### PR TITLE
Rollback to old popular selector in some Madara sources

### LINKED ISSUE #10972: Manhwa68
### Source information

Manhwa68 1.2.18

### Steps to reproduce

The manhwa are not showing on the app but working fine in webview

### Expected behavior

The manhwa should appear 

### Actual behavior

Screenshot_20220301-112410_Tachiyomi

### Tachiyomi version

Stable 0.13.1

### Android version

11

### Other details

I have just recently updated the extensions that appeared and after i opened it in the app the page was blank but its working fine in webview 
Note: the issue came after updating the extension 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #10975: Extension cant load the page
### Source information

Hentai webtoon

### Steps to reproduce

Screenshot_20220301_161715

### Expected behavior

It's should load but it doesn't, I also searched a manhwa and it comes there but no when I look for it

### Actual behavior

It's not able to connect ig. Although I can webview it, with no problem. 

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #10979: Browsing issue related to Madara extensions
### Source information

1.2.21

### Steps to reproduce

Go into 'Sources' and open the related sources.

The issue appeared after the last extension update ([#10814](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/219bf0b1d215f8a4f928663c4672297c6c742eb4) ). 

Currently, the list of sources affected are :
Manhua ES (1.2.21)
Manhua Plus (1.2.21)
ManhuaUS (1.2.20)

Likely to be related to the recent issues:
[#10972](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10972) 
[#10975](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10975)
[#10980](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10980) 

### Expected behavior

Screenshot_20220301-154329_TachiyomiSY

### Actual behavior

Screenshot_20220301-153516_TachiyomiSY
Screenshot_20220301-153521_TachiyomiSY 

Screenshot_20220301-154006_TachiyomiSY

Screenshot_20220301-154013_TachiyomiSY

### Tachiyomi version

TachiyomiSY App version: 1.8.1 (standard, 07e28ca5c, 29, 2022-02-14T01:26Z) Preview build: 441

### Android version

Android version: 12 (SDK 31) Android build ID: SP1A.210812.016.

### Other details

Additional points to note:
- Library update isn't affected. 
- Manually updating a manga from those sources isn't affected. 
- WebView works just fine. 
- Searches work just fine in the sources. Also, when cancelling the search, the 'browse' view appears without any issue.
Screenshot_20220301-154318_TachiyomiSY
 Screenshot_20220301-154329_TachiyomiSY

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #10980: Manhwatop latest & list error
### Source information

Manhwatop 1.2.17

### Steps to reproduce

Open manhwatop latest, but only 1 title show up

### Expected behavior

Latest should show a list, and the, webview is fine

### Actual behavior

Latest only show 1 title

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #10983: Madara: Missing titles in Popular and Latest
The last update to the base Madara class changed the Popular and Latest selector to filter non-image content (novels in pure text format and videos, that the app does not support). This caused an issue in some particular sources where the "No results found" error is being thrown or some image-only type titles are missing from Popular and Latest.

This problem is caused when the source:
- Customizes their Madara theme code;
- Uses an outdated Madara version;
- Incorrectly flags image-only titles as video or text.

Ideally, it's up to the site owners to fix this (if it's the point 2 and 3 of the list below), since the extension is just filtering the non-image items based on the data provided by the website. Until that doesn't happen, the extensions can have their selectors rollback to the old one individually, please **_comment on this issue_** about the source you're having issues if it's the case.

Alternatively, you can still search for the titles, since the non-image type filter isn't applied to the search.

### PR DESCRIPTION
**Pull request by alessandrojean**
Some Madara websites are incorrectly marking manga content as video or pure text format, causing the extension to filter them. Ideally this is something the site owners needs to fix, but until that, I just reverted the selector in these problematic sources.

Most Madara sources flags the content correctly, so only these problematics needs to be manually fixed in the override.

I also have run the lint tool in the overrides.

Closes #10983.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Marking as a draft to add more sources when people report them.

**Comment by Riztard** [comment]
open?
others can add to new pr

**Comment by alessandrojean** [comment]
I will just add the ones that I linked recently in the main issue and then I will open it, probably tomorrow.

**Comment by alessandrojean** [comment]
Should be okay to review and merge now.

**Pull request merged**
