### PR TITLE
Mangadex AltCover

### PR DESCRIPTION
**Pull request by FourTOne5**
It will try to get cover from related link like MAL, KU, Al etc. and if it fails then back to the original tempcover.

### CODE REVIEW

**Comment by arkon** [comment]
Sorry, but this is redundant given MD is going to add covers soon (TM).

**Comment by FourTOne5** [comment]
Well yes soon™ but as the time when soon™ will come isn't specified shouldn't this approach be taken. I mean people will like the actual cover than cover isn't available won't they?

**Comment by arkon** [comment]
It was literally announced today.

**Comment by FourTOne5** [comment]
ok.....

**Pull request closed without merging**
