### PR TITLE
reverted base URL to legacy v35 server for MangaPark v3

### LINKED ISSUE #9824: Manga Park V3
### Source information

MangaPark V3 1.2.12

### Steps to reproduce

Update new chapters

### Expected behavior

Receive updated chapters

### Actual behavior

Receive "No chapters found"

### Tachiyomi version

0.12.3

### Android version

Android 11

### Other details

Webview works normally
Screenshot_20211116-235837_Tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Jaykoerner**
Temporary measure to fix #9824 till new parser is made for the front end update in v36, this fix will likely break eventually, v36 retains the same backend as v35 so are the exact same from user perspective

Also android studio decided to edit the formatting feel free to remove formatting differences if its effects constancy.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by FourTOne5** [comment]
Use v33 if available since the extension was made on that version.

**Comment by Jaykoerner** [comment]
> Use v33 if available since the extension was made on that version.

I tried multiple, but the only versions still live are v35 and v36(if you don't count v2 since it is now a static source without updates)


I have had zero issues with useing v35 but I may very well have missed so issue, either way till the parser is fixed v35 is the best option atm with no known issues

**Comment by FourTOne5** [comment]
I'm looking into the solution for v36 but API call is using some data which I'm unable to find/understand

**Comment by Jaykoerner** [comment]
> I'm looking into the solution for v36 but API call is using some data which I'm unable to find/understand

Trust me I understand, I was messing with it for about a hour, English would be fairly easy to get back working since it's loaded by default granted the classes and ids are all alot vaguer so making a good filter for each element is a bit of a pain, the rest though...idk, granted I don't know kotlin or Java so have trouble doing much outside of simple edits

**Pull request merged**
