### PR TITLE
Update DoujinDesu.kt

### PR DESCRIPTION
**Pull request by zxc743**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Please follow the PR checklist...

> Updated `extVersionCode` value in `build.gradle` for individual extensions

**Comment by zxc743** [comment]
just fix NXDOMAIN on extension doujindesu ID

**Comment by alessandrojean** [comment]
Ok, but you still need to bump the `extVersionCode` as requested in the PR checklist.

**Comment by Username778** [comment]
Bro, can you also update manhwaid? Seems same problem

**Comment by zxc743** [comment]
Fixed on this ext. 
and need some fix for others

**Pull request closed without merging**
