### PR TITLE
Remove ShinobiScans 

### LINKED ISSUE #14457: remove shinobiscans extension
### Source link

https://shinobiscans.com/

### Other details

this is the url of the extension
https://github.com/tachiyomiorg/tachiyomi-extensions/tree/d0793a1741a80b22537c77327810d4fc2185baa1/multisrc/overrides/madara/shinobiscans

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

### PR DESCRIPTION
**Pull request by TheKingTermux**
Closed #14457 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by MeLoseAgain** [comment]
Ngab gw pen belajar buat extension, ini cuma harus pake terminal doang atau ....

**Comment by TheKingTermux** [comment]
> Ngab gw pen belajar buat extension, ini cuma harus pake terminal doang atau ....

[Disini udh ada semua, mulai alat, gmn cara kerjanya, sampe gmn bikinnya](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md)

**Comment by MeLoseAgain** [comment]
> > Ngab gw pen belajar buat extension, ini cuma harus pake terminal doang atau ....
> 
> [Disini udh ada semua, mulai alat, gmn cara kerjanya, sampe gmn bikin + check nya](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md)

Gw dah coba baca and gak ngeri sama sekali sama konsep cara pembuatannya gw kira dibuat pake Linux

**Comment by alessandrojean** [comment]
Please add as well to the REMOVED_SOURCES.md file.

**Comment by TheKingTermux** [comment]
> Please add as well to the REMOVED_SOURCES.md file.

Roger that

**Pull request merged**
