### PR TITLE
Restore Iutruyentranh, Fix bug iutruyentranh complete

### PR DESCRIPTION
**Pull request by dejavui**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by beerpiss** [comment]
I don't think it's IuTruyenTranh anymore at this point, you should've created a new source named MangaXY instead.

**Comment by dejavui** [comment]
> I don't think it's IuTruyenTranh anymore at this point, you should've created a new source named MangaXY instead. There's barely any references to IuTruyenTranh on MangaXY except for the redirect.

ext update run ok i think created a new source no necessary ~~

**Comment by beerpiss** [comment]
> > I don't think it's IuTruyenTranh anymore at this point, you should've created a new source named MangaXY instead. There's barely any references to IuTruyenTranh on MangaXY except for the redirect.
> 
> ext update run ok i think created a new source no necessary ~~

MangaXY is an entirely different website and should be treated as such.

**Comment by dejavui** [comment]
> > > I don't think it's IuTruyenTranh anymore at this point, you should've created a new source named MangaXY instead. There's barely any references to IuTruyenTranh on MangaXY except for the redirect.
> > 
> > 
> > ext update run ok i think created a new source no necessary ~~
> 
> MangaXY is an entirely different website and should be treated as such. I don't think rewriting the entire extension (+313 -122) and changing the domain counts as a bug fix lol

ok i pull new source MangaXY

**Pull request closed without merging**
