### PR TITLE
[RU]UniComics External Search

### PR DESCRIPTION
**Pull request by e-shl**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by e-shl** [comment]
Is there anyway to open a webview using another link? To pass captcha the search engine.

**Comment by alessandrojean** [comment]
> There way to open a WebView using another link(no baseUrl )? To pass captcha the search engine.

Not at the moment.

**Comment by alessandrojean** [comment]
Is this good to be merged, or it's still an WIP?

**Comment by e-shl** [comment]
> Is this good to be merged

Merge, if I haven't forgotten/broken anything with  last changed

**Pull request merged**
