### PR TITLE
Fix wrong chapter numbers in Bilibili

### LINKED ISSUE #9857: Bilibili different chapter numbering than website
### Source information

Bilibili comics 1.2.7

### Steps to reproduce

1. Open This Cultivator Came From The Future in bilibili

### Expected behavior

Same chapter numbering as on the website

### Actual behavior

Different numbering than on website

### Tachiyomi version

sy r414

### Android version

10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by alessandrojean**
This update will probably invalidate any downloaded chapters.

Closes #9857.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by FourTOne5** [comment]
chapter_number still uses order so underlying chapter number still stays wrong

**Comment by alessandrojean** [comment]
Ah, right, if the user changes the display mode it will be wrong. Thanks for the warning.

**Comment by FourTOne5** [comment]
Wouldn't it be better to just not provide chapter_number and let Tachi handle it?

Also remove chapter scanlator since the translation is done by various scanlation group and not Bilibili themselves and change the source name to be not all caps (ID will probably be same since internally they're all lowered before making ID)

**Comment by FourTOne5** [comment]
Also if chapter url is not changed Tachi will rename download folder.

**Comment by alessandrojean** [comment]
> Wouldn't it be better to just not provide chapter_number and let Tachi handle it?

I need to test if this wouldn't make the chapters to start the numbering wrong if the user changes the display mode.

> Also remove chapter scanlator since the translation is done by various scanlation group and not Bilibili themselves

Yeah, this can be done. That code is from the time they translated themselves.

> change the source name to be not all caps

Their website have the title in all caps, I just followed that, and it's better to keep as it is.

**Comment by FourTOne5** [comment]
> > Also remove chapter scanlator since the translation is done by various scanlation group and not Bilibili themselves
> 
> Yeah, this can be done. That code is from the time they translated themselves.

From the very first day everything was done by various scanlation group 😐
> 
> > change the source name to be not all caps
> 
> Their website have their name in all caps, I just followed that, and it's better to keep as it is.

Didn't notice 😜 Change the extension name to all caps then.

**Pull request merged**
