### PR TITLE
Fix mangakatana chapters only having 1 page

### LINKED ISSUE #13062: MangaKatana only loads 1 page per chapter
### Source information and language

Manga Katana 1.3.6

### Steps to reproduce

Open Tachiyomi:
1-Open Manga Katana Source
2-Click whatsoever manga
3-Click any episode
4-You ses manga chapters Page is 1/1

### Expected behavior

When you open manga, you will see that the pages should be in normal number.

Screenshot_2022-08-18-10-16-35-226_eu kanade tachiyomi

### Actual behavior

No matter how many chapters I have opened manga, all pages appear 1/1 
Screenshot_2022-08-18-09-38-15-431_eu kanade tachiyomi

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details

I tried other sources but I do not encounter this issue

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dec05eba**
Mangakatana updated their javascript and the chapter pages are now in the htnc variable. The ytaw variable only contains the first page now.
Closes #13062

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by dec05eba** [comment]
There is one issue with this. The chapter pages seem to be cached so if you open a chapter that you have previously opened while the mangakatana extension incorrectly showed only 1 page available, then that is cached and opening the same chapter will not update the available pages for a chapter. If there a way to make this update fix remove that cache?

**Comment by alessandrojean** [comment]
You can change the page list request cache mode to force network, try checking the parameters that `GET` and `POST` functions accept.

**Comment by dec05eba** [comment]
> You can change the page list request cache mode to force network, try checking the parameters that `GET` and `POST` functions accept.

Hmm, using CacheControl.FORCE_NETWORK in GET in pageListRequest in mangakatana didn't fix the issue. Are there other caches as well?

**Comment by alessandrojean** [comment]
Not really besides telling users to clear the chapter cache in the advanced settings of the app.

**Comment by dec05eba** [comment]
Alright. If there is no better solution then I guess this will have to do.

**Pull request merged**
