### PR TITLE
MangaDods: fix chapter titles, add partial chapter date

### LINKED ISSUE #17250: MangaDods chapter titles are not being displayed
### Source information

MangaDods 1.4.183

### Source language

English

### Steps to reproduce

1. Visit MangaDods source
2. Goto any Manga Screen
3. Observe the chapter entries

### Expected behavior

Chapter titles are shown properly

### Actual behavior

Chapter titles are missing.

### Tachiyomi version

r5955

### Android version

Android 11

### Other details

Image:
Chapter_Entries_Broken

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Also optimized out some unnecessary redirects.
Closes #17250 

FWIW: the popular page only has novels, so it does not show anything -- latest/search works.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by touhidurrr** [comment]
Hi @vetleledaal, an you fix the bug that the "Popular" button on MangaDods extension not working?

**Comment by vetleledaal** [comment]
The popular tab will show manga when there are manga on the website's popular page. Currently there are none, only novels, so no entries are shown.

By default Tachiyomi will not check page 2 if page 1 has no entries, which is why it's still empty.

**Comment by touhidurrr** [comment]
@vetleledaal, is there even a "Popular" section in the site? I cannot find any. I think the popular button should be disabled altogether for this source since no popular section exists and currently it gives an impression that the source is dead.

**Comment by vetleledaal** [comment]
https://mangadods.com/manga/?m_orderby=views

The popular tab can't be removed, only the latest tab can be removed. Feel free to open a separate issue for the empty popular section.

**Comment by touhidurrr** [comment]
> Feel free to open a separate issue for the empty popular section.

Thanks, I might do it. But before that are you sure that the popular section is empty in your link?

I mean I can see plenty of content in the link you gave.

> https://mangadods.com/manga/?m_orderby=views

**Comment by vetleledaal** [comment]
> are you sure that the popular section is empty in your link?
> 
> I mean I can see plenty of content in the link you gave.

Yes I'm sure. If you click on any of the chapters you will see they are just novels.

**Pull request merged**
