### PR TITLE
HeanCms: Update manga status

### PR DESCRIPTION
**Pull request by seew3l**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
I am at this moment working on some fixes on the base theme class, I hope you don't mind I addressing this as well and giving you co-author in that commit.

**Comment by seew3l** [comment]
No problem, in that case should I close this PR?

**Comment by alessandrojean** [comment]
I can close when I submit the new one, linking it as well.

**Comment by alessandrojean** [comment]
Superseded by #14887.

**Pull request closed without merging**
