### PR TITLE
[Ru]Remanga. Fix chapter number

### PR DESCRIPTION
**Pull request by Pavkazzz**
Fix chapter number for remanga

### CODE REVIEW

**Comment by arkon** [comment]
You could also just not setting it and try to let the app infer it.

**Comment by Pavkazzz** [comment]
> You could also just not setting it and try to let the app infer it.
Remanga api response with string of chapter number. Currently we have a problem with numbers like "1.2.3". Any suggestion to how truncate it to float?

**Comment by arkon** [comment]
What exactly does that mean? Is it including a volume number?

**Comment by Pavkazzz** [comment]
> What exactly does that mean? Is it including a volume number?

I doesn't realy know for sure. Maybe it's a mistake, maybe some of chapters devided by 2 parts.

**Comment by e-shl** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/5536

**Comment by arkon** [comment]
I'm fine with this change if it seems to function as expected for you.

**Comment by Pavkazzz** [comment]
@arkon thx! Can u merge?)

**Pull request merged**
