### PR TITLE
Remove ReadComicOnline due to a cat-and-mouse game

### LINKED ISSUE #11406: Readcomiconline Doesn't load the comic pages when clicking retry
### Source information

Readcomiconline 1.2.12

### Steps to reproduce

When I click retry the pages won't load.
All the comics on the extension does the same it won't load the pages

### Expected behavior

Can fix this new update of the extension problem? 

### Actual behavior

Screenshot_20220409_215620_eu kanade tachiyomi

### Tachiyomi version

0.13.1

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
The recent update has also stopped working.

Co-authored-by: Alessandro Jean <14254807+alessandrojean@users.noreply.github.com>

Closes #11406

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by alessandrojean — APPROVED** [review]

**Comment by alessandrojean** [comment]
Just another proof they're in a cat and mouse game with us. Not worth keeping the support and neither the extension, it's clear they don't want it. Should be okay to remove it.

**Comment by Penben** [comment]
Can anyone give me an alternative to it? I've always used this site to read comics. The other extension with the same name has a smaller database and I didn't like it.

**Comment by FourTOne5** [comment]
> Can anyone give me an alternative to it? I've always used this site to read comics. The other extension with the same name has a smaller database and I didn't like it.

NO! Find one yourself recommending will lead to that extension to be also removed.

**Comment by MikeCastle2002** [comment]
Damn, that's sad

**Pull request merged**
