### PR TITLE
Update domain Hentai20, Hentaidexy, Nhattruyen, Nettruyen, HentaiVN

### LINKED ISSUE #14050: Hentai20: Changed their domain
### Source information and language

Hentai20 1.3.26

### Source new URL

https://hentai20.io

### Other details

The extension webview goes to hentai20.s before redirecting to the new one. The Browse -> Sources leads to error 400. Going to site and opening a specific manga and then using Open in extension method also doesn't work as the supported web addresses for the extension is only the .s form.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14397: Hentaidexy
### Source information and language

Hentaidexy 1.3.28 English

### Source new URL

https://www.hentaidexy.net/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14452: Hentaidexy source change
### Source information and language

Hentaidexy 1.3.28

### Source new URL

https://www.hentaidexy.net

### Other details

Using webview directly opens the new source but inside app 404 error arrives as old source is
https://www.hentaidexy.com

newone is
https://www.hentaidexy.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14490: Nettruyen, Nhattruyen Changed their domain
### Source information and language

Nhattruyen 1.3.12, Nettruyen 1.3.14

### Source new URL

https://nhattruyenmin.com , https://www.nettruyenmin.com

### Other details

@dejavui 

1. Close #14478  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dejavui**
- Update domain Hentai20, Hentaidexy

1. Closes #14050 
2. Closes #14452 
3. Closes #14397 
4. Closes #14490 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by kiriya-aoi** [comment]
> Referenced all related issues **in the PR body** (e.g. "Closes #xyz")

This means that right here, in your first post, you should say
Closes #14050 
Closes #14452 
Closes #14397
since those are the issues you want to close.

Please work through the checklist and be sure you have completed each item, as appropriate.

**Comment by Soitora** [comment]
No merge until you start using issue linking correctly

**Comment by BLACKxSUN** [comment]
Thanks for your hard work 💕

**Comment by BLACKxSUN** [comment]
Hentaidexy still not work
I already update it

**Comment by BLACKxSUN** [comment]
When i try open any work from app this is the link showed
Screenshot_٢٠٢٢١٢٠٩-١٩٢٧٢٥_Chrome
It say 404 the page could not be found

And when i open the same work from the website this is the link showed 
Screenshot_٢٠٢٢١٢٠٩-١٩٢٩١٠_Chrome

**Pull request merged**
