### PR TITLE
BatoTo: Replace CryptoJS use with javax.crypto

### PR DESCRIPTION
**Pull request by pratyush3757**
Removed quickJS dependency which causes the extension to not run on Tachidesk-Server.
Tested viewing and downloads with https://bato.to/chapter/2057246 and various other chapters. 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by stevenyomi** [comment]
Can this be applied to Comico and MangaPark too?

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/4b956148e1da2b61205e3f205c84d2a23ab984b5/src/all/comico/src/eu/kanade/tachiyomi/extension/all/comico/Comico.kt#L169-L176

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/e96fd22d307d5cc46cbf7e3ecbbbffb644f0fcda/src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt#L263-L266

**Comment by pratyush3757** [comment]
> Can this be applied to Comico and MangaPark too?

I'm planning to apply this to mangapark after this in a seperate PR, but haven't checked Comico. 
> https://github.com/tachiyomiorg/tachiyomi-extensions/blob/4b956148e1da2b61205e3f205c84d2a23ab984b5/src/all/comico/src/eu/kanade/tachiyomi/extension/all/comico/Comico.kt#L169-L171

This says empty IVs aren't supported, I have to try something to bypass that. 
I think CryptoJS uses 0x00 bytes as IV under the hood, not an empty array. Becasue AES needs an IV to function.

**Comment by pratyush3757** [comment]
Or should I include the changes for Mangapark in this PR?

**Comment by stevenyomi** [comment]
Would be best if the crypto code can be extracted to a separate lib (like what I did for the code to decode packer-encoded snippets).

@arkon Can we just add these libs to `lib/` in this repo? I can move my Unpacker code to this repo too.

**Comment by arkon** [comment]
> Can we just add these libs to lib/ in this repo? I can move my Unpacker code to this repo too.

We could, although it'd introduce some redundant module building per run. It'd probably be ideal to actually move them to another repo.

**Comment by stevenyomi** [comment]
I've opened a PR to move the unpacker script. @pratyush3757 You can copy the dataimg lib's structure to make a new module. You also need to add it to `settings.gradle.kts`.

**Comment by pratyush3757** [comment]
Uh, I've migrated it to a module but I'm not familiar enough with kotlin and gradle.
Although it's building and running correctly, can you review the code and build files for any problems?
I'm not sure if the build process has any redundancy.

**Comment by stevenyomi** [comment]
Looks good. Just that the deobfuscator should only be in the lib if another source also uses it. If it's exclusive to Bato.to, you should move it inside the source.

**Comment by pratyush3757** [comment]
The deobfuscator will be used by mangapark too.

**Comment by stevenyomi** [comment]
Also I think it's okay to include other sources in this PR if the replacement is the only change.

**Comment by pratyush3757** [comment]
> Also I think it's okay to include other sources in this PR if the replacement is the only change.

Yeah, I'm almost done changing mangapark. Will probably take some time on Comico.

**Pull request merged**
