### PR TITLE
Nekopost extension: Search fix (HTTP error 520)

### PR DESCRIPTION
**Pull request by Taihenc**
fix Nekopost search HTTP error 520
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Taihenc** [comment]
->

**Comment by AntsyLich** [comment]
Review sent through discord

**Comment by CarlosEsco** [comment]
@AntsyLich This look better?

**Comment by Taihenc** [comment]
His review was: 
"Switch to HttpSource from ParsedHttpSource
and and don't use fetchXXX functions rather use the XXXrequest and XXXparse functions"
I've made the changes, so it should be good now.🥺

**Pull request merged**
