### PR TITLE
Japscan: Fix date

### PR DESCRIPTION
**Pull request by nzoba**
The span is in another div if you use a mobile user-agent

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by oktapodia** [comment]
@nzoba is japscan currently working on your side? Can't load anything here

**Comment by nzoba** [comment]
Yes it works for me when I set a mobile user-agent in the advanced settings

**Comment by oktapodia** [comment]
@nzoba interesting, is it possible for you to share the useragent you are using? I may do a pull request with something similar

**Comment by nzoba** [comment]
Just a random one :
```
Mozilla/5.0 (Linux; U; Android 8.0.0; SM-G935F Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.110 Mobile Safari/537.36 OPR/52.1.2254.54298
```

**Comment by DaMakoumba** [comment]
Thanks for the user-agent tip ! ;)

**Comment by louis1706** [comment]
> Thanks for the user-agent tip ! ;) 

It's work for you for me it's don't?

**Comment by oktapodia** [comment]
Gonna try to make something automatic for that when I'll find time, thanks for sharing it

**Comment by alessandrojean** [comment]
It's better to not set an explicit user agent in the extension code so the users can still change through the app settings when they need, as it is now. Locking this comments as this isn't an issue and not a proper place for support.

**Pull request merged**
