### PR TITLE
add inspector

### PR DESCRIPTION
**Pull request by AriaMoradi**
Generates a source-id mapping database.

example output: https://github.com/AriaMoradi/tachiyomi-extensions/blob/repo/inspector.txt

### CODE REVIEW

**Comment by arkon** [comment]
I feel like you could do this fully in your own repo (i.e. `git clone` this repo, then run it in a workflow there)?

**Comment by AriaMoradi** [comment]
I can run it on more extensions, but getting the singing keys to work is a bit of pain

**Comment by arkon** [comment]
You don't need signing keys; the IDs don't change between debug and release versions.

**Comment by arkon** [comment]
Closing since you said it's not ready yet on Discord.

**Pull request closed without merging**
