### PR TITLE
add two new sources to madara & remove two sources

### PR DESCRIPTION
**Pull request by CVIUS**
- add aqua manga & mangatone
- remove mangalazy, mangadna

### CODE REVIEW

**Comment by Riztard** [comment]
there is already mangafast ext so i think it will cause some issue #5767

**Comment by CVIUS** [comment]
I made it manga-fast.com, wdyt?

**Comment by Riztard** [comment]
try build on pc?

**Comment by Riztard** [comment]
why remove mangalazy and mangadna?

**Comment by CVIUS** [comment]
> why remove mangalazy and mangadna?

its not working, and can't fix it 😅 and I'll make a request about it instead after this is merged

**Comment by Riztard** [comment]
i think better to say something like `remove mangaduck`, cuz ext changelog is using github commit

**Pull request merged**
