### PR TITLE
Fix Manhuaren parameters

### LINKED ISSUE #17971: 漫画人 / Manhuaren: can't use without opening the official app first
### Source information

Manhuaren 1.4.14

### Source language

Chinese

### Steps to reproduce

1. Tap Browse
2. Tap Sources
3. Tap 漫画人

### Expected behavior

Manga are shown

### Actual behavior

JSONException: No value for response

### Tachiyomi version

r6049

### Android version

Android 13

### Other details

**This can temporarily be fixed by opening the official app**, no interaction is required. Seems to be IP based.

For debugging, use apk-mitm and mitmproxy. Captures from the official app, with values stripped:
(createAnonyUser2 is used by the extension, but errors out)
```
Initial:
http://mangaapi.manhuaren.com/v1/user/getRegistrationRule?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
http://mangaapi.manhuaren.com/v2/user/getUserCertifyMessage?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
http://mangaapi.manhuaren.com/v1/user/createAnonyUser2?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
http://mangaapi.manhuaren.com/v1/public/getBaseurl?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
http://mangaapi.manhuaren.com/v1/user/getMessage?version=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v2/ad/getMultiAdsStrategy?viewName=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=


Reopen after <5 minutes:
http://mangaapi.manhuaren.com/v1/public/getBaseurl?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v1/user/getRegistrationRule?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v2/user/getUserCertifyMessage?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v2/ad/getMultiAdsStrategy?viewName=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v1/user/getMessage?version=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=

8 minutes later ...:
http://mangaapi.manhuaren.com/v1/public/getBaseurl?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v1/user/getMessage?version=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=

6 minutes later...:
http://mangaapi.manhuaren.com/v1/public/getBaseurl?gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
https://mangaapi.manhuaren.com/v1/user/getMessage?version=&gsm=&gsn=&gut=&gac=&gflot=&gos=&gcut=&glbsaut=&gem=&gfut=&gov=&gfcc=&gak=&gcl=&gflcc=&gat=&gcy=&gav=&gaui=&glcn=&gle=&gts=&gln=&glat=&gpt=&gflg=&gdi=&gciso=&gft=&glut=&glcc=&gfcl=&gui=&glot=&gflat=
```
              "No value for response" error still persist.

_Originally posted by @a0193143 in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17170#issuecomment-1722121160_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by felixfon**
Avoid blocking by using real Android model, randomizing build ID, and saving the token.
I have tested this version for over a month, and no errors have occurred.

Closes #17971

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by vetleledaal** [comment]
Fixed t he failing build on my local copy, but still getting the same issue when `token` or `userId` is not initialized. Requires you to open the official app first before you can make an anonymous user.
Screenshot_20230917_113438

**Comment by felixfon** [comment]
> Fixed the failing build in my local copy, but still getting the same issue when `token` or `userId` is not initialized. Requires you to open the official app first before you can make an anonymous user.

It's possible that your IP or device has been blocked. Can you try again in a few hours?

**Comment by vetleledaal** [comment]
yeah, nah, it just doesn't want to register a new user without opening the official app first. see:

https://github.com/tachiyomiorg/tachiyomi-extensions/assets/13540478/69939130-4260-402b-9868-fef06f4c2c40

**Comment by alessandrojean** [comment]
@felixfon You will need to figure it out which request the official app is doing to request an IP to be whitelist and replicate it on the extension side. Randomizing the build ID doesn't seem a good idea as it was told before, it's easy to verify if a IP is sending different build IDs in a short period of time.

**Comment by felixfon** [comment]
> @felixfon You will need to figure it out which request the official app is doing to request an IP to be added to the allowlist and replicate it on the extension side. Randomizing the build ID doesn't seem a good idea as it was told before, it's easy to verify if a IP is sending different build IDs in a short period of time.

Currently, the extension will retain and reuse the obtained token until an error occurs.
I have been using this version for over a month, and it runs perfectly.
However, I will still follow your suggestion and remove the randomized build ID.

**Comment by felixfon** [comment]
> yeah, nah, it just doesn't want to register a new user without opening the official app first. see:
> 
>  ren.mp4

The situation in the video looks strange, and I haven't encountered such a situation before. I guess it could be due to some mocked parameters causing the impact. I'll try removing the randomized build ID first and see how it goes.

**Comment by vetleledaal** [comment]
> I guess it could be due to some mocked parameters causing the impact.

The issue occurs here:
```kt
if (token == null || userId == "-1") {
```

When this condition is true it will fail. Everything else doesn't really matter, the difference is that you are reusing a token set ages ago.

If you have root, you can confirm this is the issue by:
- Deleting `/data/data/eu.kanade.tachiyomi.debug/shared_prefs/source_3616827811449702173.xml` (assuming you use Tachiyomi Preview)
- Restart Tachiyomi
- Change IP _or_ wait >2 hours
- Try browsing popular in Manhuaren

If you don't have root, just modify the condition so it's always true instead.

**Comment by felixfon** [comment]
> When this condition is true it will fail. Everything else doesn't really matter, the difference is that you are reusing a token set ages ago.

As I mentioned earlier, I've been using the old token for over a month without any issues. I don't think it's because the token has expired; rather, frequent requests for a token might lead to it being blocked.
What do you think the correct condition should be?

**Comment by vetleledaal** [comment]
I think the condition is fine as it is, and saving the token for later is a decent improvement.

However, I think you are making it more difficult to test for yourself by reusing the token. New users will run into issues with creating tokens if they do not open the official app first.

For testing purposes; I would set the condition to `if (true) {` and figure out how to make it work consistently without requiring the official app.

**Comment by alessandrojean** [comment]
Closing as it seems to be stale. Feel free to open a new PR when you're done with the changes.

**Pull request closed without merging**
