### PR TITLE
comick: some update

### PR DESCRIPTION
**Pull request by iD-666**
# What's new:
- MangaUpdates categories have been added to the genres.
- "Content rating: Safe," "Content rating: Suggestive," etc. have been added to the genres.
- Related series (Prequel, Sequel, Same universe, Doujinshi, etc.) have been added to the description.
- "Published: year" & "Followed by: n users" have been added to the description.
### New filters:
- Author/Artist/Scanlator search
- Include/Exclude filters when searching for comics
### Other changes:
- Improved tag search filter to acceptable slug
- The `Most popular` sort is deprecated; new comics now use `sort = user_follow_count` instead. However, you can still use it.
- URLs now support deep linking to the app.

&nbsp;

&nbsp;
 
>After rigorously training for three years, the ordinary Saitama has gained immense strength which allows him to take out anyone and anything with just one punch. He decides to put his new skill to good use by becoming a hero. However, he quickly becomes bored with easily defeating monsters, and wants someone to give him a challenge to bring back the spark of being a hero.
>
>&nbsp;
>Coloured: One Punch-Man (Fan Colored)
>Pre-serialization: One Punch Man (Webcomic/Original)
>
>Alternative Titles:
>• ワンパンマン
>• 원펀맨
>• OPM
>
>Published: 2012
>Followed by: 26,427 users

&nbsp;

&nbsp;

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
Note to maintainers: this pr is very much untested and contains code written by generative ai. It is filled with logical errors which will break the extension. So please don't merge this until it is properly tested and fixed.

**Comment by iD-666** [comment]
Thanks for pointing that out. Could you please clarify where the logical error might be? I opened the pull request because I need a review.

If you could send me the .apk that would be great :)

**Comment by AntsyLich** [comment]
Given that this pr hasn't been tested once in 3 weeks I'm gonna close it.

Feel free to make a new PR after you code and test the stuff yourself.

You can also open a feature request so someone else can look into it

**Comment by iD-666** [comment]
Ok. Sorry if I were bothering you guys... I'll try making another version which uses simple synchronous call before opening a feature request

**Comment by iD-666** [comment]
I noticed a lot of issues in the code ;-;

**Pull request closed without merging**
