### PR TITLE
Fixed chapter dates for MangaJar

### LINKED ISSUE #7001: [Bug] <MangaJar> Tachiyomi doesn't load more than 50ch.
MangaJar is a very good site for Manga and Manwha, but thanks to their layout Tachiyomi cannot load more than 50 chapters in-app.

#### Example:

`In App` 

https://i.imgur.com/qHaL8Zl.png

`On Web` 

https://i.imgur.com/xBwRE6A.png

## Expected Behavior

Open Manga and be able to see all 193 (Or whatever the number listed on the site) chapters.

## Actual Behavior

Open Manga and see only 50 latest chapters listed on the website, and not all chapters.

### Steps to Reproduce

1. Have MangaJar as an extension;
2. Enter MangaJar source to get Manga;
3. Open any Manga (Or most of them) with more than 50ch;
4. See that it doesn't load all chapters, only 50 latest.

### LINKED ISSUE #8773: Mangajar: no date on chapter list
### Source information

Mangajar 1.2.6

### Steps to reproduce

Open any manga

### Expected behavior

It should have date.
Screenshot_20210823-134417_Tachiyomi~2

### Actual behavior

No date.
Screenshot_20210823-134422_Tachiyomi~2

### Tachiyomi version

0.12.1

### Android version

10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Arraiment**
Closes #8773 
#8117 also closes #7001

### CODE REVIEW

**Comment by CVIUS** [comment]
MangaJar*

**Comment by Riztard** [comment]
add `Closes` in front of `#8117` so the issue will get linked

**Comment by Arraiment** [comment]
> add Closes in front of #8117 so the issue will get linked

#8117 is a merged pr that resolves the other issue

**Comment by Riztard** [comment]
> #8117 is a merged pr that resolves the other issue

ah, ithought it was an issue

**Pull request merged**
