### PR TITLE
Add source QuegnaReader

### LINKED ISSUE #7405: [Source Request] <QuegnaTT>
## Source website - pignaquegna.altervista.org
- Name: QuegnaTT
- Link:
Forum: qtt.forumcommunity.net
Reader: pignaquegna.altervista.org
- Language(s): Italian

## Other details
It's the exact same layout as the italian PhoenixScans Extension. Here are some examples:
https://www.phoenixscans.com/reader/series/domestic-na-kanojo/
http://pignaquegna.altervista.org/

### PR DESCRIPTION
**Pull request by somebody1234**
Closes #7405

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Icons?

**Comment by CarlosEsco** [comment]
@as280093

**Comment by AlexMiniReal** [comment]
photo_2019-04-22_02-23-15

This is their Telegram Channel Icon. @CarlosEsco

**Comment by AlexMiniReal** [comment]
Do you need anything else? (I don't see the reader in tachiyomi yet)

**Pull request merged**
