### PR TITLE
ZinChanManga: re-add to Madara

### LINKED ISSUE #9491: ZinChanManga: Browse is also Latest
### Source information

ZinChanManga 1.2.1

### Steps to reproduce

1. Browse in ZinChanManga extension

### Expected behavior

The "Trending" from the site should be displayed in Browse.

### Actual behavior

Browse is also displaying Latest.

### Tachiyomi version

0.12.3 r3875

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15276: Zinchanmanga.net to .com
### Source information and language

ZinChanManga 1.4.5

### Source new URL

https://zinchanmanga.com/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15644: Requesting to re add Zinchanmanga.com
### Source name

Zinchanmanga.com

### Source link

https://zinchanmanga.com

### Language

English

### Other details

18+ = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mobi2002**
closes #15644
closes #15276
closes #9491

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Did you verify that it works? It wouldn't load the chapters when I tried to migrate it to Madara.

**Comment by mobi2002** [comment]
Yes I checked and it worked fine. Please tell me any series/chapter that didn't work for you so I can test it as well.

**Comment by ObserverOfTime** [comment]
I don't remember. I just opened a few random series and the chapters wouldn't load.

**Comment by mobi2002** [comment]
It's fine then, if the problem occurs again, someone will report it

**Pull request merged**
