### PR TITLE
MangaHub: fix random user agent

### PR DESCRIPTION
**Pull request by mobi2002**
Fixes the json error recently introduced by the changes in user-agents.json 

Not sure if using `!!` is a good approach here as it will throw an `NullPointerException`  when `uaList["desktop"]` is null.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by AntsyLich** [comment]
Rest assured `uaList["desktop"]` won't be null unless the format is changed again

And I fat fingered it

**Comment by AntsyLich** [comment]
Btw update the comment to say chromium browsers since all chromium browsers has chrome in their ua

**Comment by mobi2002** [comment]
should I also modify the REMOVED_SOURCES.md?

**Comment by vetleledaal** [comment]
Go for it, was left out of the previous PR by mistake

**Pull request merged**
