### PR TITLE
Remove Constellar Scans

### LINKED ISSUE #17251: constellarscans ain't showing any images
### Source information

"Constellar Scans 1.4.40"

### Source language

English

### Source new URL

https://constellarcomic.com/

### Other details

it will show the cover and the chapters but when you open them it's empty.. please fix this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by beerpiss**
Cat and mouse game

Closes #17251

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by vetleledaal** [comment]
> * [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")

#17251

**Comment by rahaaatul** [comment]
Can't install the app from unofficial repo. @beerpiss 

`App not installed`

**Comment by beerpiss** [comment]
Have you uninstalled the official extension before installing mine? 

If not, please try installing with [Split APK Installer](https://play.google.com/store/apps/details?id=com.aefyr.sai) for more detailed errors.

Please create an issue on my repo for any further troubles. This is not a support thread.

**Comment by AntsyLich** [comment]
You should take a doctor checkup since you can only see the word download and nothing else

**Comment by rahaaatul** [comment]
Are you an esper or something? Because if you are,  you're a fake one.

**Comment by AntsyLich** [comment]
Oh then you're just stupid since you saw the issues link and still proceeded to ask here

**Comment by rahaaatul** [comment]
I may or may not be. But you're so stupid to think that I can't ask here, just because a issues link linked.

From next time try to be respectful towards others, that'll do you a whole lot better.

**Pull request merged**
