### PR TITLE
Add ratelimit to MangaXYZ

### LINKED ISSUE #13182: MangaXYZ: Add rate limiting to requests
### Source information and language

MangaXYZ 1.3.8

### Steps to reproduce

i update my library and it says 129 update error 
and shows error 429

### Expected behavior

i expected a good outcome

### Actual behavior

it says Error 429

### Tachiyomi version

1.8.5

### Android version

Android 8

### Other details

[Screenshot_20220825-135815_Chrome](https://user-images.githubusercontent.com/112059542/186586393-3ade9faa-f254-4e66-9932-b8b5570b1540.jpg)`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mobi2002**
Closes #13182

I am not too sure if this much rate limit is enough or it should be more.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by vetleledaal** [comment]
The rate limiting on the chapters endpoint probably applies to all sources in MadTheme, but even 1 req per 10 seconds isn't enough. See https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12613#issuecomment-1186589000

**Comment by mobi2002** [comment]
From what I can tell, the existing rate limit doesn't apply to actual chapter list fetching, only on the chapter images.

For the other point, should i increase the rate limit?

**Comment by mobi2002** [comment]
So I have increased the rate limit to 1 request every 4 seconds.

**Comment by vetleledaal** [comment]
Seems like they tweaked it a bit, you can do 50 requests per 10 minutes to the /chapters endpoint that results in non-cached responses. A cached response is identified with the header "CF-Cache-Status: HIT". Other values such as "MISS" or "REVALIDATED" are not cached.

When you exceed the quota you get a response like this:
```
HTTP/1.1 429 Too Many Requests
Date: ...
Content-Type: application/json; charset=utf-8
Content-Length: 75
Connection: keep-alive
Access-Control-Allow-Origin: *
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
sv: 1
Cache-Control: no-cache
ETag: ...
Vary: Accept-Encoding
CF-Cache-Status: EXPIRED
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: ...
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: ...
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

{"message":"You sent too many requests. Please try again after 7 minutes."}
```

If we assume no cached responses you can set the rate limit on the /chapters endpoint to 1 request per 12 seconds. Since half of the requests are against the manga details page, you can set it to 1 request per 6 seconds.

This is what I would do:
- Use another `client` in `fetchChapterList()` that's rate limited to 1 per 12s
- Make `fetchChapterList()` use `.asObservable()` instead of `.asObservableSuccess()`
- throw an `Exception` in `chapterListParse()` if HTTP status isn't in range 200..299
  - Use the message in the body if available, otherwise some generic error
- Add this to the abstract MadTheme class instead of just MangaXYZ


If you're not sure how to do this, I might be able to dedicate some time to this tomorrow.

**Comment by mobi2002** [comment]
Thank you for the detailed response. I will try to  implement this.

**Pull request closed without merging**
