### PR TITLE
Gmanga: fix search request and chapter parsing

### LINKED ISSUE #6993: [Bug] GMANGA: Chpaters sort not correct
## Device information
- Tachiyomi version: 0.10.12-3354 (standard, 47c120e5, 60)
- Android version: 10

## Source information
- Name: GMANGA
- Extension version: 1.2.5

## Steps to reproduce
1. Join any manga/manhua
2. Look at the chapters order (by source)

### Expected behavior
the sort by source should be like the website, by volumes and chapters numbers

### Actual behavior
Randomly and not sorted well, i have to sort it manually for some reason.

### LINKED ISSUE #10445: GManga is broken
### Describe why this should be added

Migrate to a different source, or wait for a fix.

Known errors:
Chapters don't load (Gson.toJson error)
Http code 103

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #10445
Closes #6993

There is still a toast saying "HTTP error 103" when refreshing manga. Unsure how to hide this.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by vetleledaal** [comment]
Marked as draft to fix the 103 issue tomorrow:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/4b26f2a01f6a74168dfbd7d63a44e7a1f20b5a80/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt#L290-L297
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/4b26f2a01f6a74168dfbd7d63a44e7a1f20b5a80/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt#L86-L90

**Comment by arkon** [comment]
I suspect we'll want to just ignore all 103s from the app side, but feel free to do it in the extension for now.

**Comment by vetleledaal** [comment]
After ignoring HTTP error 103 another toast shows: "expected 0 bytes but received 2774"
Looks like it's caused by:
https://github.com/square/okhttp/blob/500ba31ada1ed156c5d2e8c5d90c818c5ea34cc4/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/Exchange.kt#L220

**Review by CarlosEsco — COMMENTED** [review]
there is no reason to [skip ci] on a commit when ci doesnt run for drafts

**Pull request merged**
