### PR TITLE
Update DoujinDesu.kt

### PR DESCRIPTION
**Pull request by RizkiMaulana203**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
You haven't followed the checklist:

> Updated `extVersionCode` value in `build.gradle` for individual extensions

Also, since it seems to be commited from GitHub Website, have you tested and compiled the extension through Android Studio?

**Comment by RizkiMaulana203** [comment]
not yet, because I don't have a PC or laptop to test it

Pada tanggal Sen, 18 Apr 2022 21.27, Alessandro Jean <
***@***.***> menulis:

**Comment by alessandrojean** [comment]
I have just now realized is a IP in the `baseUrl`. We don't accept IPs as a security measure.

If the website haven't setup a domain yet, you need to wait until they setup it so it can be updated in the extension. Closing for now, but feel free to open a new PR when they setup a proper domain.

**Comment by RizkiMaulana203** [comment]
Ok, thanks for the update.

Pada tanggal Sen, 18 Apr 2022 21.37, Alessandro Jean <
***@***.***> menulis:

**Pull request closed without merging**
