### PR TITLE
<zh-dmzj>Add ratelimit to fix HTTP 429 and return webpage url to "Open in browser" and "Share manga".

### PR DESCRIPTION
**Pull request by Oldwangtouchtouchdoge**
1. Add ratelimit to fix HTTP 429 Too Many Requests when updating library.
2. Add workaround to allow "Open in browser" and "Share manga" use webpage url. Like #5511.
<del>3. Rewrite the rate limit interceptor that only work for manhuagui, now it can work for any url and handles multiple url host's rate limiting separately. Since extensions can't override fetchImage function, this interceptor is a workaround to allow web page urls and imageCDN urls can have different rate limit setting.</del>

### CODE REVIEW

**Comment by Oldwangtouchtouchdoge** [comment]
About removing nsfw mark, #5524 request to remove it, and strictly speaking, the R18+ contents in dmzj are mostly unvisitable, banned or censored now, so I think I was a bit hasty to add nsfw mark before.

**Comment by ZerOri** [comment]
感谢修复~😀

**Comment by Oldwangtouchtouchdoge** [comment]
I still have something need to change🤣

**Comment by Oldwangtouchtouchdoge** [comment]
An interceptor that only handle one specific url host and add multiple these interceptors to an okhttp client should be more elegant than an interceptor accept an array of url hosts and handle them one by one.🤣

**Comment by Oldwangtouchtouchdoge** [comment]
Tuned up v3api's default rate limit permits from 2 to 5 per second.

**Pull request merged**
