### PR TITLE
LeerCapitulo: Fix index out of bound

### LINKED ISSUE #16209: LeerCapitulo: Chapters does not open
### Source information

Leercapitulo 1.4.3 (Español) 

### Source language

Español 

### Steps to reproduce

1.entrar en un manga que esté en dicha extensión
2.intetar abrir o descargar un capítulo 

### Expected behavior

Debería poder ver o descargar los capítulos correctamente 

### Actual behavior

En su lugar aparece un mensaje " Index:45, Size:15" y no se abre 
Screenshot_2023-04-27-14-25-58-065_eu kanade tachiyomi
Screenshot_2023-04-27-14-32-14-656_eu kanade tachiyomi

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

Screenshot_2023-04-27-14-32-14-656_eu kanade tachiyomi
Screenshot_2023-04-27-14-25-58-065_eu kanade tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by seew3l**
Closes #16209

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by KaiZer32s** [comment]
Ahora funciona la extensión?

**Comment by DarkDissaster** [comment]
La extensión sigue sin funcionar

**Comment by seew3l** [comment]
Lo volvieron a romper

**Comment by jjgreedo** [comment]
Not functioning 04/29/2023 at 4:32 P.m.

**Pull request merged**
