### PR TITLE
fix cubari upload date

### LINKED ISSUE #8076: Cubari: Loading chapter list for MangaDex series on Cubari fails with "For input string..."
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Source information

Cubari 1.2.7

### Steps to reproduce

1. Load a MangaDex series on Cubari into Tachiyomi (example: https://cubari.moe/read/mangadex/e83c326b-921b-45ff-bc0c-d667bbfe64cc/)
2. Open chapter list

### Expected behavior

Chapters should appear

### Actual behavior

Error message appears: `For input string: "1591132048.0"`

### Other details

The series that produced this exact error message is https://cubari.moe/read/mangadex/e83c326b-921b-45ff-bc0c-d667bbfe64cc/. The corresponding API page is https://cubari.moe/read/api/mangadex/series/e83c326b-921b-45ff-bc0c-d667bbfe64cc/.

This appears to only happen with MangaDex series on Cubari. However, it appears to be related to the processing of upload dates by the extension (since `1591132048` is the upload time of one of the chapters), so it will likely affect other sources on Cubari such as gist and Imgur once upload date support comes to their APIs (see https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6663#issuecomment-877925247). I think it's best to look into it before it becomes a bigger problem.

### PR DESCRIPTION
**Pull request by Seishirou101**
closes #8076

Not sure if this is the best way to fix, but tested with
https://cubari.moe/read/mangadex/e83c326b-921b-45ff-bc0c-d667bbfe64cc/
https://cubari.moe/read/mangadex/e78a489b-6632-4d61-b00b-5206f5b8b22b/
https://cubari.moe/read/mangadex/9cc3be97-91c6-4ed7-ad28-dd396699ea87/
https://cubari.moe/read/gist/OPM/

### CODE REVIEW

**Comment by funkyhippo** [comment]
I'm a bit concerned about the portability of this fix. You could instead deserialize it as a double then cast it back into a long.

**Comment by Seishirou101** [comment]
> 
> 
> I'm a bit concerned about the portability of this fix. You could instead deserialize it as a double then cast it back into a long.

sounds like a plan, i will take a look into doing it that way

**Comment by Seishirou101** [comment]
not sure if this is the correct way to deserialize and cast... but I changed it from the sketchy method from before.

**Comment by alessandrojean** [comment]
> not sure if this is the correct way to deserialize and cast... but I changed it from the sketchy method from before.

Sounds good now.

**Pull request merged**
