### PR TITLE
Fix japscan urls

### PR DESCRIPTION
**Pull request by Kantus1511**
Update japscan url.

 Closes:
- https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12574
- https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12491

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Gushaa** [comment]
Yep it's change my bad to don't see it before

**Comment by oktapodia** [comment]
Are you sure that this fixed it @arkon ? Still have the same issue locally

**Comment by arkon** [comment]
Open another issue or PR as needed; the PR reviewers aren't responsible for checking if the changes worked.

**Comment by Gushaa** [comment]
> Are you sure that this fixed it @arkon ? Still have the same issue locally

Hello,

Do you update the extension ?
Do you try to cancel the current downloading files to refresh the download ?

**Pull request merged**
