### PR TITLE
Flamescans fix

### PR DESCRIPTION
**Pull request by CVIUS**
I messed it up, my bad ༎ຶ‿༎ຶ

### CODE REVIEW

**Comment by conztanz045** [comment]
@CVIUS what have you done hahahah

**Comment by CVIUS** [comment]
@conztanz045 I messed it up༎ຶ‿༎ຶ I swear I'll never touch flamescans again. 🙏

**Comment by conztanz045** [comment]
When the update will show??

**Comment by Riztard** [comment]
> When the update will show??

when released

> I messed it up, my bad ༎ຶ‿༎ຶ

did you not try it first?

**Comment by conztanz045** [comment]
@CVIUS  
Screenshot_2021-07-03-17-25-15-79_afd66b7916d19a60815f56273408b73e
It show this

>

**Comment by CVIUS** [comment]
nah, i was in hurry that time due to some personal errands. gomen🙏

**Pull request merged**
