### PR TITLE
[Mangadex] Fix authorMap being empty

### LINKED ISSUE #6903: [Bug] Mangadex:  Author field wiped after new extension update
## Device information
- Tachiyomi version: r3346 (most recent release)
- Android version: 9

## Source information
- Name: Mangadex
- Extension version: 1.2.108

## Steps to reproduce
1. Refresh a manga in your library

### Expected behavior
Fixes from the new update (like getting rid of blank chips) will be applied, without touching the other correct information

### Actual behavior
The fixes are applied, but it also wipes the author field, and sets it to "Unknown Author"

## Other details
N/A

### PR DESCRIPTION
**Pull request by FlaminSarge**
I can't read json, evidently.

Closes #6903

### CODE REVIEW

**Comment by arkon** [comment]
Pending some other planned changes.

**Comment by specterflare** [comment]
Just out of curiosity, what does that mean? That you're going to wait to merge this until you have accumulated more fixes, or that Mangadex is planning changes to their API? Either way, can you guess when this fix will be applied? It's kinda annoying to be unable to easily check what other works a particular series author has.

**Comment by FlaminSarge** [comment]
There's one more change for content rating filters that's going to go in alongside this that I'm currently working on.

**Comment by arkon** [comment]
There's other changes being worked on by the PR author.

**Comment by FlaminSarge** [comment]
I couldn't figure out the content rating change, was getting an NPE during onSetInitialValue in the preference despite neither mValues nor mDefaultValue being null. Splitting the author fix away as I won't be able to work on the content rating thing until later tonight.

**Pull request merged**
