### PR TITLE
Madara update

### LINKED ISSUE #4319: [Source Request] Spooky Scans
### Source Website 

- Name: Spooky Scans

- Link: https://spookyscanlations.xyz

- Language(s): English

### LINKED ISSUE #5116: [Source Request] <Atikrost>
## Source Website
- Name: Atikrost
- Link: manga.atikrost.com
- Language(s): turkish

## Other Details
?

### LINKED ISSUE #5123: [Source Request] <Random Translatation>
Hello can you add this site.
## Source Website
- Name: Random Translatation
- Link: https://randomtranslations.com/
- Language(s): English

### LINKED ISSUE #5143: [Source Request] <StageComics>
## Source Website

- Name: StageComics 
- Link: https://stagecomics.com/
- Language(s): pt-BR

### LINKED ISSUE #5159: [Meta] Remove Skymanga.co
Proof of ownership was provided in discord.

### PR DESCRIPTION
**Pull request by Riztard**
add and remove source

- add Atikrost Closes #5116 
- add RandomTranslations Closes #5123
- remove Skymanga Closes #5159
- add SpookyScanlations Closes #4319
- add StageComics Closes #5143

### CODE REVIEW

**Comment by P08Rahul** [comment]
Why remove skymanga

**Comment by AbdullahM0hamed** [comment]
@P08Rahul it was removed at the behest of the site owner(a)

**Comment by P08Rahul** [comment]
Can I get the previous version of madara extension?

**Comment by AbdullahM0hamed** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/commits/repo - if you cba to go through the history of the repo branch

**Comment by P08Rahul** [comment]
Thnx

**Pull request merged**
