### PR TITLE
Fix Webtoons & Tapas Author's Notes

### LINKED ISSUE #13279: Tapas & Webtoons: Chapters with Author's Notes fail to download
### Source information and language

Tapas 1.3.16, Webtoons.com 1.3.35

### Steps to reproduce

1. Enable author's notes in source settings
2. Go to any work with author's notes
3. Download a chapter that contains notes

### Expected behavior

The chapter is downloaded.

### Actual behavior

The download fails with HTTP error 500.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Tapas and Webtoons started having issues at the same time, so I don't _think_ it's a server-side problem.
It seems that chapters that were uploaded prior to August 25-26 are not affected, but I can't confirm.
Any chapters without author's notes download fine, including for works with affected chapters.
Reading the chapters is fine, but the note won't load.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by altaccosc**
The [`placehold.jp`](https://placehold.jp/en.html) API I was using before went under, so now I'm using a different one: [`fakeimg.pl`](https://fakeimg.pl).
I don't like this one as much, but it'll have to do. I tested soo many other APIs like this and this one was the best one out of all of those.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #13279

### CODE REVIEW

**Comment by altaccosc** [comment]
..and just now I saw that the [`placehold.jp`](https://placehold.jp/en.html) API owner fixed the original API...
https://twitter.com/placeholdjp/status/1565137872549621761
image

**Comment by altaccosc** [comment]
Thanks for the tip! I'll experiment with this in a bit.
I'll report back once I've decided if I'll use that method you propose, or if I'll stick to this online API.

**Comment by stevenyomi** [comment]
Post again: You can paint the image locally. Just put your text in a random URL like `http://note/#yourTextHere` and add an interceptor like this and adjust the constants:

(If you use this code snippet, use https://coauthoredby.netlify.app/ to credit me.)

```kotlin
object TextInterceptor : Interceptor {
    
    private const val HOST = "note"
    private const val TEXT_SIZE = 0f
    private const val TEXT_WIDTH = 0
    private const val PADDING = 0
    private const val PADDING_F = PADDING.toFloat()

    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val url = request.url
        if (url.host != HOST) return chain.proceed(request)

        val text = url.fragment

        val paint = TextPaint().apply {
            color = Color.BLACK
            textSize = TEXT_SIZE
            isAntiAlias = true
        }

        @Suppress("DEPRECATION")
        val layout = StaticLayout(text, paint, TEXT_WIDTH, Layout.Alignment.ALIGN_NORMAL, 1f, 0f, false)
        val height = layout.height + PADDING * 2

        val bitmap = Bitmap.createBitmap(TEXT_WIDTH + PADDING * 2, height, Bitmap.Config.ARGB_8888)
        bitmap.eraseColor(Color.WHITE)
        val canvas = Canvas(bitmap)

        canvas.save()
        canvas.translate(PADDING_F, PADDING_F)
        layout.draw(canvas)
        canvas.restore()

        val output = ByteArrayOutputStream()
        bitmap.compress(Bitmap.CompressFormat.PNG, 0, output)
        val body = output.toByteArray().toResponseBody("image/png".toMediaType())
        return Response.Builder().code(200).body(body).build()
    }
}
```

You might need to add more headers to the response.

Override the `client` field in the source and add it by `addInterceptor(TextInterceptor)`.

**Comment by altaccosc** [comment]
Status update!
I managed to indeed intercept the requests on the `note` requests, and after a long time of messing around with encoding bitmaps and canvases to streams and responses, I finally was able to get some custom generated images with text on them to display in Tachiyomi.
I'll continue trying to make it look nice soon. But for now I'm taking a break, because this continuous googling is getting pretty exhausting by now.

**Comment by altaccosc** [comment]
I'm trying to put the same thing into Webtoons now, but I'm struggling with where to put the new dependency that is
```gradle
dependencies {
    implementation "androidx.core:core-ktx:1.8.0"
}
```
I found out there's an `additional.gradle` file that these usually go in, but for Webtoons it seems like it works differently.
Can anyone point me in the right direction?

**Comment by alessandrojean** [comment]
The additional.gradle files goes into the overrides folder.

**Comment by altaccosc** [comment]
If I place it there and resync gradle, nothing happens..

**Comment by stevenyomi** [comment]
You need to run the generator again. But honestly KTX is not really needed in extension development; it's only a plus.

**Comment by altaccosc** [comment]
The KTX thing gives me access to a very useful function that I can use to draw the StaticLayout wherever I want onto the canvas.

**Comment by arkon** [comment]
We definitely don't want to start bringing in large Android support libraries into extensions.

**Comment by stevenyomi** [comment]
You can check the source code and just copy it.

**Comment by altaccosc** [comment]
But I see in your example that you did that offset thing another way.
I'll try that too if I can't get this to work.

**Comment by stevenyomi** [comment]
Yeah, I used `StaticLayout` to calculate the size of the text block and translated the `Canvas` to the top-left position of the text block before painting it.

**Comment by altaccosc** [comment]
Yup, I do stuff like that in my other projects all the time too
I'll just do that, then, I suppose

**Comment by altaccosc** [comment]
All done, now! :D
Thanks for the wait and the help from everyone! I really appreciate it! <3

**Pull request merged**
