### PR TITLE
Fix MangaJar page list parsing

### LINKED ISSUE #7390: [Expected URl scheme 'http' or 'https' but no colon was found] <mangajar (EN)>: <Can't open or download manga>
Device information
- Tachiyomi version: 0.11.1
- Android version: 10

Source information
- Name: MangaJar (EN)
- Extension version: 1.2.3

Steps to reproduce
1. Download Mangajar(EN)
2. Open any manga

Expected behavior
Open Normally the manga, but it shows in an error instead

Actual behavior
Can't download or read manga chapters

Other details
"Expected URL scheme 'http' or 'https' no colon was found"

### PR DESCRIPTION
**Pull request by somebody1234**
Changes the JSoup selectors
Closes #7390

### CODE REVIEW

**Comment by somebody1234** [comment]
will want to remove braces. not sure about prepending `abs:` to `src` and `data-src` though

**Comment by somebody1234** [comment]
wait, i broke it?

**Comment by CarlosEsco** [comment]
converted to draft until this i resolved

**Comment by somebody1234** [comment]
pretty sure i already did resolve it, will rebuild to confirm

**Comment by somebody1234** [comment]
yea, looks like it's working, of course feel free to confirm

**Pull request merged**
