### PR TITLE
Delete Comikey Extension

### PR DESCRIPTION
**Pull request by lord-ne**
Comikey extension hasn't worked for a while (about 8 months), due to changes made to the site. Specifically, they added Cloudflare protection, encryption, and scrambling images. I don't think the extension is realistically fixable, and it's been a while and no one else has fixed it either, so I'm opting to remove the extension.

Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9075

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by alessandrojean — APPROVED** [review]

**Comment by ObserverOfTime** [comment]
Wouldn't it be possible to use their API?

**Comment by lord-ne** [comment]
Yeah, several things actually are using the API, but even those parts don't work anymore due to the DRM encryption

**Comment by CarlosEsco** [comment]
Undecided on this.  Its not a cat and mouse game afaik.  Just hasnt worked in 8 months

**Comment by lord-ne** [comment]
I'll explain my reasoning for why I think this can't really be fixed:

Currently, there are two issues preventing the extension from working:

1. The API requests are protected by Cloudflare. Example: https://comikey.com/sapi/comics/37/read?format=json&content=EPI-nDq4Mk

2. The actual page listing the image urls is DRM protected. Example: Load the above URL, and click the link (relay-us.ebub.rocks/...) in the href attirbute of the response. You'll get an encrypted JSON document. Note that these relay-us.ebub.rocks links are the only way to access the URLs of the chapter images, as far as I'm aware.

(The third issue I mentioned earlier, images being scrambled, doesn't seem to be a things anymore, or at least not on most series)

The first issues if probably fixable. Maybe making the user open the url in webview and do the Cloudflare captcha once would allow future requests, or something like that, idk. But the second issue is my main concern. Breaking DRM inside a Tachiyomi extension seems incredibly difficult, maybe even not possible.

**Pull request merged**
