### PR TITLE
fix NPE and three img error

### PR DESCRIPTION
**Pull request by lingwunb666**
Relates pull request: #17502 

fix NPE in pageListParse()
fix three img error  Solution provided by @anenasa,thank you,very thank you,very very very thank you♥♥♥

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by lingwunb666** [comment]
> 您测试了这些更改吗？

yep

**Comment by lingwunb666** [comment]
I think I should explain my modifications. The current Release version cannot parse manga images. I modified the CSS selector to fix it, and due to some anti crawler mechanisms in Manwa, after reading nearly 10 chapters, it resulted in only 3 manga images. You need to manually enter Tachiyomi to set and reset the cookie. After research, no effective solution has been found, So I use counters and cookie jars to reset cookies. Although it's not perfect, at least there's no need to manually go into the settings to reset cookies. This is very useful when downloading. Previously, I used to pause and go to the settings to manually reset cookies after downloading chapters 5-6. My code was poorly written because I only know JAVA and don't know kotlin. This code helped me complete it after I informed ChatGPT3.5 about what I was going to do

**Comment by lingwunb666** [comment]
this fix work in my note20U
if has problems,try to tachyomo-setting-advanced-clear cookies

**Comment by stevenyomi** [comment]
cc @anenasa

**Comment by anenasa** [comment]
> anti crawler mechanisms in Manwa

I think I found the problem. If I send a GET request to https://manwa.me/static/images/pv.gif every time after page list request, issue no longer happens.
好像找到問題了，每次打開漫畫章節後再請求https://manwa.me/static/images/pv.gif，似乎就不會發生只有三張圖的問題了？請你測試確認看看

**Comment by lingwunb666** [comment]
> > anti crawler mechanisms in Manwa
> 
> I think I found the problem. If I send a GET request to https://manwa.me/static/images/pv.gif every time after page list request, issue no longer happens.
> 好像找到問題了，每次打開漫畫章節後再請求https://manwa.me/static/images/pv.gif，似乎就不會發生只有三張圖的問題了？請你測試確認看看

明天我试一下吧，今天有些事情，谢谢你

**Comment by lingwunb666** [comment]
> > anti crawler mechanisms in Manwa
> 
> I think I found the problem. If I send a GET request to https://manwa.me/static/images/pv.gif every time after page list request, issue no longer happens.
> 好像找到問題了，每次打開漫畫章節後再請求https://manwa.me/static/images/pv.gif，似乎就不會發生只有三張圖的問題了？請你測試確認看看

明天我试一下吧，今天有些事情，谢谢你
I'll try it tomorrow. I have something to do today. Thank you.

**Comment by lingwunb666** [comment]
> > anti crawler mechanisms in Manwa
> 
> I think I found the problem. If I send a GET request to https://manwa.me/static/images/pv.gif every time after page list request, issue no longer happens.
> 好像找到問題了，每次打開漫畫章節後再請求https://manwa.me/static/images/pv.gif，似乎就不會發生只有三張圖的問題了？請你測試確認看看

似乎不行，我在获取到章节图片后手动将pv.gif的链接插入index 0，依旧会出现三张图片的问题，只不过加上pv.gif变成了四张

It doesn’t seem to work. I manually inserted the link of pv.gif into index 0 after getting the chapter picture. There will still be three pictures, but it becomes four with pv.gif

**Comment by anenasa** [comment]
> 将pv.gif的链接插入index 0

這樣是沒用的，tachiyomi有快取機制，實際上只有第一次會請求pv.gif。以下是我的做法，你再試試：
```
    override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
        client.newCall(GET("$baseUrl/static/images/pv.gif")).execute()
        return super.fetchPageList(chapter)
    }
```

It does not work because pv.gif is cached by tachiyomi and is only fetched for the first time. Please test my code.

**Comment by alessandrojean** [comment]
You might want to use the `cache` attribute of the `GET` helper function to force it to always fetch from network instead of using the local cache though. Also might be worth wrapping it inside a `runCatching` in the case an Exception is thrown.

**Comment by lingwunb666** [comment]
> > 将pv.gif的链接插入索引 0
> 
> 这样是没用的，tachiyomi有快取机制，实际上只有第一次会请求pv.gif。以下是我的做法，你再尝试一下：
> 
> ```
>     override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
>         client.newCall(GET("$baseUrl/static/images/pv.gif")).execute()
>         return super.fetchPageList(chapter)
>     }
> ```
> 
> 它不起作用，因为 pv.gif 被 tachiyomi 缓存并且仅在第一次获取。请测试我的代码。

It successfully solved the problem,thank you very much,I love you ♥

**Pull request merged**
