### PR TITLE
Rename PMScans to RackUsReads

### LINKED ISSUE #13478: Source Request RackusReads
### Source name

RackusReads

### Source link

https://www.rackusreads.com/

### Language

English

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by happywillow0**
Option 1, Just update the baseURL. #13492 
Option 2, rename the source as well.

Closes #13478
Closes #12796

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Riztard** [comment]
maybe also remove pmscans

**Comment by happywillow0** [comment]
> maybe also remove pmscans #12796

Interesting. Should this stay as a new extension or be a update on the old ID?

**Comment by stevenyomi** [comment]
Probably just change the base URL of the old one.

**Comment by happywillow0** [comment]
Based on the website, the group is rebranded as RackUsReads. There is still one reference to pmscanlation with the paypal link. 
If I did this right, the name should change but the pkgName and ID should be the same.

**Comment by stevenyomi** [comment]
Yeah, but this will invalidate existing downloads and requires user to manually rename the folder. A better approach might be to rename it several days after the "auto rename folder" feature is released in the next stable patch.

**Comment by happywillow0** [comment]
Alright. That makes sense. Close in favor of #13492. No need for all the commit history.

**Comment by alessandrojean** [comment]
Closing in favour of #13492 as mentioned, but feel free to do this approach when the new feature hits stable.

**Pull request closed without merging**
