### PR TITLE
Add Extension

### LINKED ISSUE #15203: KomikSeru
### Source name

komikseru

### Source link

https://komikseru.me/

### Language

Indonesia

### Other details

NSFW/18+ = Yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15455: Katakomik
### Source name

Katakomik

### Source link

https://katakomik.online/

### Language

Indonesian

### Other details

18+/NSFW = no

katakomik

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15532: Komiksan
### Source name

KOMIKSAN

### Source link

https://komiksan.ml

### Language

Indonesia

### Other details

Theme : MangaThemesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #15547: MangaLivre.top
### Source name

MangaLivre.top

### Source link

https://mangalivre.top

### Language

Brazilian portuguese

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by MeLoseAgain**
Closes #15532 
Closes #15547 
Closes #15455 
Closes #15203

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by MeLoseAgain** [comment]
> Aside: Please edit your comment so that you use the ["Closes xyz" format](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)
> Example, like here: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/15785
> You can see it linking the issues correctly near the portion where it shows Assignees, Labels, Milestones, Development
> 
> otherwise, GitHub has a hard time linking the pull request to those issues
> It also won't automagically close the issues when the PR gets merged

Thanks, I'm new here so I don't really understand

**Comment by alessandrojean** [comment]
You didn't mark the Manga Livre extension as non official and neither used another package name, now it's showing as an update to an obsolete extension with the same name. I will fix this.

**Comment by MeLoseAgain** [comment]
> You didn't mark the Manga Livre extension as non official and neither used another package name, now it's showing as an update to an obsolete extension with the same name. I will fix this, but please be careful with this in the future.

Ok, thanks for the feedback, I'll check it again, I didn't realize that the extension already existed

**Comment by MeLoseAgain** [comment]
> Usually looking at the removed_sources.md file helps in these situations.
I want to ask, there is a web of my friend who is on tachiyomi if I delete it, what kind of procedure should I do? or I have to provide documents about the ownership of the site

**Comment by alessandrojean** [comment]
We only accept removal requests from scanlator sources that host their content only (i.e. it can't contain any content from other groups or be an aggregator website). If the site fits these requirements the person can ask for removal in our [Discord server](https://discord.gg/tachiyomi) and provide any proof of ownership such as an administration panel screenshot or the domain management ownership panel as well.

**Comment by MeLoseAgain** [comment]
> We only accept removal requests from scanlator sources that host their content only (i.e. it can't contain any content from other groups or be an aggregator website -- and we will double check this claim). If the site fits these requirements the person can ask for removal in our [Discord server](https://discord.gg/tachiyomi) and provide any proof of ownership such as an administration panel screenshot or the domain management ownership panel as well to any member of Staff there.

It's like my friend's web doesn't meet those requirements

**Pull request merged**
