### PR TITLE
Update url

### PR DESCRIPTION
**Pull request by matheuswr89**

### CODE REVIEW

**Comment by CarlosEsco** [comment]
@alessandrojean do you want to just make this configurable?

**Comment by matheuswr89** [comment]
I think this would be a good thing for this extension, as it uses the domain of another one, that is, if it breaks there, the same happens here.

**Comment by alessandrojean** [comment]
@CarlosEsco sure. I can update the hentai website URL to the new one and add the preference in a new PR, so users will not need to update the extension twice.

> if it breaks there, the same happens here.

Extensions can't read settings from each other, though.

**Comment by matheuswr89** [comment]
> Extensions can't read settings from each other, though.
I know, I mean when you change Neox URL

**Comment by jobobby04** [comment]
> 
> 
> @CarlosEsco sure. I can update the hentai website URL to the new one and add the preference in a new PR, so users will not need to update the extension twice.
> 
> > if it breaks there, the same happens here.
> 
> Extensions can't read settings from each other, though.

They can if you setup the shared preferences correctly, just use the same id for the key

**Comment by alessandrojean** [comment]
> They can if you setup the shared preferences correctly, just use the same id for the key

Probably would be confusing for the users to setup the URL though, and when Neox changed the URL of the main website, it took some days for them to update the hentai one, so users in this period would not be able to use the extension if they changed the URL in the main preference.

I will just let them separate because it will be more easy for the users.

**Comment by matheuswr89** [comment]
@alessandrojean can I close this PR?

**Pull request closed without merging**
