### PR TITLE
[RU]NudeMoon webview mobile site

### PR DESCRIPTION
**Pull request by abubaca4**
Force mobile site version in webview by set cookie
Maybe someone know better place to insert cookie change code(it need be called one time on start)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Tried to use the `init` block?

**Comment by abubaca4** [comment]
> Tried to use the `init` block?

This extension is my first kotlin kode(I know c++ and python so I look in other extensions code and do something similar)
By google is it should look like
```
class Nudemoon : ParsedHttpSource() {
...
private val cookieManager by lazy { CookieManager.getInstance() }
init {
cookieManager.setCookie(baseUrl, "nm_mobile=1; Domain=" + baseUrl.split("//")[1])
}
...
```
?

**Comment by abubaca4** [comment]
Look like it works

**Comment by abubaca4** [comment]
I think it's ready for merge
Debug version work as expected

**Pull request merged**
