### PR TITLE
Added Cloudflare client to Lanraragi

### PR DESCRIPTION
**Pull request by jferdous70**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
> Updated `extVersionCode` value in build.gradle for individual extensions

Bump the `extVersionCode`.

**Comment by arkon** [comment]
Did you test this?

**Comment by jferdous70** [comment]
I don't have an example of non-protected server to test, if anybody has a URL i could check

**Comment by alessandrojean** [comment]
Cloudflare client only do something if it detects that the `Server` header is `Cloudflare` and the website returned `403` and some other codes, so it should be fine, I guess?

**Comment by jopejoe1** [comment]
You could always test with the demo server at `https://lrr.tvc-16.science` pretty sure that doesn't have Cloudflare.

**Comment by jferdous70** [comment]
I tested both https://lrr.tvc-16.science and the cloudflare website, both work perfectly fine

**Pull request merged**
