### PR TITLE
AllAnime refactor

### LINKED ISSUE #16402: Allanime: Add option of "low Image quality" servers in setting
### Source name

Allanime

### Source language

English

### Describe your suggested feature

there is a setting on the website where you can change the image quality so it would be great if there is a feature in this extension also.. like: Wp-480 and Wp-800

Eg: (Mashle: Magic and Muscle) manga pics--
https://wp.youtube-anime.com/aln.youtube-anime.com/images133/22Sc8Cm2wmwCEkrzx/157/sub/1.css?w=480 (480x701) : 73.69 KB

https://wp.youtube-anime.com/aln.youtube-anime.com/images133/22Sc8Cm2wmwCEkrzx/157/sub/1.css?w=800 (784x1145) 225.69KB

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #16652: Allanime: Wrong Chapter time stamp
### Source information

Allanime 1.4.2

### Source language

English

### Steps to reproduce

1. Goto any manga on allanime extension.
2. Only "Today" is showing on chapter release date.

### Expected behavior

Screenshot_20230601-202249_Kiwi Browser

### Actual behavior

Screenshot_20230601-202149_TachiyomiSY

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
* code cleanup
* chapter titles\dates
* image quality setting

closes #16652
closes #16402

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Berserk0001** [comment]
Waiting eagerly....

**Comment by AntsyLich** [comment]
No it's abandoned cause you won't stop whining

**Comment by Berserk0001** [comment]
> No it's abandoned cause you won't stop whining

Please do not say mean things...

**Comment by Berserk0001** [comment]
I know the Dev who is building this is busy on another work so it may take some time but that does't mean I am whining..So,
Please mind your tongue..

**Pull request merged**
