### PR TITLE
Change mangadex api url

### PR DESCRIPTION
**Pull request by az4521**
i havent even tested this, they were just making fun of us in the mangadex discord for using the wrong url

### CODE REVIEW

**Comment by arkon** [comment]
Sorry if this wasn't a shitpost and MD actually has a plan.

**Comment by az4521** [comment]
it was a shitpost that wouldve actually fixed the extension

**Comment by arkon** [comment]
"Fix" is sort of a stretch if their main webserver(s) die again from the load. Did they actually say something about it?

**Comment by az4521** [comment]
nah this is on the level of the shared-account fix for searching

**Pull request closed without merging**
