### PR TITLE
[RU]Multi Lib (MangaLib and HentaiLib)

### PR DESCRIPTION
**Pull request by e-shl**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names (*partially, doesn't seem to affect)
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by e-shl** [comment]
How to make  work filters from the overrides? Filters are replaced / built into the list, but requests from them do not go.

**Comment by e-shl** [comment]
If that this all, what kind of error I don't know, my apk is building.

**Comment by alessandrojean** [comment]
It seems to be missing a `)` somewhere.

https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12030/checks

**Comment by e-shl** [comment]
> merge LibUrlActivity (fix crash)

didn’t help, it turned out that all multi-sources are broken

**Pull request closed without merging**
