### PR TITLE
New extension GMANGA

### LINKED ISSUE #117: [Arabic] gmanga.me
(CATALOGUE) SOURCE REQUESTS:
Please Add Arabic Managa Site 
http://gmanga.me/

### PR DESCRIPTION
**Pull request by clarencecastillo**
## Adds new source:
https://gmanga.me/

## Implemented Features:
- Latest: fetches from https://gmanga.me/mangas/latest
- Popular: fetches from https://gmanga.me/mangas which also acts as unfiltered search
- Pages, Chapters: fetches and decrypts actual content
- Search: allow searching via text query
- Filters: allow filtering of search results as per https://gmanga.me/mangas
- Preferences: option to show all scans or only most viewed scan, refresh manga to show change

## TODO:
- ~~Filters & Sort: allow filtering of search results as per filters available here https://gmanga.me/mangas~~
- ~~Rate limiting~~
- ~~Translate preferences and validation error messages at filters~~

## Important Stuff
I don't speak Arabic so will need some help or consensus with the following:

1. ~~Need some help with getting the exact wording right for the filters & sort feature. Would be good if you could provide a mock-up based on existing extensions, including how you want it to look and work.~~ The filters were actually pretty straightforward to replicate though I can't verify if there's typos so please review if you can.
2. ~~Haven't used and/or worked on a source that provides multiple scans of the same chapter before. To avoid duplicate listing of the same chapter, I've picked the scan with the most number of views. Let me know how you'd like to handle this (or if there's already a standard way to do so).~~ Will be exposing an option in preferences to choose between picking most viewed scan or just show all scans.
3. ~~Though most (if not all) titles are written in English, I can see that some have alternate titles in Arabic. Should I let that take priority over the default English title?~~ Apparently Arabic title is only available at Manga details page and not at search results. Will keep this option out first until the official app supports updating of `SManga.title`  field.

## APK Previews
[b1ec432](https://github.com/clarencecastillo/tachiyomi-extensions/releases/tag/v1.2.1-4-b1ec432)
~~[05ca52e](https://github.com/clarencecastillo/tachiyomi-extensions/releases/tag/ar.gmanga-v1.2.1-3-05ca52e)~~
~~[552fa72](https://github.com/clarencecastillo/tachiyomi-extensions/releases/tag/ar.gmanga-v1.2.1-2-552fa72)~~
~~[37642f7](https://github.com/clarencecastillo/tachiyomi-extensions/releases/tag/ar.gmanga-v1.2.1-1-37642f7)~~

Thanks to @as280093 for preparing the icons

Closes #117

### CODE REVIEW

**Comment by yshalsager** [comment]
Thanks for your great work.
I'm an Arabic speaker and can help with translating and any other needed stuff.

2. Personally, I think listing all is good, since some translations are better than others.

3. If both can be shown, why not? I think Arabic title should have the priority.

**Comment by CarlosEsco** [comment]
i agree with what you mentioned i would add a heavy rate limiter, you can see an rate limiting example in the mangadex extension.  I also would probably change the user agent to something that is a generic desktop.  There is probably another extension with an example of that

**Comment by clarencecastillo** [comment]
@yshalsager Regarding 2 and 3, I think the best way would be to expose them in the source preferences so that the user can change accordingly. There will be two list items there namely:

`Chapter Listing`
- `Pick most viewed scan`^
- `Show all scans`

`Manga Title`
- `Use Arabic when available`^^
- `Use original`
- `Use Arabic followed by original`^^^

^ setting this as default to avoid confusion when reading the manga in reader mode (continuous chapters)
^^ setting this as default as per recommendation
^^^ it will follow the format `<arabic_title> | <original_title>`

Would be great if you could provide translations for those texts, including the following error messages:

`Invalid start date`
`Invalid end date`
`Invalid min chapter count`
`Invalid max chapter count`

**Comment by yshalsager** [comment]
> 
> 
> @yshalsager Regarding 2 ~and 3~, I think the best way would be to expose them in the source preferences so that the user can change accordingly. There will be ~two~ one list item there namely:
> 
> `Chapter Listing`
> 
>     * `Pick most viewed scan`^
> 
>     * `Show all scans`
> 
> 
> ~`Manga Title`~
> ~- `Use Arabic when available`~
> ~- `Use original`~
> ~- `Use Arabic followed by original`~
> 
> ^ setting this as default to avoid confusion when reading the manga in reader mode (continuous chapters)
> 
> Edit: seems Arabic title is only available at the manga details page and not at the list of mangas page such as search or latest. Dropping this feature for now till the official app supports updating of titles.
> 
> Would be great if you could provide translations for those texts and also for the following error messages when providing invalid filter values:
> 
> `Invalid start date`
> `Invalid end date`
> `Invalid min chapter count`
> `Invalid max chapter count`

Yeah, the preferences option would be the best.

Here is the translation of the errors:

`Invalid start date`: تاريخ بداية غير صالح
`Invalid end date`:  تاريخ نهاية غير صالح
`Invalid min chapter count`: الحد الأدنى لعدد الفصول غير صالح
`Invalid max chapter count`: الحد الأقصى لعدد الفصول غير صالح

**Comment by CarlosEsco** [comment]
@clarencecastillo  @ me when you are done and i can review

**Comment by clarencecastillo** [comment]
@yshalsager Thanks, will also need translations for:


`Chapter Listing`
> `Pick most viewed scan`
> `Show all scans`

**Comment by yshalsager** [comment]
@clarencecastillo

Chapter Listing كيفية عرض الفصل بقائمة الفصول
Pick most viewed scan اختيار النسخة الأكثر مشاهدة
Show all scans عرض جميع النسخ

**Comment by clarencecastillo** [comment]
@CarlosEsco We're good to go, please review.

**Comment by motsouzumaki** [comment]
thanls to everyone who developed this resource,that made me very happy.

If you'll excuse me, I have some suggestions or problems.

1-Search for any manga that fails if I don't adjust anything option in the filters.

2- Is there no option to merge the scans such as volumes?

**Comment by clarencecastillo** [comment]
@motsouzumaki Please create new and separate issues for those items and provide specific steps and sample URLs

**Pull request merged**
