### PR TITLE
Change mangapro to manga1001 and fix cover image

### LINKED ISSUE #11303: MangaRaw: Showing placeholder covers
### Source information

MangaRaw 1.2.5

### Steps to reproduce

1. Browse -> Comick or MangaPro.
2. Go to Latest or Browse.

### Expected behavior

Cover images show correctly.

### Actual behavior

 All cover images not showing.
FKI5OTE `W2DGA{WU1QKA(R

### Tachiyomi version

TachiyomiSY Stable 1.8.1

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KoSChicken**
mangapro.top and manga1001.top are same site and mangapro.top always redirect to manga1001.top.
Close #11303 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Riztard** [comment]
might as well change it to multisrc factory if possible

**Comment by KoSChicken** [comment]
> 

I'm unfamiliar with multisrc factory, I'll do some research.

**Comment by KoSChicken** [comment]
change to multisrc, delete old individual code.

**Comment by KoSChicken** [comment]
Add comick, manga1001, mangapro and syosetu.
manga1001 and mangapro have a latest manga page but all these manga redirect to syosetu.top. I don't know how to deal with the url of SManga. So for now, even manga1001 and mangapro have latest update, this function will not work. Anyone knows how to fix this issue?

**Comment by Riztard** [comment]
> Still working on some issues, please do not merge this pr.

you can change this pr to draft if not ready yet, so it doesnt get merged

**Comment by KoSChicken** [comment]
Ready for merge.
- Change MangaRaw to multisrc. Now support comick.top, manga1001.top, mangapro.top and syosetu.top
- Close #11303, but maybe some covers still not showing.
- 'Latest' not implemented


Screenshot_2022-04-07-10-19-42-902_eu kanade tach
Screenshot_2022-04-07-10-20-06-707_eu kanade tach
Screenshot_2022-04-07-10-20-26-243_eu kanade tach
Screenshot_2022-04-07-10-21-00-325_eu kanade tach
.

**Pull request merged**
