### PR TITLE
Migrate ReaperScans from Genkan to Madara

### PR DESCRIPTION
**Pull request by LeMyst**
Version change from v1.2.1 to v1.2.7

### CODE REVIEW

**Comment by LeMyst** [comment]
Migration seem to be mandatory (URL clearly change)
exemple:
https://reaperscans.com/comics/312770-nano-machine
to
https://reaperscans.com/series/nano-machine/

**Comment by alessandrojean** [comment]
Closes #8082.

**Comment by LeMyst** [comment]
Issues with some titles, investigating

**Comment by alessandrojean** [comment]
You possibly can filter the novels by overriding the selector.

```kotlin
override fun popularMangaSelector() = "div.page-item-detail.manga"
```

**Comment by LeMyst** [comment]
> You possibly can filter the novels by overriding the selector.
> 
> ```kotlin
> override fun popularMangaSelector() = "div.page-item-detail.manga"
> ```

Thank you, figured by myself but he took me some time to understand how overrides works.

**Comment by LeMyst** [comment]
Like E3FxGaming said on Discord, it seem possible to write old URL to new one:

> If you cut the 312770- out of the first link you'll get a link that'll 301 Moved Permanently redirect you to the second link.

**Comment by LeMyst** [comment]
web novel are shown in search

**Comment by alessandrojean** [comment]
Madara don't provide a way to really filter then at search, so nothing much that can be done.

**Comment by CarlosEsco** [comment]
Needs override code right?

**Comment by LeMyst** [comment]
> Needs override code right?

I don't understand your question, but yes, there is some code override in the PR.

**Comment by alessandrojean** [comment]
Why you merged master into your branch?

> I don't understand your question, but yes, there is some code override in the PR.

He is referring to the `versionId`.

```kotlin
/**
 * Version id used to generate the source id. If the site completely changes and urls are
 * incompatible, you may increase this value and it'll be considered as a new source.
 */
open val versionId = 1
```

Just put it as below:

```kotlin
override val versionId = 2
```

**Comment by LeMyst** [comment]
> Why you merged master into your branch?
> 

It was to solve the conflict from #8080

**Comment by alessandrojean** [comment]
I didn't have seen the merge commit didn't change anything, my bad.

**Pull request merged**
