### PR TITLE
Madara split: part 1

### PR DESCRIPTION
**Pull request by AriaMoradi**
This covers about 50 of madara sources, can be merged now.

I'll do more of it when I have time.

### CODE REVIEW

**Comment by arkon** [comment]
Can you remove the stuff from the Madara source rather than commenting them out?

**Comment by AriaMoradi** [comment]
I need the list for cross referencing, but i can remove the class implementations

**Comment by Soitora** [comment]
How would one know their source in Madara has been off-sourced when the extension itself isn't gone?

**Comment by AriaMoradi** [comment]
> How would one know their source in Madara has been off-sourced when the extension itself isn't gone?

migration tab shows id instead of name

**Comment by AriaMoradi** [comment]
removed moved classes.

**Comment by arkon** [comment]
You might want to try splitting the other smaller ones first and doing Madara last.

**Comment by arkon** [comment]
Read #5672.

**Pull request merged**
