### PR TITLE
HentaiChan URL Update 

### PR DESCRIPTION
**Pull request by lurure**
Checklist:

- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed

### CODE REVIEW

**Comment by CarlosEsco** [comment]
you need to update the override version code

**Comment by alessandrojean** [comment]
> Have tested the modifications by compiling and running the extension through Android Studio

Please do test your code.

**Comment by lurure** [comment]
> you need to update the override version code

updated

**Comment by alessandrojean** [comment]
Still missing tests.

**Comment by e-shl** [comment]
Use settings. if you found a working domain for VPN.

**Comment by NickOwennss** [comment]
At the moment this is the working domain of the site: https://xxxxx.hentaichan.live/

**Comment by alessandrojean** [comment]
Closing as it seems to be stale.

**Pull request closed without merging**
