### PR TITLE
Add MangaReader extension

### LINKED ISSUE #9112: MangaReader
### Source name

MangaReader

### Source link

https://mangareader.to/home

### Language

English

### Other details

Doesn't seem to use WordPress at all
Doesn't seem to be a mirror of the other mangareader sites
~~There doesn't seem to be a dedicated Latest updates page or a typical "browse" page, but there is a A-Z page~~ lol there is I just didn't look hard enough

They scramble the pages they serve
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ObserverOfTime**
The images are scrambled and I don't know how to unscramble them.
I'd appreciate some help with that if possible.

---

Closes #9112

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by CVIUS** [comment]
Can you add quality preference?

**Comment by alessandrojean** [comment]
> I'd appreciate some help with that if possible.

In the extension side, you can take a look at how [Viz](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/vizshonenjump/src/eu/kanade/tachiyomi/extension/en/vizshonenjump/VizImageInterceptor.kt) extension does it. Usually the unscramble is done by a interceptor that recreates the image.

To get the algorithm to unscramble you will need to inspect the JavaScript code of the page probably.

**Comment by ObserverOfTime** [comment]
Yeah, making sense of their [heavily obfuscated code](https://mangareader.to/js/read.min.js) is the part I'm currently having trouble with…

**Comment by alessandrojean** [comment]
Oof, that will be a lot of work.

It isn't the ideal, but you can use the screenshot interceptor from Japscan extension too.

**Comment by ObserverOfTime** [comment]
I'll come back to this PR at a later time. If someone more experienced can figure out the unscrambling algorithm by then, that'll be great. If not, I'll see what I can do.

**Comment by tanuukii** [comment]
I don't know if this is relevant but I'll leave this here
https://github.com/saikou-app/saikou/pull/44/commits/6cd13d7be9122a3b9c73a5c493602da2bc13b3ff
https://github.com/saikou-app/saikou/pull/45/commits/00243ceb9f2ae6b6dadf2c2fe8883c747fae5328
https://github.com/saikou-app/saikou/pull/47/commits/cb7536fd2418851f8aa94ba76488f319d58711fc

**Comment by ObserverOfTime** [comment]
Too bad that's GPL-licensed so I can't legally yoink the code…

**Comment by FourTOne5** [comment]
@ObserverOfTime can't we just save a version of the `read.min.js` in some place and use quickjs to get the image base64?

**Comment by ObserverOfTime** [comment]
Does it support HTML canvas?

**Comment by FourTOne5** [comment]
it should work iirc

**Comment by ObserverOfTime** [comment]
Nope, QuickJS isn't working.

**Comment by KraXen72** [comment]
@ObserverOfTime paperback has a working mangareader.to extension that is opensource, you might wanna take a look:
https://github.com/saikou-app/saikou/blob/main/app/src/main/java/ani/saikou/manga/source/parsers/MangaReaderTo.kt

**Comment by vetleledaal** [comment]
I figured out the encryption used on the site, feel free to use something like this in an interceptor or w/e:

```kt
import kotlin.math.ceil
import kotlin.math.pow

class Arc4Shuffler(seed: String) {
    // Based on davidbau/seedrandom (MIT license) Copyright 2019 David Bau
    // Based on webcaetano/shuffle-seed (MIT license) Copyright 2016 Andre Caetano

    private val s = (0 until width).toMutableList()
    private var i = 0
    private var j = 0

    init {
        val key = seed.map { it.code }.ifEmpty { listOf(0) }
        var j = 0
        for (i in 0 until width) {
            val t = s[i]
            j = mask and (j + key[i % key.size] + t)
            s[i] = s[j]
            s[j] = t
        }
        g(width)
    }

    private fun g(count: Int): Double {
        var r = 0.0

        repeat(count) {
            i = mask and (i + 1)
            val t = s[i]
            j = mask and (j + t)
            s[i] = s[j]
            s[j] = t
            r = r * width + s[mask and (s[i] + s[j])]
        }

        return r
    }

    private fun prng(): Double {
        // This function returns a random double in [0, 1) that contains
        // randomness in every bit of the mantissa of the IEEE 754 value.

        var n: Double = g(chunks)
        var d: Double = startdenom
        var x = 0

        while (n < significance) {
            n = (n + x) * width
            d *= width
            x = g(1).toInt()
        }

        while (n >= overflow) {
            n /= 2
            d /= 2
            x = x ushr 1
        }

        return (n + x) / d
    }

    fun unshuffle(list: List<Int>): List<Int> {
        val resp = list.indices.toMutableList()
        val keys = list.toMutableList()

        for (element in list) {
            val r = (prng() * keys.size).toInt()
            val g = keys[r]
            keys.removeAt(r)
            resp[g] = element
        }
        return resp
    }

    companion object {
        private const val width = 256
        private const val chunks = 6
        private const val digits = 52
        private val startdenom = width.toDouble().pow(chunks)
        private val significance = 2.toDouble().pow(digits)
        private val overflow = significance * 2
        private const val mask = width - 1
    }
}

data class Point2D(
    val x: Int,
    val y: Int,
)

data class Dim2D(
    val w: Int,
    val h: Int,
)

fun draw(sx: Int, sy: Int, sWidth: Int, sHeight: Int, dx: Int, dy: Int, dWidth: Int,
 dHeight: Int) {
    assert(sWidth == dWidth)
    assert(sHeight == dHeight)
    println("$sx,$sy,$sWidth,$sHeight,$dx,$dy")
}

fun main() {
    // Static
    val pieceSize = 200

    // Dynamic
    val width = 760
    val height = 1201

    /*
     * Pieces are put into up to 4 groups
     * 1. whole pieces, 200x200
     * 2. partial width pieces, ex. 14x200
     * 3. partial height pieces, ex. 200x56
     * 4. leftover piece, ex. 152x188
     */
    val pieceCountX = ceil(width / pieceSize.toDouble()).toInt()
    val pieceCountY = ceil(height / pieceSize.toDouble()).toInt()
    val groups = mutableMapOf<Dim2D, MutableList<Point2D>>()

    for (i in 0 until (pieceCountX * pieceCountY)) {
        val x = (i % pieceCountX) * pieceSize
        val y = (i / pieceCountX) * pieceSize

        val dimGroup = Dim2D(
            w = minOf(pieceSize, width - x),
            h = minOf(pieceSize, height - y),
        )
        groups.putIfAbsent(dimGroup, mutableListOf())
        groups[dimGroup]!!.add(Point2D(x, y))
    }

    groups.forEach { (group, pieces) ->
        val shuffler = Arc4Shuffler("stay")
        val shuffled = shuffler.unshuffle(pieces.indices.toList())

        val cols = pieces.count { it.y == pieces[0].y } // TODO: (nit) stop when iterating over a different y value
        val offsetX = pieces[0].x
        val offsetY = pieces[0].y

        pieces.forEachIndexed { index, piece ->
            val i = shuffled[index]
            val row = i / cols
            val x = (i - row * cols) * group.w
            val y = row * group.h

            draw(offsetX + x, offsetY + y, group.w, group.h, piece.x, piece.y, group.w, group.h)
        }
    }
}
```

**Comment by alessandrojean** [comment]
Superseeded by #11811.

**Pull request closed without merging**
