### PR TITLE
MangaPark v3: Rewrite

### LINKED ISSUE #7963: MangaPark v3: Failed to load pages
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3521

### Android version

Android 12

### Source information

Mangapark v3 1.2.7

### Steps to reproduce

Open Chainsaw Man Chapter 7 (title url https://mangapark.net/comic/74763/chainsaw-man)

### Expected behavior

Chapter images load

### Actual behavior

Chapter doesn't load, shows following error 
Screenshot_20210703-215318_Tachiyomi

### Other details

Not sure if this affects other titles/chapters, haven't found anything in the, admittedly small, titles i sampled

### LINKED ISSUE #9129: MangaparkV3: Chapters not showing
### Source information

"MangaParkV3 1.2.9"

### Steps to reproduce

1. Open a manga in app
2. Reload for new chapter update

### Expected behavior

"The manga updates new chapters"

### Actual behavior

"For input string:..."
Screenshot_20210919-122114_Tachiyomi

### Tachiyomi version

0.12.2

### Android version

Android 11

### Other details

Webview works normally

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by FourTOne5**
Rewrite the garbage I wrote previously + Migrate to MPv3.3 (The site changed code twice while I was doing this! Please don't break again.)

Fixes #9129
Fixes #7963

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Annotated `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- [X] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `versionId` if a source's name or language were changed

### CODE REVIEW

**Comment by FourTOne5** [comment]
@CarlosEsco PR is ready to merge.

**Comment by vncrack** [comment]
Is this normal?
Screenshot_20210926-225250_Tachiyomi

**Comment by FourTOne5** [comment]
> Is this normal?
> New update btw
> Screenshot_20210926-225250_Tachiyomi

Umm what? I swear it was working.

**Comment by vncrack** [comment]
> > Is this normal?
> > New update btw
> > Screenshot_20210926-225250_Tachiyomi
> 
> Umm what? I swear it was working.

This is what happens when you select old chapter btw
Screenshot_20210926-234834_Tachiyomi

**Comment by FourTOne5** [comment]
> > > Is this normal?
> > > New update btw
> > > Screenshot_20210926-225250_Tachiyomi
> > 
> > 
> > Umm what? I swear it was working.
> 
> This is what happens when you select old chapter btw
> Screenshot_20210926-234834_Tachiyomi

That's because url was changed and it doesn't exist now.
Previously - /comic/1/test/1
Now - /comic/1/test/c1-en

**Pull request merged**
