### PR TITLE
Update URL mangaku.pw

### PR DESCRIPTION
**Pull request by muhammadzikrullah**

### CODE REVIEW

**Comment by Riztard** [comment]
yakin cuma butuh update url trus bisa?

**Comment by CarlosEsco** [comment]
@Riztard is this good to go?

**Comment by Riztard** [comment]
he need to update gradle and i think there is more issue other than this afaik

**Comment by FallenX2** [comment]
SekaiKomik & mangasusu di fix juga dong bro

**Comment by arkon** [comment]
Closing due to inactivity. Someone else can create another PR if desired.

**Pull request closed without merging**
