### PR TITLE
Hide non-manga entries in search on Madara sources

### LINKED ISSUE #8396: Hentairead won't show genres even after pressing reset
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.0

### Source information

Hentairead 1.2.9

### Steps to reproduce

1.Open Source
2.Press the filter button
3. and press reset button

### Expected behavior

show genres list that was previously hidden

### Actual behavior

only show press reset to attempt to fetch genres warning no matter how many times i press reset button

### Other details

_No response_

### LINKED ISSUE #11142: Madara: Deep linking broken
### Source information

Any Madara based Extension

### Steps to reproduce

1. Open Link from Madara based site in app
2. Wait

### Expected behavior

The manga associated with that url opens

### Actual behavior

It loads and never stops loading

### Tachiyomi version

r4197

### Android version

Android 10

### Other details

Is working in TachiyomiSY but fails in all other versions and forks of Tachiyomi

Partially Supersedes #10591

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #11251: Hiperdex genre list
### Describe your suggested feature

Remove the fetching data on the genres section of the filter replacing it with fixed genres list writing it directly in the extension (like a previous version of the extension). i am asking for it because every time i open hiperdex i have to scroll down, fetch the genres clicking on the button "press reset to attempt to fetch genres" and then the reset button. previously the genre list was fixed and i didn't have to do all this cranky stuff becuse the genre list was always there, fixed and without the need to fetch, worsening the QoL in the use of the extension. can you restore it?

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by alessandrojean**
Make Madara sources filters the non-manga entries by using a post meta filter in `madara_load_more` action.

The search request was totally rewritten to follow the [WP_Query](https://developer.wordpress.org/reference/classes/wp_query/) structure, and the taxonomies and meta keys were consulted directly in the `madara-core` source code I downloaded from the internet.

Using this action on search allows even more customization of the filters, enabling things they don't have yet in their theme frontend, like changing the sort direction or even adding support for exclusion in the genres filter.

The `.manga` class selector added to the popular and latest was also removed in favour of the meta filter.

Sources that incorrectly marks the entries' chapter type or have incompatibilities can be rollback like the last similar PR (by setting `fetchGenresOnInit = false` and/or `useLoadMoreSearch = false`, as explained below).

This PR also fixes the behavior of dynamic genres filter, by fetching it on `init`, fixing the bug where the filters view should be reinflated by manually pressing the `Reset` button to show the genres. The algorithm is the same used in Komga.

A new `Show only manga entries` filter is also added to the filter list if `useLoadMoreSearch = true`. It can be useful if the source incorrectly marks the entry as novel or video and the users wants to add it to their library.

New control variables added to the base `Madara` class:

- `filterNonMangaItems` (defaults to `true`): Controls if the source should send the chapter type filter.
- `fetchGenresOnInit` (defaults to `true`, constructor): Controls if the source should fetch the genre list on `init`.
- `useLoadMoreSearch` (defaults to `true`): Controls if the source should use the new search request.

Initially marking it as draft because build errors may occur, and it will probably need a rebase after #11298 gets merged.

Closes #8396.
Closes #11142.
Closes #11251.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by FourTOne5** [comment]
```diff
- override fun popularMangaNextPageSelector(): String? = "body:not(:has(.no-posts))"
+ override fun popularMangaNextPageSelector(): String? = "div:not(:has(.no-posts))"
```
Also change this cause in the actual response there is no body it's added by jsoup.

**Comment by alessandrojean** [comment]
Sure, I just don't know how it worked before, since the popular request URL wasn't changed.

**Comment by alessandrojean** [comment]
@FourTOne5 I just tested, and it's working as expected, no need to change the selector.

**Comment by FourTOne5** [comment]
> @FourTOne5 I just tested, and it's working as expected, no need to change the selector.

Yeah i know it's gonna work since Jsoup wraps the html with body if it's not present

**Comment by alessandrojean** [comment]
Should be okay to merge now. If any user reports future issues regarding individual sources, they can be rollback from the update individually like the last time.

**Pull request merged**
