### PR TITLE
Fix chapters and other updates for Mangadex

### LINKED ISSUE #8036: Mangadex: manga not showing name
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Stable 0.11.1

### Android version

Android 11

### Source information

Mangadex 1.2.122

### Steps to reproduce

1. Open Mangadex source (not latest)
2. Some manga don't display the title but only the cover even though they have a tittle like other manga when you open them in webview

### Expected behavior

1. Open Mangadex source (not latest)
2. Manga display as they should be with titles and all the informations

### Actual behavior

[Mangadex title URL brought as example](https://mangadex.org/title/8fef2dc5-fd32-4d62-9cb3-4a39275e0ef5) 
Screenshot_20210709-232919_Tachiyomi
Screenshot_20210709-231742_Tachiyomi

### Other details

I cleared cache/cookies of both tachiyomi and webview if that helps with anything.

### LINKED ISSUE #8872: Mangadex : Alternative Name
### Describe your suggested feature

image
Please add this feature to this extension. Thank you for the hard work 

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #8928: NSFW missing
### Source information

Mangadex 1.2.130

### Steps to reproduce

NSFW +18 doesn't show up, it doesn't show up in searches too, mangadex, all nsfw option all turned on, in tachiyomi settings and extension settings, it doesn't show up

### Expected behavior

NSFW +18 to show up mangadex searches and in general

### Actual behavior

NSFW +18 not showing up

### Tachiyomi version

0.12.1

### Android version

Android 10

### Other details

If this report is already up and issuing a fix pls close this thread

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Arraiment**
Closes #8928 
As for the updated icon, I couldn't find one with a high enough res so I'll leave that up to someone else.
Closes #8872 
Closes #8036, now ext will show titles based on preferred lang->en->first available title, any title is better than no title.
Also changed latest updates since api now supports sorting by update date.

### CODE REVIEW

**Comment by FourTOne5** [comment]
Btw can you also add the new sorts to search and change latest to latest uploaded sort

**Comment by Arraiment** [comment]
> pornographic manga in libary will not get any update if pornographic is set to off

My idea was that users who don't want pornographic content will never see any 18+ stuff while the preference is off but if the preference is mostly for initial sorting I can revert it and change the preference description to be more explicit.

> Btw can you also add the new sorts to search and change latest to latest uploaded sort.

Didn't notice that lol, I'll change the filters to mimic their website.

**Comment by CarlosEsco** [comment]
Other issue, I'm not merging that latest change 

Sorting by latest chapter on manga list doesn't take into account the current users language (not available in api). So if some group uploads a bunch chapter in Spanish for manga 1 and you are browsing the English dex extension you are seeing the manga 1 near the top even though no English chapters were uploaded

**Comment by CarlosEsco** [comment]
Changes you are making for the content rating for default don't need to be made.  Preview Tachi already fixed default filters

**Comment by CarlosEsco** [comment]
Why did you split tags ?

**Comment by Arraiment** [comment]
> Changes you are making for the content rating for default don't need to be made. Preview Tachi already fixed default filters

What changes?

> Why did you split tags ?

For user-friendliness really, like how its implemented on md's own site.

> Sorting by latest chapter on manga list doesn't take into account the current users language (not available in api). 

I'll see if I can make it work, otherwise I'll revert

**Comment by CarlosEsco** [comment]
> > Changes you are making for the content rating for default don't need to be made. Preview Tachi already fixed default filters
> 
> What changes?
The content rating on the initial query
> 
> > Why did you split tags ?
> 
> For user-friendliness really, like how its implemented on md's own site.
Are you changing how the filter sheet looks to match?  
> 
> > Sorting by latest chapter on manga list doesn't take into account the current users language (not available in api). 
> 
> I'll see if I can make it work, otherwise I'll revert
> 
> 
There is no API endpoint so good luck

**Comment by Arraiment** [comment]
> The content rating on the initial query

I believe filters are not passed on initial queries like `popularMangaRequest`, so it would still be necessary to specify user preferred content prefs.

> Are you changing how the filter sheet looks to match?

Yes

**Comment by CarlosEsco** [comment]
> > The content rating on the initial query
> 
> I believe filters are not passed on initial queries like `popularMangaRequest`, so it would still be necessary to specify user preferred content prefs.
> 
Sure but you removed the users preference as the value and and passed all the content filters enabled

**Comment by Arraiment** [comment]
I haven't changed the content prefs for latest or popular requests though? Only added content prefs to the chapter api request for latestUpdates

**Pull request closed without merging**
