### PR TITLE
Updated MangaSum Rebranding to MangaToro

### LINKED ISSUE #7705: [Source Request] <Mangatoro>
## Source website
- Name: Mangatoro
- Link: https://www.mangatoro.com/
- Language(s): English

## Other details

Mangasum now redirects to this site in webview and thus mangasum extension is no longer working

### PR DESCRIPTION
**Pull request by nar1n**
Closes #7705

### CODE REVIEW

**Comment by Riztard** [comment]
hmm the japanese got removed

**Comment by CarlosEsco** [comment]
i assumed that was intentional?

**Comment by Riztard** [comment]
nah

**Comment by nar1n** [comment]
Not intentional, I couldn't find the Japanese button it at first. Will make another commit to fix.

**Pull request merged**
