### PR TITLE
Filtered comikey chapters

### LINKED ISSUE #8877: MangaDex: Chapters Uploaded by Comikey return No Pages found
### Source information

1.2.129

### Steps to reproduce

Find a manga with a Comikey chapter
Open it

### Expected behavior

The chapter should be able to be opened, or if it's a redirect to another site, the chapter should be hidden

### Actual behavior

The chapter returns no pages found

### Tachiyomi version

0.12.1

### Android version

Android 9

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by loocool2**
Closes #8877

### CODE REVIEW

**Comment by paulo27ms** [comment]
Bilibili Comics will also be external-only from what's planned, if you want to add that.

**Comment by alessandrojean** [comment]
> Bilibili Comics will also be external-only from what's planned, if you want to add that (for now they have pages in the API but in the future they won't I guess).

Bilibili is a special case because the Bilibili team that is uploading stuff to Dex, it's kinda like a deal between them iirc.

**Comment by paulo27ms** [comment]
I'm pointing it out because the original issue was about chapters not loading pages, in the future I'd imagine Bilibili's stuff won't have pages (I'm not sure why they have them now in the API since you can't read them on the site) but I guess that can wait until they really start uploading page-less chapters.

**Comment by CarlosEsco** [comment]
Billibilli will eventually have the latest 3 chapters redirect and older will be available on dex

**Comment by CarlosEsco** [comment]
Also comikey might be under the same boat

**Comment by paulo27ms** [comment]
Which is why something like I mentioned in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8877 would be better rather filtering out the entire group. Only filter stuff if there's no pages in the API, not hardcoded group filters.

**Comment by CarlosEsco** [comment]
Confirmed that this will all redirect

**Pull request merged**
