### PR TITLE
MangaPark v3 Fixes

### LINKED ISSUE #7213: [Bug] <MangaPark v3>: No chapters found error
@FourTOne5

MangaPark v3 extension (version 1.2.2) leads to error "no chapters found", when trying to check different manga on list.

Xiaomi Mi Note 10 Lite
Android 11
Tachiyomi Preview r3417

### PR DESCRIPTION
**Pull request by FourTOne5**
Fix No Chapter Found
Fix Only 1 image In A Chapter

Closes #7213

### CODE REVIEW

**Comment by FourTOne5** [comment]
Due to some code changes in MangaPark side only the first image of a chapter is being shown. To overcome this we need to place a value in the Local Storage like below (which I have no Idea how to do.)

|image|
|---|

**Comment by alessandrojean** [comment]
You can take a look at the JavaScript code that reads this value and see how it loads the other pages. Probably it can be some additional AJAX request.

**Comment by FourTOne5** [comment]
> You can take a look at the JavaScript code that reads this value and see how it loads the other pages. Probably it can be some additional AJAX request.

I did some digging and turns out i can do some CryptoJS stuff to get all the images. Anyway Thanks for the tip. @alessandrojean

**Comment by h-hyuuga** [comment]
> > You can take a look at the JavaScript code that reads this value and see how it loads the other pages. Probably it can be some additional AJAX request.
> 
> I did some digging and turns out i can do some CryptoJS stuff to get all the images. Anyway Thanks for the tip. @alessandrojean
> 

If the site is doing AES crypto and is relying on CryptoJS, I wrote some code to do decryption in another extension


https://github.com/tachiyomiorg/tachiyomi-extensions/blob/004355c93f71bfdd3a5bdff6d5dc51402b9831ac/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt#L580

Specifically it implements AES decryption with:

* CBC mode of operation
* PKCS5 Padding

which are CryptoJS's defaults.

**Comment by jopejoe1** [comment]
Mangapark v3 icons
[mangaparkv3.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6604194/mangaparkv3.zip)

**Pull request closed without merging**
