### PR TITLE
manganato: rename manganelo to -nato

### PR DESCRIPTION
**Pull request by OncePunchedMan**
renaming
fix fetching date
add new icons

### CODE REVIEW

**Comment by bango17** [comment]
How about the downloaded chapters?

**Comment by CrepeTF** [comment]
You'll have to rename the folder manually using a file manager

**Comment by bango17** [comment]
Sad thing for people like me who downloaded about like 1000+ chapters

**Comment by OncePunchedMan** [comment]
> Sad thing for people like me who downloaded about like 1000+ chapters

renaming one folder isn't that hard, is it

**Comment by bango17** [comment]
Ummm can I ask how onepunchman? Like its not possible for mine because downloaded chapters have the word manganelo on them and i need to do it one by one

**Comment by bango17** [comment]
Screenshot_20210528_170539
Screenshot_20210528_170551

**Comment by bango17** [comment]
Mine's like that so i need to change the name of all the chapters

**Comment by bango17** [comment]
Thank youuuu so muchh this is a great help

**Pull request merged**
