### PR TITLE
MangaCatalog multisrc extension

### LINKED ISSUE #6308: [Source Request] <readjujutsukaisen>
## Source website 
- Name: readjujutsukaisen
- Link: https://ww1.readjujutsukaisen.com/
- Language(s): English

### LINKED ISSUE #6309: [Source Request] <readmha>
## Source website
- Name: remha
- Link: https://ww6.readmha.com/
- Language(s): English

### LINKED ISSUE #6408: [Source Request] <https://ww7.readsnk.com/manga/shingeki-no-kyojin-colored/>
## https://ww7.readsnk.com
- Name: Attack on Titan - Colored Edition
- Link: https://ww7.readsnk.com/manga/shingeki-no-kyojin-colored/
- Language(s): English

## Other details
So, a friend of mine really likes this website to read SnK manga, and he wants it added as a source on this app. I've seen a website similar to this one already being requested here, and it was rejected because it was "available from plenty of other sources". However, he didn't find the colored variant of the manga on any other source.

### PR DESCRIPTION
**Pull request by jopejoe1**
This is a multisrc extension that implements a collection of sites listed on [https://ww3.readopm.com/read-manga/](https://ww3.readopm.com/read-manga/). Just one small problem i have no idear what the collection of these sites is called so currently im using a development name for the name of the multisrc extension. If some has any idear what i should call this multisrc extension please comment.

Know issues:
- [ ] Need to manually add all manga for one site
- [ ]  long names
- [x] No name for multisrc

This add the Following Sites:

- https://ww6.readmha.com
- https://ww3.readopm.com
- https://ww8.tokyoghoulre.com
- https://ww3.read7deadlysins.com
- https://ww1.readkaguyasama.com

Closes #6309
Closes #6308
Closes #6408

### CODE REVIEW

**Comment by jopejoe1** [comment]
Added the following sources:
- https://ww1.readjujutsukaisen.com
- https://ww1.readtowerofgod.com
- https://ww2.readhxh.com
- https://readsololeveling.org
- https://ww3.readneverland.com

**Comment by Riztard** [comment]
the name i think contains M and C
because this is their favicon

**Comment by CarlosEsco** [comment]
MangaCatalog?

Also can you add https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6408

**Comment by jopejoe1** [comment]
Added Following source:
- [https://ww7.readsnk.com/](https://ww7.readsnk.com/)

Renamed it to Manga Catalog as that i have no better idear on what to name
Closes #6408

**Pull request merged**
