### PR TITLE
Bilibili Manga: change lang code and extension name

### PR DESCRIPTION
**Pull request by kasperskier**
- changes lang code from `zh-Hans` to `zh` since all other Chinese extensions use `zh`
- changes extension name to Chinese

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Extension names uses romanized names, that's why I kept Bilibili Manga. The name inside the class is still the Chinese one. The `zh-Hans` was already discussed before and we prefer to have a more specific language code rather than just `zh`. Knowing if it's traditional or simplified helps a lot language learners.

**Comment by kasperskier** [comment]
@alessandrojean Let me list some of my observations.

### Confusing behavior in app

Currently this is the only single (non-multi language) source classified as `zh-Hans`. All other single Chinese sources are classified in `zh`.

When installing Tachiyomi on a Simplified Chinese system, the selected languages by default are All, English and Chinese. Chinese (hans) is not selected. Also, in the language list, Chinese (hans), if not selected, is at the bottom of the list, thus hard to find. Moreover, Chinese (hans) is displayed as `中文 (HANS)`, making it hard to recognize it as Simplified Chinese.

This is why someone posted #10547\. The user experience is confusing, especially for Chinese users.

### Necessity of classification

In https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10547#issuecomment-1019723815 @ZerOri claimed that most Chinese sources contain both variants and that Chinese users can understand both of them.

Regarding the status of the sources, I mentioned in https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11839#issuecomment-1126169794 that many Chinese scanlators tend to convert their work in Simplified Chinese to Traditional Chinese before posting on web. You can verify it by searching [`漫画翻译 为什么 繁体`](https://cn.bing.com/search?q=%E6%BC%AB%E7%94%BB%E7%BF%BB%E8%AF%91+%E4%B8%BA%E4%BB%80%E4%B9%88+%E7%B9%81%E4%BD%93) (`manga translation, why, Traditional` in Simplified Chinese) and finding a lot of questions and posts by people interested in this phenomenon. Thus, unofficial sites usually contain mixed content and there's no way to classify them. Tagging the official sites would be unnecessary in my opinion since they usually limit viewing on web and force people to use their apps, rendering them un-useful.

In https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10547#issuecomment-1020077441 @arkon disagreed with the latter generalization. However, this is the truth for a lot of native Chinese speakers. There are few researches or surveys on this, but you can read [this stack exchange](https://chinese.stackexchange.com/questions/2577/what-are-the-relative-literacy-rates-in-for-simplified-and-traditional-character). The fact that a lot of Simplified Chinese scanlators still output Traditional Chinese contents and that readers are satisfied with it can prove this.

Previous changes and discussions in #6849 and #10562 are mostly about multi-language sites. Those multilingual platforms adopt language tags on a **per-comic/per-translation** basis, but Tachiyomi is different in that the language classification happens on **sites or sources**. You should take this into consideration as well.

Regarding language learners, I think native user experience should be more important somehow. After all, reading comic is not the mainstream way to learn Chinese, neither is Tachiyomi a language learning app. As far as I know, you can learn much more if you participate in scanlators' work, and if you do you won't really need this classification - which is already not useful since the tricky parts lie beyond this.'

### My words

You guys are the active contributors, and I understand you want to make this app more "perfect". But are these changes really useful for most Chinese extension users, or do they just look good to *you* and look confusing to *them*? The decision is upon you.

**Comment by alessandrojean** [comment]
> When installing Tachiyomi on a Simplified Chinese system, the selected languages by default are All, English and Chinese. Chinese (hans) is not selected.

Yes, this is an app bug that needs to be addressed, it also happens with Brazilian Portuguese for example. But this shouldn't be an enourmous issue to stop correct classifying the source's languages (my opinion).

Bilibili themselves classifies their language as Chinese Simplified, so I don't get beside that app bug what's the real issue into correct classifying it as `zh-Hans`. The language name shown in the app is just how the Java's `Locale` displays it, so it's a upstream issue.

My opinion is to let as it is, but I don't really speak Chinese, but I can relate to the issue by being a Brazilian Portuguese native speaker, where we also have this generalization problem with `pt`, `pt-BR` and `pt-PT`. In general, even if we can understand `pt-PT`, we prefer to it being correcly labeled as it or `pt-BR` because a lot of things are confusing.

Anyway, would be good to get a second thought on this by @arkon.

**Comment by kasperskier** [comment]
> My opinion is to let as it is, but I don't really speak Chinese, but I can relate to the issue by being a Brazilian Portuguese native speaker, where we also have this generalization problem with `pt`, `pt-BR` and `pt-PT`. In general, even if we can understand `pt-PT`, we prefer to it being correcly labeled as it or `pt-BR` because a lot of things are confusing.

As far as I know, this is not the case for Simplified and Traditional Chinese comics/translations. These two variants are more similar and closely related. Sites in either language welcome contents and users in the other.

**Comment by ZerOri** [comment]
> @alessandrojean Let me list some of my observations.
> 
> ### Confusing behavior in app
> Currently this is the only single (non-multi language) source classified as `zh-Hans`. All other single Chinese sources are classified in `zh`.
> 
> When installing Tachiyomi on a Simplified Chinese system, the selected languages by default are All, English and Chinese. Chinese (hans) is not selected. Also, in the language list, Chinese (hans), if not selected, is at the bottom of the list, thus hard to find. Moreover, Chinese (hans) is displayed as `中文 (HANS)`, making it hard to recognize it as Simplified Chinese.
> 
> This is why someone posted #10547. The user experience is confusing, especially for Chinese users.
> 
> ### Necessity of classification
> In [#10547 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10547#issuecomment-1019723815) @ZerOri claimed that most Chinese sources contain both variants and that Chinese users can understand both of them.
> 
> Regarding the status of the sources, I mentioned in [#11839 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11839#issuecomment-1126169794) that many Chinese scanlators tend to convert their work in Simplified Chinese to Traditional Chinese before posting on web. You can verify it by searching [`漫画翻译 为什么 繁体`](https://cn.bing.com/search?q=%E6%BC%AB%E7%94%BB%E7%BF%BB%E8%AF%91+%E4%B8%BA%E4%BB%80%E4%B9%88+%E7%B9%81%E4%BD%93) (`manga translation, why, Traditional` in Simplified Chinese) and finding a lot of questions and posts by people interested in this phenomenon. Thus, unofficial sites usually contain mixed content and there's no way to classify them. Tagging the official sites would be unnecessary in my opinion since they usually limit viewing on web and force people to use their apps, rendering them un-useful.
> 
> In [#10547 (comment)](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10547#issuecomment-1020077441) @arkon disagreed with the latter generalization. However, this is the truth for a lot of native Chinese speakers. There are few researches or surveys on this, but you can read [this stack exchange](https://chinese.stackexchange.com/questions/2577/what-are-the-relative-literacy-rates-in-for-simplified-and-traditional-character). The fact that a lot of Simplified Chinese scanlators still output Traditional Chinese contents and that readers are satisfied with it can prove this.
> 
> Previous changes and discussions in #6849 and #10562 are mostly about multi-language sites. Those multilingual platforms adopt language tags on a **per-comic/per-translation** basis, but Tachiyomi is different in that the language classification happens on **sites or sources**. You should take this into consideration as well.
> 
> Regarding language learners, I think native user experience should be more important somehow. After all, reading comic is not the mainstream way to learn Chinese, neither is Tachiyomi a language learning app. As far as I know, you can learn much more if you participate in scanlators' work, and if you do you won't really need this classification - which is already not useful since the tricky parts lie beyond this.'
> 
> ### My words
> You guys are the active contributors, and I understand you want to make this app more "perfect". But are these changes really useful for most Chinese extension users, or do they just look good to _you_ and look confusing to _them_? The decision is upon you.

Yep,as a Chinese, I totally agree with you that it is unnecessary for Chinese comic websites to differentiate between simplified and traditional.
After all, all unofficial comic sites are a mix of simplified and traditional content.Only very few websites have traditional content only.According to the opinion of the extensions author, it should be divided into three plug-in categories (HANS&HANT, HANS, HANT), which will be very confusing for Chinese users.

**Comment by arkon** [comment]
I'll be properly reading through the feedback when I get a chance tomorrow.

**Comment by arkon** [comment]
My expectation was that sites tailored to certain regions (TW, potentially HK but less so nowadays) would have been using HANT and could neatly be categorized.

If that isn't the case, which seems to be what @kasperskier is saying, and sites are in reality often mixing both HANT and HANS content, then I'm fine with using the generic `zh` locale.

I can't reopen this PR since the branch was deleted, but feel free to make another PR to recategorize the Chinese extensions as appropriate.

**Comment by kasperskier** [comment]
I've restored the branch. It would be great to categorize things together.

**Comment by arkon** [comment]
Would this still be desirable if the app enables all sub-locales by default? e.g., if the device is on `zh`, enable all `zh-XYZ` locales too.

**Comment by kasperskier** [comment]
> Would this still be desirable if the app enables all sub-locales by default? e.g., if the device is on `zh`, enable all `zh-XYZ` locales too.

It would be great. Also, "English" and "All" extensions are not useful to most Chinese users. Few Chinese translators post on these sites.

**Comment by kasperskier** [comment]
Should this be re-opened? Or a final decision should be made?

**Comment by alessandrojean** [comment]
> Should this be re-opened? Or a final decision should be made?

I am currently taking a look into enabling the sub-locales by default in the app first, so that problem doesn't happen any more. In that way, the Chinese (but also other sub-locale based, such as Portuguese and Spanish) extensions can be correctly categorized, and the users will see them by default too. I am assuming it would be okay in that way, since you said "it would be great".

If it doesn't work well, you are free to open a new PR to change the Bilibili language again 👍🏻 

Does this work for you?

**Comment by kasperskier** [comment]
Sounds okay. Would be even better if "English" and "All" extensions can be turned off by default since that's too much.

There's another issue that turning off a language in the filter also hides installed sources in that language, as they share the same options. Probably should open a new issue?

**Comment by alessandrojean** [comment]
> There's another issue that turning off a language in the filter also hides installed sources in that language, as they share the same options. Probably should open a new issue?

I think that's on purpose, but yeah, you can ask about it in the app repository either way 👍🏻

**Comment by kasperskier** [comment]
> I think that's on purpose, but yeah, you can ask about it in the app repository either way 👍🏻

There's already an issue there: https://github.com/tachiyomiorg/tachiyomi/issues/6897 

arkon seems to be against this one. Actually there is a reason: Chinese extensions (or those in another language) are so few that I can go over the list and pick one if the installed ones are not enough. I don't remember all of them in my mind. Also sometimes I need to install one or two extensions in English or Japanese. Switching between these two modes is annoying.

Another solution is to implement manual sorting of the language list. Don't know if I should open an issue or not 😂

**Comment by ZerOri** [comment]
> 



> My expectation was that sites tailored to certain regions (TW, potentially HK but less so nowadays) would have been using HANT and could neatly be categorized.
> 
> If that isn't the case, which seems to be what @kasperskier is saying, and sites are in reality often mixing both HANT and HANS content, then I'm fine with using the generic `zh` locale.
> 
> I can't reopen this PR since the branch was deleted, but feel free to make another PR to recategorize the Chinese extensions as appropriate.

To be honest, you may not be familiar with the Chinese comic market. The market size of Taiwan and Hong Kong is too small, so it is difficult to create a decent original electronic comic platform. There used to be a few, but now they no longer exist.In the future, Neither Hong Kong nor Taiwan is likely to have a large-scale electronic comics website.

**Comment by arkon** [comment]
> Should this be re-opened?

I still can't reopen it, GitHub says it was force-pushed or recreated.

> arkon seems to be against this one

I'm not convinced that you need to actively enable/disable different languages between the 2 tabs. If the issue is that it's difficult to scroll through long lists, it may be better to implement collapsable sections instead.

> To be honest, [...]

Yes, you're just reiterating previously said points.

**Pull request closed without merging**
