### PR TITLE
fix: jinmantiantang no pages found

### LINKED ISSUE #11209: "Pages Not Found" in Jinmantiantang
### Source information

Jinmantiantang Version 1.2.23

### Steps to reproduce

When I tried to read, it showed no pages found. The same applies to other manga and webtoons from this source. I tried to clear cache, etc but it doesn't work. I tried it on my tablet and phone, and the same problem occured. It works fine when I tried to read it through webview. 

### Expected behavior

Being able to read it without needing to read it through webview.

### Actual behavior

I'm only able to read it through webview and not through the extension.

### Tachiyomi version

0.13.1

### Android version

Android 12 One UI 4.0

### Other details

My apologies if this isn't filled out properly. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by lbwstco**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #11209

### CODE REVIEW

**Comment by lbwstco** [comment]
Closes #11209

**Comment by junyaotan020517** [comment]
fix ald? how to download latest ver?

**Comment by alessandrojean** [comment]
You guys need to wait until the update appears on the app, there's nothing you can do besides waiting.

**Comment by kasperskier** [comment]
@CarlosEsco Could you please merge this?

**Pull request merged**
