### PR TITLE
Remove DokkoManga per request

### LINKED ISSUE #12837: dokkomanga removal request
### Source link

http://dokkomanga.xyz

### Other details

i am currently requesting the removal of the dokkomanga extension for my website, as i do not have large servers, and the use of people logging into tachiyomi does not benefit us in any way other than just taking up resource.
Once my scanlation gets adsense revenue and we move to dedicated servers I will contact you to let you know.
Thanks for your attention

By: ShoNxDokkO Scanlation (emanuel scan leader)

P/D: I attach my personal facebook in case you want to [contact me](https://www.facebook.com/emanuelk12).

### Requirements

- [X] Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- [X] Site is not infested with user-hostile features (e.g., invasive or malicious ads)

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #12837

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Was the proof really sent? Nobody from Discord staff commented in that issue.

**Comment by vetleledaal** [comment]
Don't think so, maybe close both issue/PR as there hasn't been any contact

**Comment by alessandrojean** [comment]
Will mark this one as draft and comment there and wait a little before closing.

**Comment by alessandrojean** [comment]
Closing since there was no response in that issue.

**Pull request closed without merging**
