### PR TITLE
Project Suki: Enhancements and fixes

### PR DESCRIPTION
**Pull request by npgx**
### Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### Comment:

This is a draft as I still need to do some work and test it thoroughly, but it's at a good enough point.
Will try to write up on what changed near the end when this is going to be ready for review and merge, but most info should be in the commit messages.
Feel free to leave suggestions.

(For anyone curious I'm experimenting with these: https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by npgx** [comment]
Should be ready for testing 🤞🏼

**Comment by npgx** [comment]
Everything should be ready 👌🏼

**Comment by npgx** [comment]
Wait, I forgot about the Url Intent

**Comment by npgx** [comment]
I got so annoyed that I rewrote the class in Java, but could someone more Android-savvy explain to me why this [Url Activity](https://github.com/npgx/tachiyomi-extensions/blob/112909df2a2da67661cb5b63d7e08a08488dca98/src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSukiUrlActivity.kt) was complaining with a `java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics`?

**Comment by vetleledaal** [comment]
> Is the kotlin stdlib not present in the apk?

Pretty much. Some additional context I stole from #programming:
> UrlActivity is a bit jank because you write it in kotlin but in a way that does not import any kotlin stuff
> because the kotlin runtime is a compileOnly dependency for extensions

**Comment by npgx** [comment]
Understandable
Is it fine to leave the Activity in java?

**Comment by vetleledaal** [comment]
Java code has never been merged before, at least for extensions, so I'd stick with Kotlin.
```
❱ git log --name-only --pretty=format: -- '**/*.java' | sort | uniq

core/src/com/squareup/duktape/Duktape.java
lib/duktape-stub/src/com/squareup/duktape/Duktape.java
lib/preference-stub/src/main/java/android/content/Context.java
lib/preference-stub/src/main/java/android/support/v7/preference/CheckBoxPreference.java
lib/preference-stub/src/main/java/android/support/v7/preference/DialogPreference.java
lib/preference-stub/src/main/java/android/support/v7/preference/EditTextPreference.java
lib/preference-stub/src/main/java/android/support/v7/preference/ListPreference.java
lib/preference-stub/src/main/java/android/support/v7/preference/Preference.java
lib/preference-stub/src/main/java/android/support/v7/preference/PreferenceScreen.java
lib/preference-stub/src/main/java/android/support/v7/preference/TwoStatePreference.java
lib/preference-stub/src/main/java/androidx/preference/CheckBoxPreference.java
lib/preference-stub/src/main/java/androidx/preference/DialogPreference.java
lib/preference-stub/src/main/java/androidx/preference/EditTextPreference.java
lib/preference-stub/src/main/java/androidx/preference/ListPreference.java
lib/preference-stub/src/main/java/androidx/preference/Preference.java
lib/preference-stub/src/main/java/androidx/preference/PreferenceScreen.java
lib/preference-stub/src/main/java/androidx/preference/TwoStatePreference.java
lib/preference-stub/src/main/java/eu/kanade/tachiyomi/source/ConfigurableSource.java
```

**Comment by arkon** [comment]
Java's fine if you can't avoid it.

**Comment by npgx** [comment]
hmm, I'll see what I can do 👍🏼

**Comment by npgx** [comment]
Seems to be working like that
Adding more UrlActivity classes to handle different URLs would be non-ideal but fine in the future if necessary right?
Seems like kotlin doesn't like comparing/checking string values without Intrinsics

**Pull request merged**
