### PR TITLE
add few more sources & changes to some madara sources

### PR DESCRIPTION
**Pull request by CVIUS**
- added azmanhwa, blockmanga, manga47, mangadrago, mangahero, mangaleveling, mangalibrary, mangamanhua, mangamg, mangaonlineteam, mangarex, mangatop1, mangax1, manhuachill, manhuatoon, manhwapool, manhwaxz, pomanga, wekomic
- replace mangaxp icon
- add www to mangahz
- add nsfw tag to webtoonxyz

### CODE REVIEW

**Comment by Riztard** [comment]
did you check if it works? especially for the fix issue

**Comment by CVIUS** [comment]
yea

**Comment by CVIUS** [comment]
oh wait, mangadrago change .co to .com

**Comment by Riztard** [comment]
bruh, just make it `draft` if not ready yet

**Comment by CVIUS** [comment]
ready to merge

**Comment by CVIUS** [comment]
I wonder if I missed something¿ 😅

**Pull request merged**
