### PR TITLE
Remove academyvn - no longer available

### PR DESCRIPTION
**Pull request by namnguyen51**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by FourTOne5** [comment]
image

PEPEHMM

**Comment by namnguyen51** [comment]
> image
> 
> PEPEHMM

This site is no longer a manga site. Maintenance team has sold it to a 3rd party, and it's currently a novel site.

**Comment by CarlosEsco** [comment]
Has conflicts please resolve them

**Comment by namnguyen51** [comment]
> Has conflicts please resolve them

Resolved. Just realized that my fork repo hasn't updated since 2019 -.-

**Pull request merged**
