### PR TITLE
EroMuse split, refactor, bug fix

### PR DESCRIPTION
**Pull request by AriaMoradi**

### CODE REVIEW

**Comment by AriaMoradi** [comment]
The bug fix is kind of critical @arkon , merge this one before any other split PR

**Comment by CarlosEsco** [comment]
Does this not handle the NSFW annotation anymore?

**Comment by arkon** [comment]
Which part is the bug fix? Can you just have a separate smaller PR?

**Comment by AriaMoradi** [comment]
I'l turn this into a draft and PR the bug fix first.

**Pull request closed without merging**
