### PR TITLE
Source migration from RawLH to WeLoveManga

### LINKED ISSUE #8357: RawLH: HTTP Error 302
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

TachiJ2K 1.2.1

### Android version

Android 11

### Source information

RawLH 1.2.5

### Steps to reproduce

1. Attempt to browse the extension

### Expected behavior

The manga available in the extension should appear.

### Actual behavior

The manga available in the extension does not appear. [Appears instead.](https://i.imgur.com/xUX3lIK.jpg) 

### Other details

The website doesn't load on the browser nor webview. I *think* they are migrating their site to https://weloma.net/ or https://welovemanga.net/

### LINKED ISSUE #8373: WeLoveManga
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

WeLoveManga

### Source link

https://weloma.net/

### Language

Japanese

### Other details

#8357 and FMReader multisource template

### PR DESCRIPTION
**Pull request by Arraiment**
Closes #8373
Closes #8357

### CODE REVIEW

**Comment by CarlosEsco** [comment]
@alessandrojean does this need the source id override

**Comment by alessandrojean** [comment]
It needs.

**Comment by Arraiment** [comment]
What changes do I need to make?

**Comment by Riztard** [comment]
something like this https://github.com/tachiyomiorg/tachiyomi-extensions/commit/5b9dff0b8148710e9f4793432f15ed4bb829cdcb#diff-3edfc88187e0dcb81d1ca5344ba5c3bfc593c7c20f7bcca242bdcf56ffd41adeR12

**Comment by alessandrojean** [comment]
You need to get the old sourceId (can get it from the index.json inside the repo branch) and use it like so inside the source:

```kotlin
override id: Long = <the-old-id>
```

**Comment by Riztard** [comment]
but i think its hard/weird for multi-src to do that if i remember correctly

@Arraiment also remove the override file for the old one

**Comment by alessandrojean** [comment]
> but i think its hard/weird for multi-src to do that if i remember correctly

It's not, it's just needed to be placed inside the override class.

**Comment by Arraiment** [comment]
Oh ok, I'll get on it. Ty.

**Comment by alessandrojean** [comment]
I remembered something extra now. You need to keep the old package name so the users get prompt with the new update. Just revert the package change in the override file and explicitly sets it in the generator line:

```kotlin
SingleLang("WeLoveManga", "https://weloma.net", "ja", pkgName = "rawlh", overrideVersionCode = 1),
```

**Review by alessandrojean — APPROVED** [review]

**Comment by arkon** [comment]
Won't the class name change break the update behaviour?

**Comment by alessandrojean** [comment]
It should not iirc, I already updated a multisrc website just like that and the update appeared in the app.

**Pull request merged**
