### PR TITLE
Updated the new tkor website url

### PR DESCRIPTION
**Pull request by royal78**
Changed url to https://tkor.dog

### CODE REVIEW

**Comment by CarlosEsco** [comment]
You need to update the build.gradle file and bump the version

**Comment by royal78** [comment]
> You need to update the build.gradle file and bump the version = done
extVersionCode 3 to 4

**Comment by royal78** [comment]
PLEASE SEND TKOR UPDATE TO EXTANSION 
 I am tired of waiting I want to read new episodes of novel 🥰

**Comment by Riztard** [comment]
> PLEASE SEND TKOR UPDATE TO EXTANSION
> I am tired of waiting I want to read new episodes of webtoon 🥰

just build and install if you cant wait

**Comment by royal78** [comment]
> > PLEASE SEND TKOR UPDATE TO EXTANSION
> > I am tired of waiting I want to read new episodes of webtoon 🥰
> 
> just build and install if you cant wait
 Bro if I know that much about kotlin then, why I have requested to update extansion...

**Pull request merged**
