### PR TITLE
remove, fix, & added madara sources

### LINKED ISSUE #8195: Tappytoon
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

Tappytoon

### Source link

https://tappytoon.net/

### Language

English

### Other details

Add this extension pls😁

### PR DESCRIPTION
**Pull request by CVIUS**
- added fastmanhwa, gogoscans, hentairead, hentaiwebtoon, kokomanga, mangax18, manhwa18.app, manhwa.biz, manhwua.fans, skyraws, tappytoon.net (closes #8195 ), toonmany
- added nsfw override to toonily.net
- manga47: reverse chapter order
- mangamanhua, manga-fast.com: fix chapter timestamp
- remove wekomic

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Meant say for this and the last once, can you verify there were no open issues for the sources you are adding?

**Comment by Riztard** [comment]
bruh you just add wekomic and mangamanhua, and now you removing it and fix the timestamp
did you really test it first? 
image

**Comment by Riztard** [comment]
> Meant say for this and the last once, can you verify there were no open issues for the sources you are adding?

#7204 was added in #8160 then removed in this pr. not sure with others

**Comment by CVIUS** [comment]
I didn't notice little issues like timestamps, cus there's a lot of exts in it, and sometimes, I forgot to add it on the list. This applies for testing the exts too. 
For Wekomic case, I haven't tested it cuz due to the rotational brownout happening here at my place (f power supply shortage), and I'm not sure if that'll work (so I didn't mention the issue) I took a risk of adding it in hoping that it'll work, and it came out its not. That's why I'm removing it.

**Comment by CarlosEsco** [comment]
> 
> 
> I didn't notice small issues like timestamps, cus there's a lot of exts in it that I forgot to add it on the list. This applies for testing the exts too.
> For Wekomic case, I haven't tested it due to the rotational brownout happening here at my place (f power supply shortage), and I'm not sure if that'll work (so I didn't mention the issue) I took a risk of adding it in hoping that it'll work, and it came out its not. That's why I'm removing it.

I would prefer you to make the PR's smaller and actually verify the sources editted, or added before they are merged.  If you don't actually start testing them, i probably will stop merging these PRs

**Comment by CVIUS** [comment]
I am just actually doing it before people could request it.  Glad I did contribute a very little in this app. I respect your decision, sir. Have a nice day, and sorry if I did waste your time.

**Comment by CarlosEsco** [comment]
> 
> 
> I am just actually doing it before people could request it. Glad I did contribute a very little in this app. I respect your decision, sir. Have a nice day, and sorry if I did waste your time.

I'm not saying to stop, I'm saying add one or two, and verify they work before opening the PR.  Committing broken extensions is not ideal and makes your PR's untrustworthy

**Pull request merged**
