### PR TITLE
Created a standalone extension for TCBScans due to layout changes

### LINKED ISSUE #6869: [Bug] <tcb scans>: <can't display manga in extension>
## Device information
- Tachiyomi version: stable 0.10.12
- Android version: 11

## Source information
- Name: TCB scans
- Extension version: 1.2.3

### Expected behavior
Should have shown the manga in their list which is one piece

### Actual behavior
Nothing in the extension but the webview works fine

### PR DESCRIPTION
**Pull request by fabiomurru96**
Closes #6869

### CODE REVIEW

**Comment by CVIUS** [comment]
need to bump the `extVersionCode`

**Comment by fabiomurru96** [comment]
Ah ok, done!
I had seen that in the MangaMainac generator it was `overrideVersionCode = 2` so I thought it had to be 3

**Comment by tanuukii** [comment]
Thank you for fix!❤️ I'm waiting for update😁

**Comment by tanuukii** [comment]
Hopefully update will come today😅

**Comment by tanuukii** [comment]
Pls add this too D:

**Comment by arkon** [comment]
@tanuukii Stop spamming.

**Comment by tanuukii** [comment]
> @tanuukii Stop spamming.

Sorry.

**Pull request merged**
