### PR TITLE
MangaGeko: fix Lasted

### PR DESCRIPTION
**Pull request by pizidavi**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Mara101-Anna** [comment]
MangaGeko is not working after the update today on Tachiyomi J2K.
It shows NO RESULT FOUND.

PLEASE HELP 
I HAVE ALL MY MANGA ON THIS EXTENSION

**Comment by pizidavi** [comment]
You are right, sorry
I'll do it soon

**Comment by gloist** [comment]
> MangaGeko is not working after the update today on Tachiyomi J2K. It shows NO RESULT FOUND.
> 
> PLEASE HELP I HAVE ALL MY MANGA ON THIS EXTENSION

get to the history and download v1.4.18

**Comment by Mara101-Anna** [comment]
> > MangaGeko is not working after the update today on Tachiyomi J2K. It shows NO RESULT FOUND.
> > PLEASE HELP I HAVE ALL MY MANGA ON THIS EXTENSION
> 
> get to the history and download v1.4.18

How to download MangaGeko  v1.4.18 ?

My MangaGeko version is  v1.4.19

**Comment by gloist** [comment]
> How to download MangaGeko v1.4.18 ?
> 
> My MangaGeko version is v1.4.19

Go to the repo branch and look for the history.

**Pull request merged**
