### PR TITLE
MangaHub: update API key again

### LINKED ISSUE #13040: Mangahub / Mangakakalot.fun API rate limit
### Source information and language

Mangakakalot.fun 1.3.9

### Steps to reproduce

1. Choose mangakakalot.fun source
2. Read manga for a while

### Expected behavior

Mangas still load normally

### Actual behavior

Screenshot_20220817-163431_Tachiyomi

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Managing cookies 🤮

Also switched the "recently" cookie to use `buildJsonObject` instead

Closes #13040

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by raziel100** [comment]
I believe the issue #13040 is still happening the same way as previously

**Comment by vetleledaal** [comment]
MangaHub works fine for me as of now, but they will probably break it again soon. When  that happens feel free to open another issue

**Comment by raziel100** [comment]
> MangaHub works fine for me as of now, but they will probably break it again soon. When that happens feel free to open another issue

Strange, for me after reading 4 to 5 chapters I get the Api error all over again, I have tried more than once and I didn't see a change, should I do something more?

**Comment by vetleledaal** [comment]
That's the same behaviour as if you haven't updated to 1.3.20. Make sure you're using Tachiyomi 0.13.6, and if you're already on the latest version try clearing cookies.

**Comment by raziel100** [comment]
> That's the same behaviour as if you haven't updated to 1.3.20. Make sure you're using Tachiyomi 0.13.6, and if you're already on the latest version try clearing cookies.

I have updated and I'm using the 13.6

**Pull request merged**
