### PR TITLE
Add Athena fansub extension 

### PR DESCRIPTION
**Pull request by Tarik366**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

I'm too clumsy to build apk, sorry.

### CODE REVIEW

**Comment by alessandrojean** [comment]
Please use the icon generator tool linked in the CONTRIBUTING.md guide in the repository. The one in this PR has transparent backgrounds and doesn't fit the pattern used by the other extensions.

**Comment by Tarik366** [comment]
> Please use the icon generator tool linked in the CONTRIBUTING.md guide in the repository. The one in this PR has transparent backgrounds and doesn't fit the pattern used by the other extensions.

I fixed up

**Comment by Riztard** [comment]
failed to build btw

**Comment by Tarik366** [comment]
I tried to build this

**Pull request closed without merging**
