### PR TITLE
Remove MangaRaw source

### LINKED ISSUE #11047: Remove manga1000/manga1001
### Source information

MangaRaw1.2.4

### Steps to reproduce

open manga1000/manga1001

### Expected behavior

load manga list

### Actual behavior

manga1000 404
manga1001 time out

### Tachiyomi version

0.13.1

### Android version

Android 11 MIUI12.5

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ringosham**
Closes #11047 

Both sites have been DMCA'd by Shogakukan, Shueisha, Kadokawa and Kodansha and will not be coming back.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by ringosham** [comment]
On a second note, comick.top seems to be the new domain of MangaRaw

We should change the domain instead

**Comment by ringosham** [comment]
I found quite a number of sites that looks exactly the same as MangaRaw.

Should I close this and change the domain?

**Comment by CarlosEsco** [comment]
If there are a number of them, maybe make a factory source for it?

**Comment by ringosham** [comment]
Superseded by #11058

**Comment by arkon** [comment]
Since there's apparently new sites that could use the new factory, can you try adding them too rather than deleting the factory outright?

**Comment by ringosham** [comment]
That's what I did in the previous closed PR. I changed the domains with some changes to the selectors, but you guys told me to basically make a new extension with a new factory, and this old factory is thrown away?

Am I reading this right? What should this new factory be called since it's not the same owner from MangaRaw?

**Comment by arkon** [comment]
@FourTOne5 @CarlosEsco Did you guys read the other PR incorrectly?

The sites' layouts are the same so the factory can be reused, right?

**Comment by CarlosEsco** [comment]
I don't think you know what a factory is, in this context.

**Comment by FourTOne5** [comment]
@arkon @CarlosEsco Maybe I caused a misunderstanding but what I meant was that the copycat should go under a "MangaRaw (Unoriginal)" extension instead of the original one like everyother copycat sites.

**Pull request closed without merging**
