### PR TITLE
CopyManga: rewrite

### LINKED ISSUE #12320: copymanga : Extremely slow and unsteady loading speed
### Source information

copymanga 1.3.28

### Steps to reproduce

1.open the source
2.the interface circling for a long time and much probably the error 504 take place
3.select a random manga
4.cover image can't loaded(or just in a extremely slow speed) , and when the chapters was loaded , the error 502 often take place

### Expected behavior

the error 502 and error 504 shouldn't take place frequently , and the covers and chapters should be loaded successfully

### Actual behavior

the error 502 and error 504 take place frequently , and the covers and chapters can't be loaded successfully the most time

### Tachiyomi version

0.13.4

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #12346: CopyManga: cannot load, update or read any manga from it
### Source information

CopyManga 1.3.28

### Steps to reproduce

1.Install this extension
2.search some mangas
3.select the manga from CopyManga and view details

### Expected behavior

normally display the introduction and chapter list

### Actual behavior

load name, cover and introduction normally, but cannot load chapter list, and shows:
"Attempt to invoke virtual 
method 'java.lang.String
org.jsonp.nodes.Element.data()'on a
 null object reference"

### Tachiyomi version

0.13.4

### Android version

11

### Other details

MIUI 12.5.6 based on Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by stevenyomi**
Supercedes #12332

- Rewrite using APIs, closes #12346
  - no longer depends on org.json
  - better filters
  - better parsing
  - better chapter lists
  - better preferences
    - add option to prefer WebP images, reducing site load
    - add option to change domain
    - all preferences take effect without restart
- Changes to rate limit, fixes #12320
  - Change rate limit from 1 per 2 seconds to 2 per 4 seconds
  - Make rate limit interceptor nonblocking in https://github.com/tachiyomiorg/tachiyomi/pull/7389 and integrate that into the extension
- Update icons
- Exclude unused dictionary files in charater converter library to reduce size

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by zhongfly** [comment]
The rate limit is too strict, because checking for an update of a comic requires at least 2 requests, so it takes 4 seconds to update a comic at the fastest, which is too slow.
I think it needs to be changed to a preference that the user can modify

**Comment by stevenyomi** [comment]
> The rate limit is too strict, because checking for an update of a comic requires at least 2 requests, so it takes 4 seconds to update a comic at the fastest, which is too slow. I think it needs to be changed to a preference that the user can modify

Regarding the math, the new limit allows 2 requests to be executed at the same time, so ideally it would not take 4 seconds. As you know, some titles have multiple chapter groups, and the app might re-download the thumbnail, so it might take 3~5 requests. Considering that network requests are already quite slow, 4+ seconds is very acceptable.

The rate limit was added to close #9096, where the site owner said they were unhappy with the extension. Traffic from Tachiyomi is useless for them, increasing site load while not producing ad clicks. Therefore, for a third-party aggregator website (non-official or licensed), rate limit is rather necessary to relieve pressure on them, so we should not add such preference unless the website is really inaccessible. According to my tests, after the fix the load speed is reasonable and acceptable.

**Comment by stevenyomi** [comment]
By the way, I cached the chapter group information locally, so for updates it will take just that amount (1~3 requests).

**Comment by zhongfly** [comment]
There is one more question: I found that you modified the image file in every pr. Is it something that your development tool does automatically? Because Git can not diff birnay file, it stores every single version of every single binary file within the repository, which also makes the git data larger and larger.
I think it would be better to only adjust the picture when necessary.

**Comment by stevenyomi** [comment]
In #12226 I optimized the old, blocky icons and in this PR I replaced it with the app icons. It won't take up too much space. If you find your clone too big, it's most likely because git fetched objects from the `repo` branch and all other unused extensions. Follow the steps that I wrote [here](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#cloning-the-repository) and you will get a smaller repo.

**Pull request merged**
