### PR TITLE
Remove paprika

### PR DESCRIPTION
**Pull request by AriaMoradi**
All domains are down.
confirmed by 3 people.

### CODE REVIEW

**Comment by arkon** [comment]
These sites still load for me:

- http://mangastream.xyz
- http://readmangafox.xyz
- http://manganelos.com
- http://mangadogs.fun
- http://mangareader.cc/

**Comment by AriaMoradi** [comment]
Spreadsheet links are https, thats why none where loading, they don't have https.

**Comment by arkon** [comment]
The others in the factory _are_ seemingly dead though.

**Comment by Soitora** [comment]
Updated the spreadsheet to fix https and tell which of these were down

**Pull request closed without merging**
