### PR TITLE
New Source: SobatManKu

### LINKED ISSUE #17477: Sobatmanku
### Source name

Sobatmanku19

### Source link

https://www.sobatmanku19.site/

### Source language

Indonesia

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Rewtio**
Close #17477

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
This is just using ZeistManga theme, use the multisrc theme instead.

**Comment by Rewtio** [comment]
I apologize for my mistake, this is my first time contributing to add new source.
I'm unable to find the theme of the site before, thank you for the confirmation.

The source had been migrated to ZeistManga Theme now.

**Comment by Riztard** [comment]
iconnya pake ini aja, ngambil dari discord mereka
[ic_launcher (35).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/12879019/ic_launcher.35.zip)

**Comment by Rewtio** [comment]
@alessandrojean mind if you take a look? the source is ready for review
i already tested it myself

**Pull request merged**
