### PR TITLE
Update lang codes in a few extensions

### PR DESCRIPTION
**Pull request by jopejoe1**
Reduces the  amount of Chinese lang codes from 7 to 3
Edit: Also fixed some wrong lang codes

Related to #6889
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Shouldn't be better to use `zh-Hans` and `zh-Hant` as Bilibili and MangaDex (and soon MangaToon) uses it?

**Comment by jopejoe1** [comment]
> Shouldn't be better to use `zh-Hans` and `zh-Hant` as Bilibili and MangaDex (and soon MangaToon) uses it?

Yeag, for some reason i read it as `zh-HANS` and `zh-HANT` in dex
 
> Also needs to keep the old IDs in Batoto and Mangapark to avoid unnecessary migrations.

Done

**Comment by alessandrojean** [comment]
I think MangaPark and Batoto constructor `lang` parameter needs to be changed to final, otherwise there will be a compile error.

```kotlin
final override val lang: String
```

**Comment by jopejoe1** [comment]
> I think MangaPark and Batoto constructor `lang` parameter needs to be changed to final, otherwise there will be a compile error.
> 
> ```kotlin
> final override val lang: String
> ```

Worked fine in Android Studio for me, but changing it is not gone hurt

**Review by alessandrojean — APPROVED** [review]

**Review by alessandrojean — APPROVED** [review]

**Comment by alessandrojean** [comment]
Will close #6849 now.

What needs to be done in another future PR is review the `zh`-only sources and change the language to `-Hans` or `-Hant`, so they get grouped together in the listing.

**Pull request merged**
