### PR TITLE
[RU] AllHentai - Change url, fix status, add "No auth" message

### LINKED ISSUE #13485: AllHentai changed site/address
### Source information and language

Extension version 1.3.29

### Steps to reproduce

Step 1 
Launch the application 
Step 2
run extension AllHentai

### Expected behavior

launch extension and view content 

### Actual behavior

gives an error that the site or address has moved 

### Tachiyomi version

0.13.6

### Android version

Android 11

### Other details
hello guys, change the site address/link AllHentai
 http://22.allhen.online
Screenshot_2022-09-16-15-08-45-46_680d03679600f7af0b4c700c6b270fe7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by klaseca**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #13485

### CODE REVIEW

**Comment by e-shl** [comment]
Why duplicate the shared code from multisrc?

**Comment by klaseca** [comment]
> Why duplicate the shared code from multisrc? changing the domain is enough

In `mangaDetailsParse` method I changed getting status
In `pageListParse` method I added a message if auth is required to get content

**Comment by e-shl** [comment]
> In `mangaDetailsParse` method I changed getting status
> In `pageListParse` method I added a message if auth is required to get content

do it via multisrc

**Comment by klaseca** [comment]
> > In `mangaDetailsParse` method I changed getting status
> > In `pageListParse` method I added a message if auth is required to get content
> 
> do it via multisrc

I can do this for message, but not for status (in other sources status is correct)

**Comment by e-shl** [comment]
> not for status (in other sources status is correct)

the status can be implemented with a couple of lines as an alternative.
and if/when it gets into other sources, sources will immediately start using the new code.

**Comment by klaseca** [comment]
Closed in favor of  #13498

**Pull request closed without merging**
