### PR TITLE
Add source: I Roved Out

### PR DESCRIPTION
**Pull request by GoldenRover**
Did not find any feature requests or existing PRs for this source

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher) to generate the icons.

**Comment by GoldenRover** [comment]
I did, did they come out wrong?

**Comment by alessandrojean** [comment]
Yes, the other sizes have a transparent background. It would also be good to add a larger padding.

**Comment by GoldenRover** [comment]
Could you point out which icon is wrong? I literally copy pasted from the .zip the tool created.
I expanded the padding from the default -5% to 0, seems to look fine. If I expand it any further, it starts to crop the icon.

**Comment by alessandrojean** [comment]
Here, use [these icons](https://github.com/tachiyomiorg/tachiyomi-extensions/files/8548752/ic_launcher.zip) instead, I already made then right to follow the current pattern adopted by the other extensions.

**Pull request merged**
