### PR TITLE
Bypass cloudflare WAF using webview in MyReadingManga

### LINKED ISSUE #7923: MyReadingManga: Can't read manga HTTP error 403 but works in webview
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3537

### Android version

Android 11

### Source information

MyReadingManga v1.2.41

### Steps to reproduce

1. Open source MyReadingManga or saved manga from MyReadingManga
2. Source display HTTP error 403: Check website in WebView or HTTP error 403 for saved manga
Screenshot_20210629-194810_Tachiyomi
3. Open source in WebView
Screenshot_20210629-194822_Tachiyomi
4*. Exit WebView, retry source but still displays HTTP error 403: Check website in WebView

### Expected behavior

If source displays HTTP error 403, open it in WebView wait for Cloudflare, exit WebView, hit retry and source will load

### Actual behavior

If source displays HTTP error 403, open it in WebView, fully loads website [Cloudflare doesn't come up], exit WebView and hit retry but still displays HTTP error 403

### Other details

I've already cleared cookies, database, and chapter cache
I've also cleared cache for Android System WebView and Chrome to see if Cloudflare will come up, it didn't
My IP can't be banned because then I wouldn't be able to access the site at all
I was running a previous preview version that worked for three days then today it didn't. So I updated Tachiyomi to r3537 to see if it would fix it, it didn't.

### PR DESCRIPTION
**Pull request by mountfox**
Context: #8547. Close #7923 and #8484.

Use a WebView to run the Cloudflare browser integrity checking when necessary. Tested and worked on an Android 11 emulator and Samsung Galaxy S21. However, I am not sure if cleaning the cookies of webview has any impact on other extensions.

### CODE REVIEW

**Comment by CarlosEsco** [comment]
2 things i see.
1.  The interceptor should probably be in the library moudle
2.  Clearing the cookies is gonna clear all the cookies for all extensions

**Comment by mountfox** [comment]
@CarlosEsco I just made the interceptor remove only the `__cf_bm` cookie for the myreadingmanga.info domain. In doing this cookies from other domains should stay untouched.

As for make the fix a library module, I am not very confident about it since other sites can enforce different levels of WAF, which in turn might use different cookies. This workaround might not be applicable to other sites/extensions. And I am unsure about the requirements and processes of making a library module for this project.

**Review by CarlosEsco — APPROVED** [review]

**Comment by arkon** [comment]
This seems effectively like a modification to the [existing interceptor](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt). Any reason why changes can't be made to that instead of replicating most of it?

**Comment by mountfox** [comment]
@arkon Like I said, this workaround really depends on the Cloudflare anti-bot configuration of each site. And there are [several reasons](https://support.cloudflare.com/hc/en-us/articles/115003014512-4xx-Client-Error-Why-am-I-getting-a-403-error-#code_403) that Cloudflare can throw a 403 exception, most of which I have no experience with. I feel that directly modifying the core Cloudflare interceptor implementation can have unwanted side effects on other extensions which employ different Cloudflare protection features.

Since currently most of other extensions work just fine right now, I suppose the best way is to make a separate interceptor first, and gradually introduce it to other extensions which have the same Cloudflare 403 issue. Finally, we can merge the workaround with the original Cloudflare interceptor when we have sufficient adopters.

**Review by arkon — APPROVED** [review]

**Pull request merged**
