### PR TITLE
Fixed VMP thumbnails and chapters not loading

### PR DESCRIPTION
**Pull request by Neoterux**
Fixed IllegalArgumentException when saving thumbnail and when loading chapter images.

### CODE REVIEW

**Comment by arkon** [comment]
Please update the `extVersionCode` value in the extensions' `build.gradle` files as well.

**Comment by Neoterux** [comment]
updated version codes

**Comment by E3FxGaming** [comment]
You're not supposed to increment the `libVersion`, that one should remain as `1.2`.

Only increment the `extVersionCode` to `1.3`

**Comment by Neoterux** [comment]
oh, ok sorry for that

**Pull request merged**
