### PR TITLE
TMO ratelimit options

### PR DESCRIPTION
**Pull request by TheeoCornnaro**
list of values for ratelimit is not enough,  chapter ratelimit is 10, but image ratelimit is higher.

added more values for the user to choose the right ratelimit, this variates from image hosting server. 

it is annoying to be reading and then stop for a minute on the images because the choices were below the server cap.

### CODE REVIEW

**Review by alessandrojean — APPROVED** [review]

**Comment by arkon** [comment]
Is there really a point of a rate limit if you can set it to 999...?

**Comment by TheeoCornnaro** [comment]
> Is there really a point of a rate limit if you can set it to 999...?

not really, it was a way to set it to disabled. that is more for the images rate limit, in the chapter ratelimit, 10 is the number, but in the image rate limit, I guess it depends on the chapter number of images, I reduced it to 100 as maximum.

**Comment by CarlosEsco** [comment]
fix merge conflict please

**Comment by TheeoCornnaro** [comment]
> fix merge conflict please

done

**Pull request merged**
