### PR TITLE
Updating MangaLek Domain.

### PR DESCRIPTION
**Pull request by Le-Thon**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by Le-Thon — COMMENTED** [review]
Updating MangaLek Domain.

**Comment by alessandrojean** [comment]
Have you tested your changes by compiling the extension through Android Studio? The branch names suggests the commit was done through GitHub web instead.

**Comment by Le-Thon** [comment]
> Have you tested your changes by compiling the extension through Android Studio? The branch names suggests the commit was done through GitHub web instead.

I did everything works fine .

**Comment by omar-bear** [comment]
wow its really complicated i tryed to clone the project and checkout in this branch and build the apk in local didnt understand how to focus on mangalek before building the apk, its not mentioned on the documentation can you help me @Le-Thon please 😢

**Comment by alessandrojean** [comment]
Read the CONTRIBUTING.md guide, it has instructions on how to build and edit multisrc extensions.

**Comment by omar-bear** [comment]
i really tried @alessandrojean, can you tell me which part exactly helps to do build that ? 
maybe im missing something

**Comment by alessandrojean** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#multi-source-themes

**Comment by Le-Thon** [comment]
> https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#multi-source-themes
> 
> If you need additional help, ask at the #programming channel on [our Discord server](https://discord.gg/tachiyomi).

Please test the extension urself if u want and merge it cause people want it so bad.

**Comment by omar-bear** [comment]
Thank you, guys! I'm really excited to learn about this; it's not just for the APK! I hope to contribute in the future. I'm a web developer and not accustomed to Android development, but it's time to learn, haha!

**Comment by Le-Thon** [comment]
Goodluck omar in your journey ✅.

**Comment by omar-bear** [comment]
I did it finally yesterday lol, but im having this error when I open the extension with tachiyomi: `java.io.IOException: failed to bypass cloudflare` but it works when i open the page from history and i try to refresh

**Comment by Le-Thon** [comment]
It's the cloudflare troubleshooting, try to change the "User-Agent"

**Comment by omar-bear** [comment]
@Le-Thon, I did change from this list: https://www.whatismybrowser.com/guides/the-latest-user-agent/android. The first page is still not working. Do you have an example of a User-Agent that I can try? What's weird is that I got this error before, but then, it was for the whole app, not just the first page. Is it working for you, even for the first page?

**Comment by alessandrojean** [comment]
> Have tested the modifications by compiling and running the extension through Android Studio

Closing as it was not tested. Feel free to open a new PR if you manage to test it (would be better to also provide a screenshot of it working in the emulator).

**Pull request closed without merging**
