### PR TITLE
Add New Extension: Pornhwa18

### PR DESCRIPTION
**Pull request by MeLoseAgain**
#14037 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by MeLoseAgain** [comment]
@arkon @TheKingTermux @alessandrojean

**Comment by TheKingTermux** [comment]
> @TheKingTermux

Why you tag me ?
I didn't a member

**Comment by MeLoseAgain** [comment]
> > @TheKingTermux
> 
> Why you tag me ? I didn't a member

uhh, I guess you are included

**Comment by alessandrojean** [comment]
Don't ping users to ask the merge to be quicker. It will be reviewed and merged when someone have free time.

**Comment by arkon** [comment]
Use a square background when using https://as280093.github.io/AndroidAssetStudio/icons-launcher.html so that it fits with the other extensions' icons.

**Comment by MeLoseAgain** [comment]
> Use a square background when using https://as280093.github.io/AndroidAssetStudio/icons-launcher.html so that it fits with the other extensions' icons.

I used it from there, made an icon generator from the site you provided yesterday

**Comment by arkon** [comment]
Note the "**Use a square background**" part.

**Comment by MeLoseAgain** [comment]
``> > Use a square background when using https://as280093.github.io/AndroidAssetStudio/icons-launcher.html so that it fits with the other extensions' icons.
> 
> I used it from there, made an icon generator from the site you provided yesterday


> Note the "**Use a square background**" part.

sorry i will correct

**Comment by MeLoseAgain** [comment]
> Note the "**Use a square background**" part.

``

this is what you mean? I've used square

**Comment by arkon** [comment]
Yes, similar to the backgrounds for the icons seen on https://tachiyomi.org/extensions/

**Comment by MeLoseAgain** [comment]
> Yes, similar to the backgrounds for the icons seen on https://tachiyomi.org/extensions/

I already use it I generate icon him there

**Comment by MeLoseAgain** [comment]
https://telegra.ph/file/2bc19bdb2cb71ac37cc2f.jpg

this is the icon that I got directly from the web that you provided

**Comment by arkon** [comment]
I'm not entirely sure what you're doing, but it definitely includes the background for me:

ic_launcher

**Comment by MeLoseAgain** [comment]
> I'm not entirely sure what you're doing, but it definitely includes the background for me:
> 
> ic_launcher

ok i will fix it

**Comment by MeLoseAgain** [comment]
> I'm not entirely sure what you're doing, but it definitely includes the background for me:
> 
> ic_launcher

I'm a little confused, because everything should be square and I didn't change anything from that site, I uploaded it right away

**Pull request closed without merging**
