### PR TITLE
Change URL for Furyosquad

### LINKED ISSUE #17357: [FR] FuryoSquad
### Source name

FuryoSquad

### Source language

French

### Source link

https://furyosquad.com/

### Other details

Source closed 2 days ago.

https://twitter.com/FuryoSquad/status/1684987082450845697

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #17358: [FR] FuryoSociety
### Source name

FuryoSociety

### Source link

https://furyosociety.com/

### Source language

French

### Other details

New team continuing the legacy of the now dead FuryoSquad

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KirinRaikage**
Checklist:

Closes #17358 
Closes #17357 

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Review by stevenyomi — CHANGES_REQUESTED** [review]
Do not change the package name. Should also keep the source name if it's not a big problem. Only change the base URL.

**Comment by alessandrojean** [comment]
What Steven said, if the package name is changed, users will not receive the update and the app will think it's a completely different extension.

**Comment by KirinRaikage** [comment]
Noted. I'll just change the URL, thanks!

**Comment by Cypral** [comment]
It's not a team rebrand tho, FuryoSquad closed and some members of this team that still wanted to scanlate created FuryoSociety. 
I thought creating a new source would be the way but it's up to y'all to determine if keeping the same package name is an issue or not, I personally don't really care

**Comment by stevenyomi** [comment]
It depends on whether the manga and chapter URLs have changed or not.

@KirinRaikage Can you update your original manga entries after updating to this extension?

**Comment by KirinRaikage** [comment]
Nothing changed apart from the base URL.

**Pull request merged**
