### PR TITLE
MCCMS: add, remove and fix sources

### LINKED ISSUE #14273: haoman8.com
### Source information and language

Haoman8 1.3.3(chinese)

### Steps to reproduce

This Site added verification
Now can't search and no data for last update
and comics not to be added to the bookshelf

Comics that have been added to the bookshelf can continue to be updated and read

### Expected behavior

replace it

### Actual behavior

replace it

### Tachiyomi version

J2K v1.5.9

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14316: Haoman6: No results found
### Source information and language

Zh.haoman6 1.3.6 (中文）

### Steps to reproduce

No found result when click

### Expected behavior

Able to browse

### Actual behavior

No result found

### Tachiyomi version

0.14.2

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #14521: manman
### Source name

manman

### Source link

https://www.hanman.cyou/

### Language

Chinese

### Other details

+18 / NSFW: yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by stevenyomi**
- Fix Haoman6 (closes #14316), Haoman6 (g-lens), Haoman8 (closes #14273)
- Remove Pupu Manhua
- Readd Haomanwu
- Add Kuaikuai Manhua and bz Manhua
- Add 5 NSFW sources, closes #14521

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Riztard** [comment]
i think it would be better to separate the `fix` pr 
or maybe fix, add, remove

**Comment by stevenyomi** [comment]
> i think it would be better to separate the `fix` pr

The fix is basically swapping the implementation. Changes for fixing and adding overlaps a lot so there's no point in splitting, considering it's the same multisrc theme after all.

**Comment by Riztard** [comment]
for better changelog

**Comment by stevenyomi** [comment]
> for better changelog

Bruh. How can I do it in the first place? Adding the sources requires code from the "fix" part so the second PR will depend on the first one. Do I send commit 1 in the first PR and commit 1+2 in the second?

We only require 1 source per PR for better changelog, not one small patch. 

Next time try asking pringle to split his huge PR into smaller ones (like https://github.com/tachiyomiorg/tachiyomi/pull/7244) after he has open it and see how he will react.

**Comment by Riztard** [comment]
pr later :bigbrain:
also tachiapp changelog cant be accessed in app / not for user

**Pull request merged**
