### PR TITLE
[SKIP CI] Contributing update for multisrc

### PR DESCRIPTION
**Pull request by AriaMoradi**
I guess it's enough for an introduction, I'll add more in future PRs.

### CODE REVIEW

**Comment by CarlosEsco** [comment]
IS this good? You have it marked as a draft

**Comment by CarlosEsco** [comment]
Any update on this?

**Comment by AriaMoradi** [comment]
This should be enough for a general guide, the rest of docs are present in the source code.

**Comment by CarlosEsco** [comment]
Thanks

**Pull request merged**
