### PR TITLE
Remove CocoManhua due to a cat-and-mouse game

### LINKED ISSUE #11334: CoCoManhua: Failed to bypass Cloudflare
### Source information

CoCoManhua(OhManhua) 1.2.10 chinese

### Steps to reproduce

I have the proxy connection, so maybe not the network proble.
1. CoCoManhua setting is limit is 1, period is 2.
2. clink to the CoCoManhua extension.

### Expected behavior

show the manga. and can update the manga.

### Actual behavior

1. After several seconds(about 30 seconds), can't show the manga, only the error notify: Can't bypass cloudflare.
3. But I open the CoCoManhua web through the webview in tachiyomi it workes, and the web link is https://www.cocomanga.com

### Tachiyomi version

0.13.1

### Android version

Android 9

### Other details

In Webview I open one manga that in my bookshelf which is belonging to CoCoManga, which link is https://www.cocomanga.com//15336/, is works, I can see the manga list and the picture.

But when I slide down another error occur and show empty page with these code:

`网页无法打开
位于 https://xc.4po6iqp9.cn:8001/cc/4601?is_not=1&interval=111&refso=1_Linux%20armv7l_0.2_-0.2_10.1&url=hLLg3q%2F%2FDDD*(4(4.)5%3A)*(4.%2F%2F7r%5E%5Ei%2F&source=hLLg3q%2F%2FDDD*(4(4.)5%3A)*(4.%2F&jiami=1&screen=768*1024&ifrom=0&history=1&ipnumber=1&clickp=452*861&ctype=good&jstime=1649155443&t=0.6533871037512105&target=1 的网页无法加载，因为：

net::ERR_NAME_NOT_RESOLVED`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #11345: CoCoManhua: Decryption failed
### Source information

CoCoManhua(OhManhua) 1.2.10 chinese

### Steps to reproduce

1. Open any comic's chapter or select download chapter from CoCoManhua.

### Expected behavior

When select any chapter it should load the page of the chapter.
When select download it should start downloading. 

### Actual behavior

page closed immediately and showed "decryption failed" message for 1 second without any error code.
Unable to download the chapters after press download. 

### Tachiyomi version

0.13.1

### Android version

Android 8.0.0

### Other details

Screenshot_20220406-221729

I have tried open through webview, there are no issue reading the comics through webview. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by alessandrojean**
The source is encrypting the images URL and changing the encryption algorithm and keys frequently, not worth to keep playing the game. Users should migrate to better sources.

I will submit a separate PR later to add it to the issue autocloser (to avoid merge issues with the other PR).

Closes #11334.
Closes #11345.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by whghjyh** [comment]
I'm sad that there are less and less Chinese extensions on Tachi.I hope more people will be willing to make Chinese extensions.😳😳

**Comment by trojblue** [comment]
OH is one of the good image sources out there. Good image quality and lots of copyrighted comics. It was really unfortunate to see it getting closed, as I have around 70 comics from this source.  Hopefully someone would be willing to keep up updating it.

**Comment by alessandrojean** [comment]
It's not removed yet, and even I don't know if the PR will be merged. But it's ideally not worth keeping the support to sources in a cat and mouse game as it is exhaustive.

**Comment by xuanranran** [comment]
I hope it can be updated continuously. Almost all my Chinese comics come from COCO. The comics in COCOMANGA are relatively comprehensive, so I still hope to continue to update!🥺

**Comment by alessandrojean** [comment]
I marked the PR as a draft to see for about a week if any contributor wants to try fixing it one last time, but even if someone submits a fix and they break it right after, it's just another proof they're in a cat and mouse game with us.

It's not worth to keep support to sources that clearly don't want the extension to work. It's time to consider migrating will be the only option soon.

**Comment by alessandrojean** [comment]
Site owners already changed the website again after the last PR that fixed it was merged, so another proof we're in a cat-and-mouse game.

**Comment by alessandrojean** [comment]
@mergifyio rebase

**Pull request closed without merging**
