### PR TITLE
Re: Use Gradle version catalog to simplify dependencies

### PR DESCRIPTION
**Pull request by ghostbear**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by arkon** [comment]
I'm wondering if the previous build failures are related to the action's caches?

**Comment by ghostbear** [comment]
> I'm wondering if the previous build failures are related to the action's caches?

Mayhaps, I will wait for #10952 to be merged and rebase my changes

**Comment by CarlosEsco** [comment]
@ghostbear This good to go?

**Comment by ghostbear** [comment]
Yep

**Pull request merged**
