### PR TITLE
MangaDex: Scanlation Group blocking

### PR DESCRIPTION
**Pull request by curche**
*The setting everyone's been waiting for (but not how they expected to be: random UUIDs waves hello)*

Adds option to block Scanlation groups by entering them as a comma-separated list of UUIDs

By Default, this blocks the External Link Official Groups (Bilibili, Comikey, Azuki, Mangaplus).
Note that this disables ALL bilibili chapters: including the *exception-causing* ones that are uploaded to dex and readable on dex ([Eg like this:](https://mangadex.org/title/e1c2aace-d3fb-453a-a580-886405ca27f4/ceo-s-sudden-proposal))

### Notes: 

 - First time having to deal with Preferences, that too a string plain text
 - Checked how Komga, Lanraragi does it and worked from that
-  Tried to make it a Set of Strings but ended up crashing the Extension settings page oof
   Welcoming any changes for dealing with this, thanks!

 PS. I feel this might be the jankiest PR I have sent uptil now phew (jk its [not](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/01ecbdc8337681d9a943ca18bc05bf95f1baa7ab/src/en/reallifecomics/src/eu/kanade/tachiyomi/extension/en/reallifecomics/RealLifeComics.kt#L72) :p)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by curche** [comment]
Closes #10291

**Comment by curche** [comment]
Should I block the External Link Official Groups (Bilibili, Comikey, Azuki, Mangaplus etc) explicitly as well? Right now, its the default value for blocking which can edited by just clearing the setting

**Comment by alessandrojean** [comment]
> Tried to make it a Set of Strings but ended up crashing the Extension settings page oof

Probably happened because you used the same key for the preference (the setting expect the key to be a String, since you're using a `EditTextPreference` and it crashes when it sees the preference is a String set instead, I guess).

You can try to save it as a String set using another key.

**Comment by curche** [comment]
> > Tried to make it a Set of Strings but ended up crashing the Extension settings page oof
> 
> Probably happened because you used the same key for the preference (the setting expect the key to be a String, since you're using a `EditTextPreference` and it crashes when it sees the preference is a String set instead, I guess).
> 
> You can try to save it as a String set using another key just for it.

Nah, it was crashing on the first fresh install. Looking at the docs later, [EditTextPreference](https://developer.android.com/reference/androidx/preference/EditTextPreference) only saves as a String so that was probably it

**Comment by IPTN** [comment]
Where do you go to edit these preferences for the extension/source?

**Pull request merged**
