### PR TITLE
ReadComicOnline: fix selector

### LINKED ISSUE #9879: ReadComicOnline not working
### Source information

ReadComicOnline 1.2.10

### Steps to reproduce

Try to open a comic

### Expected behavior

It should work normally

### Actual behavior

When i try to read a comic, It says "Pages not found"

### Tachiyomi version

1.4.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #11141: ReadComicOnline "No results found"?
### Source information

ReadComicOnline 1.2.10

### Steps to reproduce

1. Open up the tachiyomi app
2. Click on ReadComicOnline extension
3. No homepage appears only "No results found"

### Expected behavior

I should see the comic covers upon clicking the extension and be able to search titles.

### Actual behavior

Nothing appeared and "No Results Found" was the only thing there. I tried to retry and restart my app to no avail. I also tried searching for titles in the search bar but "No Results Found" also appeared. 

### Tachiyomi version

0.13.1

### Android version

11 RKQ1.200826.002

### Other details

When opened in WebView, the site seems to be working. As well as if you click on the titles from the history, it loads properly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #11141 
Can't reproduce #9879 , so Closes #9879

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Devthereader** [comment]
Thank you

**Comment by Devthereader** [comment]
It’s still not working

**Comment by arkon** [comment]
The update isn't even available yet. You need to wait for it to build and then you need to update your extension.

**Comment by Devthereader** [comment]
Ah ok thanks

**Pull request merged**
