### PR TITLE
change base url manhwalist

### LINKED ISSUE #16422: Manhwalist: URL changed
### Source information

Manhwalist

### Source language

Indonesia

### Source new URL

manhwalist.xyz

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by TesyarRAz**
closes #16422

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by TesyarRAz** [comment]
> Did you not test the changes?

i cant test this

**Comment by TesyarRAz** [comment]
> Will mark this as draft, when you manage to test, comment it out.

can you help me run it?, for individual extensions I can, but for multisrc I don't know how

**Comment by alessandrojean** [comment]
Follow the CONTRIBUTING.md guide, there's sections on how to run individual and multisrc extensions there.

**Comment by TesyarRAz** [comment]
@alessandrojean

**Pull request merged**
