### PR TITLE
TMO and LectorManga: Remove paginated mode for load chapter's images and fix TMO

### LINKED ISSUE #11154: Lector Manga: Chapter images do not load
### Source information

Lectormanga 1.2.21

### Steps to reproduce

1. Entrar a cualquier historia que sea de Tumangaonline ó Lectormanga

2. Al ir cargando el capítulo solo hasta la imagen número 10 carga 

3. Para q cargue lo demás, debes salir de app y esperar unos minutos siendo bastante estresante 

### Expected behavior

Debería seguir cargando fluidamente como las anteriores imágenes sin problema

### Actual behavior

No carga de la imagen 10 hacia adelante, a menos que  salgas de la app a otra y esperar para que cargué todo unos minutos
Screenshot_2022-03-17-03-13-49-063_eu kanade tachiyomi
Screenshot_2022-03-17-03-15-31-126_eu kanade tachiyomi

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

Esto ya de había arreglado antes, pero después de una actualización de la extensión volvió este problema

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #16344: TuMangaOnline: Images dont download by ssl error
### Source information

TuMangaOnline

### Source language

Spanish

### Steps to reproduce

The new version of extension TuMangaOnline not fix the ssl problem shows in this issue #16263.

### Expected behavior

Example in the original issue

### Actual behavior

Example in the original issue

### Tachiyomi version

0.14.6

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #16413: TuMangaOnline no Found Images
### Source information

TuManagaOnline 1.4.42

### Source language

Spanish

### Steps to reproduce

app automatic download new chapters

### Expected behavior

Download the chapter without error

### Actual behavior

the extension found the new chapter but not download the images , errror pop up saying "NO pages found"

### Tachiyomi version

0.14.6

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

The pagination mode doesn't work as it should because sometimes the pagination method relies on changing the URL (a lot of requests which causes error 429) and other times it loads the images via JavaScript. I could add a way to handle both cases, but I think it's better to remove it and only use the cascade mode.

Closes #16344 -> I think the issue refers to the "no pages found" error when downloading instead SSL error, this happens because if you send the baseUrl in the header, this redirects you to a non-functional reading page, the opposite of LectorManga, where you have to send the baseUrl as Referer.

Closes #11154 
Closes #16413

### CODE REVIEW

**Comment by Kytoh** [comment]
Very efficient, my congratulations :)

**Comment by seew3l** [comment]
> "Probably fixes". 

Anyway, can you provide the manga you have the problem with?

**Comment by Kytoh** [comment]
> > "Probably fixes".
> 
> Anyway, can you provide the manga you have the problem with?

https://lectortmo.com/library/manhwa/57722/en-esta-vida-sere-la-soberana

**Comment by Kytoh** [comment]
It seems 429 error but not managed by Exception, cause if you wait a bit, there are no errors and the chapter is downloaded correctly

**Comment by seew3l** [comment]
> It seems 429 error but not managed by Exception, cause if you wait a bit, there are no errors and the chapter is downloaded correctly

Reduce the rate limit for the page in the extension settings

**Comment by Kytoh** [comment]
I have the default 10/10. 
I said only "seems", cause now i have more than 5 minutes without downloading anything and i still have the "No pages" error, and this was happening to me all day

**Comment by seew3l** [comment]
> I have the default 10/10.

Reduce it anyway (8 works fine for me), are you using paginated mode?

**Comment by Kytoh** [comment]
I'll change to 8, currently "Cascade", maybe on Paginated will be better?

**Comment by seew3l** [comment]
> I'll change to 8, currently "Cascade", maybe on Paginated will be better?

No, it doesn't work well, that's why I'm removing it

**Comment by Kytoh** [comment]
I'm having this error currently.

image

Sorry ^^'

**Comment by Kytoh** [comment]
Hi again seew3l, I've been trying with 8 and i still get the same error, dont know if this is the problem really with TMO cause i had the rate limit to 20 a while ago and it worked fine

**Comment by seew3l** [comment]
Reducing the rateLimit only helps prevent the 429 error, if you're getting a no pages found error this PR should fix it.

**Comment by Kytoh** [comment]
Yep, but i was checking the PR and you removed the option to select the rateLimit, right?

**Comment by Kytoh** [comment]
Yep, but i was checking the PR and you removed the option to select the rateLimit, right?

**Comment by Kytoh** [comment]
Ok, i though you deleted the selector on the extension, sorry :)

**Review by alessandrojean — APPROVED** [review]

**Comment by Kytoh** [comment]
Sorry for disturbing, do you know when it will pulled to master?

**Pull request merged**
