### PR TITLE
Update Japscan

### PR DESCRIPTION
**Pull request by zormy111**
Japscan has again changed its obfuscation, but it is the most complete source of French scans, so don't give up. It is now impossible to recover the two encryption keys only with the reading of the JS file. But if we execute the javascript we can quite easily recover the two decryption keys thanks to the debugger, so with a single instance of a browser it is possible to recover the keys and share them with everyone!

This is what I managed to set up: https://gist.github.com/zormy111/f6abdc7f9385e95203e2b6a64af15ea3/revisions

The JS script changes its key and the name of its variables at each time change, it's a fixed time, thanks to a nodejs script I get the two keys and I modify my gist to share them, they are global keys they can therefore be used by anyone.

What it changes: There is a server dependency, however I think it is better to choose this system because it will be much more stable than a script that tries to read the key in the obfuscated JS.

**Do I have to share my node.js script?**

I could make it public, however, I think I understood that the japscan site was closely monitoring the current extension and as soon as we find a solution they quickly patch the code in a simple way, if I keep it on the server side ( and I remind you that it concerns ONLY the decryption keys and nothing else) they will have a lot more trouble patching or even not being able to patch it if they keep the same system.

For me it works very well, the script recovers the key without worries and adapts as it should to each change of script, I undertake to maintain it as best as possible (I am a very regular user of the application). If it happens that I no longer maintain for some reason I will share my script.

I also specify that only mobile user agents work because the script changes depending on whether it is a pc user agent and a mobile user agent. (My script retrieves the one from the mobile)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by zormy111** [comment]
Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17478

**Comment by curche** [comment]
While I appreciate your commitment to maintaining the script/gist so that the extension can figure out the keys in real-time (for as long as you maintain it and they use the same setup), ...
...I believe it'd be better to merge both efforts (#17585 and #17543) so that the extension has the option to either use your approach OR let the user enter the keys themselves (if you werent fast enough to update keys or are busy irl). This lets users not wait and figure out the keys themselves if they can. Maybe you can have a public gist for that node.js script sooner right now than later although I'm not sure how japscan will retaliate to that.

Now all this hinges on the fact that japscan continues to use the same algorithm and just keeps rotating keys but I assume that you are confident that they won't change it anytime soon.

tbh, given the history between tachiyomi and japscan, I'd rather just remove the extension completely and end this chapter for good but if you're trying to continue efforts on a cat-and-mouse-game, I provide my 2 cents. There are always other readers/downloaders available.

Additionally, perhaps it might be a good idea to increase the rate limit to make it even more strict
Also, the `Closes ##` has to be made in the first comment otherwise it doesn't work

**Comment by zormy111** [comment]
Thank you for your answer, actually it's not just those readers but the French scans are generally very badly referenced except on this site, hence the importance for a large part of us of maintaining it. It is a very good idea to use the possibility of custom keys in parallel with the key search. This will allow anyone who knows how to decipher the scans for a short time. I made all these modifications and shared my nodejs code: https://github.com/zormy111/japscangetkey

**Comment by Rajh** [comment]
I'm not an expert and I don't have that much time to dig into it, but if anyone want to improve the preferences feel free to do it :)

I just did it as a workaround when the extension break, it could use 2 settings instead of splitting it though...

**Comment by alessandrojean** [comment]
I think at this point it would just be better to remove the extension, doesn't seem a good thing on depending at a external Gist. Can be removed as a cat and mouse game again, it's causing a lot of trouble and they will sure find a way to break your approach as soon it gets merged.

**Comment by zormy111** [comment]
As you want it's up to you, on my side in an unnoficial way I would continue to maintain anyway, and many people will go through an unnoficial version if it is deleted, but if to make your repo clean of plugins you decide to remove I would understand. As explained previously, there is no other real reliable and complete source for French scans, even mangadex only provides very few complete lists (many missing chapters). If this does not bother you on the side of your organization, it is currently preferable in my opinion to leave it as long as there is no better source. Whatever your decision thank you for your answers and your attention for these requests 👍

**Pull request closed without merging**
