### PR TITLE
Fix android studio 'duplicale content roots' error

### PR DESCRIPTION
**Pull request by AriaMoradi**
Fixes this error:
screenshot_20201219_231141

And causes android studio to recognize extension modules correctly.
screenshot_20201219_225946

More info on discord: https://discord.com/channels/349436576037732353/566590778323763207/789923169174552576

### CODE REVIEW

**Comment by arkon** [comment]
Is the diff just copying the same manifest to every module?

**Comment by AriaMoradi** [comment]
> Is the diff just copying the same manifest to every module?

yes
and common.gradle
yet some extensions have their own AndroidManifest so I didn't overwrite them(i.e. all.nhentai)

**Comment by arkon** [comment]
> yet some extensions have their own AndroidManifest so I didn't overwrite them(i.e. all.nhentai)

They need to be merged.

I sort of hope there's a better way than copying them all though, it's a bit prone to error.

**Comment by AriaMoradi** [comment]
> I sort of hope there's a better way than copying them all though, it's a bit prone to error.

It's the only way to fix that error

**Comment by AriaMoradi** [comment]
here's the list of those that have their own AndroidManifest:
```
        modified:   src/all/ehentai/AndroidManifest.xml
        modified:   src/all/hitomi/AndroidManifest.xml
        modified:   src/all/mangadex/AndroidManifest.xml
        modified:   src/all/mangadventure/AndroidManifest.xml
        modified:   src/all/nhentai/AndroidManifest.xml
        modified:   src/en/guya/AndroidManifest.xml
        modified:   src/en/hentai2read/AndroidManifest.xml
        modified:   src/en/myhentaigallery/AndroidManifest.xml
        modified:   src/en/naniscans/AndroidManifest.xml
        modified:   src/en/tsumino/AndroidManifest.xml
        modified:   src/es/lectormanga/AndroidManifest.xml
        modified:   src/es/tmohentai/AndroidManifest.xml
        modified:   src/es/tumangaonline/AndroidManifest.xml
        modified:   src/pt/unionmangas/AndroidManifest.xml
        modified:   src/ru/libmanga/AndroidManifest.xml
        modified:   src/zh/manhuagui/AndroidManifest.xml

```

**Comment by AriaMoradi** [comment]
This solution doesn't break the extensions mentioned.

**Review by arkon — CHANGES_REQUESTED** [review]
This can be simplified now, as mentioned in #5214.

**Comment by AriaMoradi** [comment]
done

**Comment by AriaMoradi** [comment]
I'll update contributing in this PR too

**Review by arkon — APPROVED** [review]

**Pull request merged**
