### PR TITLE
Generate a totally random user-agent

### PR DESCRIPTION
**Pull request by vic-blt**
Related to #5850

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Just so you know, this user agent can easily be blocked with a regex: `[a-zA-Z0-9]{10,30}`.

**Comment by vic-blt** [comment]
For sure, but it would also match valid user agents and block users reading from browsers.

**Comment by ObserverOfTime** [comment]
Browser user agents aren't usually between 10 and 30 characters.

**Comment by vic-blt** [comment]
User agents aren't only about browsers.
But I agree with you that it's not effective at all.
For proof it's been blocked easily.

**Pull request merged**
