### PR TITLE
fix reaperscans

### LINKED ISSUE #13883: Reaper scans: Error 429
### Source information and language

ReaperScans 1.3.36

### Steps to reproduce

Have lots of series in library
Update library

### Expected behavior

Check for updates

### Actual behavior

Fails and gets error 429

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Rate Limiting needed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #13886: Reaper Scans:Json token error
### Source information and language

Reaper Scans 1.3.36

### Steps to reproduce

Trying to update the manhwas in the library 

### Expected behavior

Should update normally 

### Actual behavior

Update fails and gives JSON token error

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Screenshot_2022-10-17-08-12-28-51_8d485484d290ec17555e7acc83d01a83

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #13909: Reaper Scans (English): LiveWireData error
### Source information and language

Reaper Scans 1.3.37

### Steps to reproduce

1. Try to update any entry of the source
2. LiveWireData error occurs

### Expected behavior

Should be able to update any entry as usual.

### Actual behavior

Can't update any entry.

### Tachiyomi version

0.13.6

### Android version

Android 12

### Other details

Screenshot_20221018-193837_Chrome

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by henrik9999**
Closes #13886
Closes #13883
Closes #13909

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by henrik9999** [comment]
> merge didnt fix issues. please take another look.

The build isn't even out yet.... since the pipeline is failing

**Comment by ihatecaptchas** [comment]
> > merge didnt fix issues. please take another look.
> 
> The build isn't even out yet.... since the pipeline is failing

i know but i tested a 1 on 1 copy of what you guys did and issues are still coming up
youll see.

**Comment by alessandrojean** [comment]
Build is now fixed and available. If it isn't already working again, blame Reaper for the cat and mouse game and start considering using other sources.

**Comment by marccremer** [comment]
I havent looked at the code, but is this a content-crawl-countermeassure or simply their new website changing some stuff ?

**Comment by alessandrojean** [comment]
Potentially the first as they changed things again right after this PR was created.

**Pull request merged**
