### PR TITLE
Update mangafreak base url to the latest working version

### LINKED ISSUE #14376: Mangafreak base url update
### Source information and language

Mangafreak 1.3.7

### Source new URL

https://w14.mangafreak.net/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by ashley-how**
Closes #14376.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by alessandrojean** [comment]
Please do follow the checklist

> Updated `extVersionCode` value in `build.gradle` for individual extensions

**Comment by ashley-how** [comment]
> Please do follow the checklist
> 
> > Updated `extVersionCode` value in `build.gradle` for individual extensions

Have done so!

**Comment by vetleledaal** [comment]
I don't think "Closes issue #xyz" is recognized properly. Make sure it follows the suggested pattern "Closes #xyz" or [one of the alternatives](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by ashley-how** [comment]
> I don't think "Closes issue #xyz" is recognized properly. Make sure it follows the suggested pattern "Closes #xyz" or [one of the alternatives](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

Rectified this part thanks!

**Pull request merged**
