### PR TITLE
Remove Sources that are down

### LINKED ISSUE #4535: [Bug] <madara - mangazuki.online>: <no chapters found>
## Device information
- Tachiyomi version: stable 0.10.5
- Android version: 10

## Source information
- Name: Madara (mangazuki.online)
- Extension version: 0.1.2.139

## Steps to reproduce
1. opens manga catalog
2. clicks on chosen manga

### Expected behavior
the correct behavior criteria, all the chapters found, even the current ones

### Actual behavior
the "no chapters found" message appears

## Other details
i do know why this happens and the motive is that mangazuki.online has changed it, now the domain address is kissmanga.link, but apparently there are some people who dont know about it yet and i am here just for begging please can someone change the domain😭😭😭😭😭😭😭😭

### LINKED ISSUE #5714: [Invalid Sources] List of sources that might be broken
I opened all websites in the Spreadsheet (Multi-src), these are the websites that had issues:

### Opens sketchy websites:

Source | Website
-- | --
HanaScan (Raw QQ) | http://rawqq.com
Midnight Haven | http://midnighthaven.shounen-ai.net
Storm in Heaven | http://storm-in-heaven.net
Miracle Scans | http://miraclescans.com

### Domain pending renewal

Source | Website
-- | --
Tsubaki No Scan | https://tsubakinoscan.com
MangaZuki.xyz | http://mangazuki.xyz

### Domain parked

Source | Website
-- | --
Manga18 Fun | https://manga18.fun
Raider Scans | https://raiderscans.com
WeScans | https://wescans.xyz
Komik Go | https://komikgo.com
KingzManga | http://kingzmanga.com

### Host misconfiguration

Source | Website
-- | --
مانجا عرب اون لاين | https://mangaarabonline.com
Einherjar Scan | https://einherjarscans.space
MangaCultivator | https://mangacultivator.com
NTS Void Scans | https://ntsvoidscans.com
Prime Manga | https://primemanga.com
DoujinYosh | https://doujinyosh.work
Mangatensei | http://www.mangatensei.com
Matakomik | https://matakomik.com
Fallen World Reader | https://faworeader.altervista.org
The Phoenix Scans | http://www.phantomreader.com
مانجا اولاو | https://olaoe.giize.com

### ERR_CERT_AUTHORITY_INVALID

Source | Website
-- | --
Nikushima | https://azbivo.webd.pro

### DNS_PROBE_FINISHED_NXDOMAIN

Source | Website
-- | --
MangazukiClubJP | https://mangazuki.club
MangazukiClubKO | https://mangazuki.club
Just For Fun | https://just-for-fun.ru
TurkceManga | https://turkecemanga.com
NoxSubs | https://noxsubs.com
KomikIndo | https://www.komikindo.web.id
18LHPlus | https://18lhplus.com
ATM-Subs | https://atm-subs.fr
Nazarick Scans | https://nazarickscans.com

### ERR_CONNECTION_TIMED_OUT

Source | Website
-- | --
Ajia no Scantrad | https://ajianoscantrad.fr

### Suspended by hosting provider

Source | Website
-- | --
KomikRu | https://komikru.com

### Might have database errors

Source | Website
-- | --
KaisarKomik | https://kaisarkomik.com

### Product activation error

Source | Website
-- | --
Mangakyo | https://mangakyo.me

### Error 521: Web server is down

Source | Website
-- | --
FR Scan | https://frscan.me
MangaShiro | https://mangashiro.co

### Error 526: Invalid SSL Certificate
Source | Website
-- | --
ToonPoint | https://toonpoint.com

### Error 404: Not found

Source | Website
-- | --
AlianzaMarcial | https://alianzamarcial.xyz
Spooky Scanlations | https://spookyscanlations.xyz
MangazukiOnline | https://www.mangazuki.online

### Error 403: Forbidden

Source | Website
-- | --
Baixar Hentai | https://leitura.baixarhentai.net

### Not loading

Source | Website
-- | --
ZManga | https://zmanga.org

### Might be shutting down

Source | Website
-- | --
StageComics | https://stagecomics.com

### Website requires login

Source | Website
-- | --
MMScans | https://mm-scans.com

### LINKED ISSUE #6495: [Bug] <ComicLatest>: <HTTP 404 error>
## Device information
- Tachiyomi version: 0.10.9
- Android version: 8.1.0

## Source information
- Name: ComicLatest
- Extension version: 1.2.1

## Steps to reproduce
1. Open the app
2. Go to extension
3. Click on ComicLatest extension

### Expected behavior
It should show the available comics.

### Actual behavior
It is giving HTTP 404 error.

## Other details
I think the domain has moved to another. When clicking on webview it is taking to https://readcomicsfree.com/

### LINKED ISSUE #7042: [Bug] Renascans: They probably shut down
## Device information
- Tachiyomi version: Preview r3002
- Android version: 10

## Source information
- Name: Renascense Scans (Renascans
- Extension version: v1.2.3

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
It should work.

### Actual behavior
NXDOMAIN. Neither http://renascans.com/ nor http://new.renascans.com/ loads, so I'm assuming they've abandoned scanlation.

## Other details
Their last release was 2 months ago, and third last was 7 months ago. https://www.mangaupdates.com/groups.html?id=9482

### LINKED ISSUE #7231: [Bug] <comiclatest>: <getting a 521 error in trying to get a list while "latest" works>
## Device information
- Tachiyomi version: 0.10.12
- Android version: 10 patch level 03/2021

## Source information
- Name: comiclatest
- Extension version: 1.2.2

## Steps to reproduce
1. go to source, press on comiclatest. i get an error 521, it works on webview.
2. if i press on "latest", i have access to the latest comics available.

### Expected behavior
have a view of all the comics, not only the latest ones, and being able to search.

### Actual behavior
HTTP error 521, going into webview and refresh does not change the situation

## Other details
thanks for the great work. i really appreciate.

### PR DESCRIPTION
**Pull request by jopejoe1**
Sites that are Down or otherwise not usable by tachiyomi

- Parked Domains
   - miraclescans.com
   - tsubakinoscan.com
   - manga18.fun
   - raiderscans.com
   - wescans.xyz
   - kingzmanga.com
   - doujinyosh.work
   - mangaarabonline.com
   - mangazuki.club
   - zmanga.org
   - komikgo.com
   - storm-in-heaven.net
   - chiotaku.com
   - neumanga.tv
   - manga-zen.com
- Different Service
   - olaoe.giize.com -url shortener
   - matakomik.com -plex server
- Removed by Hosting site
   - faworeader.altervista.org
   - azbivo.webd.pro
- No A/AAAA/CNAME records
   - atm-subs.fr
   - just-for-fun.ru
   - mangazuki.online
   - spookyscanlations.xyz
   - alianzamarcial.xyz
   - www.komikindo.web.id
   - komikru.com
   - andromedax.net
- misconfigured/not setup
   - primemanga.com
   - einherjarscans.space
- Blank page
   - nazarickscans.com
   - mundohentaioficial.com
- Cloudflare
   - toonpoint.com
   - mangashiro.co
- Timed out
   - ajianoscantrad.fr
   - mangap.me
- redirect
   - comiclatest.com
   - mangaindo.web.id -Google DNS
   - bacamanga.cc 

Closes #5714 - Sites that I didn't remove are still providing manga from this list
Closes #7231 - redirects to readcomicsfree.com
Closes #6495 - Same as #7231
Closes #7042 - Site is not shutdown and is working fine
Closes #4535 - Due to removing the source

### CODE REVIEW

**Comment by somebody1234** [comment]
seems like bacamanga.cc now redirects to komikindo.id? this is a weird one tho since there are (were) 2 other sources named komikindo, both of which used wp manga stream, but for some reason this one was standalone? not sure if this one uses wp manga stream too, it loads really slowly for me

**Comment by jopejoe1** [comment]
> https://komikindo.id 

Not gone add Source in this pr was Request at #6031

> https://mangaku.in and https://mangaku.co both appear to redirect to https://mangaku.pro - this will need some editing to remove the specialcasing for mangaku.co

That to bug for this pr see #2530 for more info

**Comment by jopejoe1** [comment]
>     * https://mangalink.org/ gives cloudflare gateway timeout error

Seems to have gone back online just now

>     * https://003.jmana2.net/ gives cloudflare web server down error

Gone wait a few days and if it still gives Cloudflare error gone remove it

>     * https://manatoki1.net/ seems to redirect to weird redirect website???

Changes the number behind the name regularly so it's manually changed in the app by the user

>     * https://tkor.cx/ seems to redirect to https://tkor.baby/ - warning: flashing images

Open an issue request to change the URL

>       i won't be checking english and all since i'm assuming those have already been checked.

There are many sources down in English as there a just too many sources to be checked

**Comment by somebody1234** [comment]
thanks for the updats, back now:
- https://www.scan-manga.com/ region locked? so can't check
- https://www.tohomh123.com/ has an A record pointing to 127.0.0.1 (localhost)...
russian, french, vietnamese, chinese sources checked.

**Comment by CarlosEsco** [comment]
I'm pinging you if there are any complaints :smile:

**Comment by somebody1234** [comment]
forgot to check multisrc modules... oh well. can probably check those tomorrow or something

**Pull request merged**
