### PR TITLE
HentaiVN: update domain

### PR DESCRIPTION
**Pull request by CuongBa956**
Checklist:

- [✓ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ✓] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [✓ ]Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [✓] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [✓] Have not changed source names
- [✓] Have explicitly kept the `id` if a source's name or language were changed
- [✓] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by CarlosEsco** [comment]
need to bump version

**Comment by vetleledaal** [comment]
As Carlos said, bump the version. Also update the old URL in `chapterListRequest()`, like so:
```patch
---
 src/vi/hentaivn/build.gradle                                    | 2 +-
 .../src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt   | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/vi/hentaivn/build.gradle b/src/vi/hentaivn/build.gradle
index bf4cfabfd..62dea5a77 100644
--- a/src/vi/hentaivn/build.gradle
+++ b/src/vi/hentaivn/build.gradle
@@ -5,7 +5,7 @@ ext {
     extName = 'HentaiVN'
     pkgNameSuffix = 'vi.hentaivn'
     extClass = '.HentaiVN'
-    extVersionCode = 14
+    extVersionCode = 15
     isNsfw = true
 }
 
diff --git a/src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt b/src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
index 2ae7ade32..66764de82 100644
--- a/src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
+++ b/src/vi/hentaivn/src/eu/kanade/tachiyomi/extension/vi/hentaivn/HentaiVN.kt
@@ -73,7 +73,7 @@ class HentaiVN : ParsedHttpSource() {
 
     override fun chapterListRequest(manga: SManga): Request {
         val mangaId = manga.url.substringAfterLast("/").substringBefore('-')
-        return GET("https://hentaivn.fun/list-showchapter.php?idchapshow=$mangaId", headers)
+        return GET("$baseUrl/list-showchapter.php?idchapshow=$mangaId", headers)
     }
 
     override fun imageUrlParse(document: Document) = ""
-- 
2.38.1


```

**Comment by CarlosEsco** [comment]
The other PR has been merged

**Pull request closed without merging**
