### PR TITLE
Kiryuu: use new url, move factory/multisrc

### LINKED ISSUE #6989: [Bug] Kiryuu.co: They Move To New Site
I realized my bookmark from this source : kiryuu.co not updating anymore. I check the latest update tab and it didn't show the new manga/manhwa. So, I went to their site and saw that they have changed their site to the new one from { https://kiryuu.co/ to the
https://kiryuu.id/. So I hope that you can update their new site on the old source. Thank you

### PR DESCRIPTION
**Pull request by Riztard**
- change to kiryuu.id url
- move multisrc from wpmangastream to wpmangareader 
- fix indent in wpmangareader generator
Closes #6989

### CODE REVIEW

**Comment by CarlosEsco** [comment]
This has conflicts, once you fix i will merge

**Comment by CarlosEsco** [comment]
? still conflict lol

**Comment by CarlosEsco** [comment]
fyi in the future just merge origin/master -> your branch lol

**Comment by Riztard** [comment]
or merge faster :whip:

**Pull request merged**
