### PR TITLE
[RU]Remanga PUT chapters on alt img server

### PR DESCRIPTION
**Pull request by e-shl**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by e-shl** [comment]
What is the easiest way to show TOAST when opening a chapter? If possible from under the extension.

**Comment by arkon** [comment]
Search for `Toast.makeText` in the repo. You'd ideally only use it for preferences though, exceptions messages are shown as messages otherwise.

**Comment by alessandrojean** [comment]
If you really need to, you can use `Injekt` to get the context from the Application to use in a toast.

**Comment by e-shl** [comment]
> use `Injekt`

I don't understand. How?

`Injekt.get<Application>().applicationContext` - causes an error

**Comment by e-shl** [comment]
@alessandrojean ?

**Pull request merged**
