### PR TITLE
Add source 247manga

### LINKED ISSUE #7389: [Source Request] <247manga>
## Source website
- Name: 247manga
- Link: https://247manga.com/
- Language(s): English

## Other details
Madara

### PR DESCRIPTION
**Pull request by somebody1234**
Closes #7389

### CODE REVIEW

**Comment by jopejoe1** [comment]
You only added icons in this one.

**Comment by CarlosEsco** [comment]
converted to draft until this i resolved

**Comment by somebody1234** [comment]
oops... not sure how i managed to do that. will fix asap

**Comment by somebody1234** [comment]
i think i messed up stashing actually

**Pull request merged**
