### PR TITLE
Add new multisrc extension (Weebreader)

### LINKED ISSUE #7908: Arang Scans: No Longer Using Madara
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Not applicable

### Android version

Not applicable

### Source information

Arang Scans 1.2.10

### Steps to reproduce

Attempt to use the extension in any way

### Expected behavior

Normal extension things

### Actual behavior

Returnw HTTP 521

### Other details

Seems to be using: https://github.com/Dinokin/WeebReader

Users will have to migrate titles after a fix is pushed -> uses different URL scheme

### PR DESCRIPTION
**Pull request by h-hyuuga**
This pull request adds new multisrc extension weebreader to the repo.

Sources:

* NaniScans (Used as the base implementation)
* Arang Scans

Close #7908

### CODE REVIEW

**Comment by Daktyl198** [comment]
Why not use the weebreader API that's available, like this other extension is doing?
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/naniscans/src/eu/kanade/tachiyomi/extension/en/naniscans/NaniScans.kt

**Comment by h-hyuuga** [comment]
> Why not use the weebreader API that's available, like this other extension is doing?
> https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/en/naniscans/src/eu/kanade/tachiyomi/extension/en/naniscans/NaniScans.kt

Had no idea there was an API.

Thanks for bringing this to my attention

**Comment by CarlosEsco** [comment]
this WIP then so you can switch to api?

**Comment by h-hyuuga** [comment]
> this WIP then so you can switch to api?

I already did.

**Pull request merged**
