### PR TITLE
[CI SKIP] Describe some of SManga fields

### PR DESCRIPTION
**Pull request by AriaMoradi**

### CODE REVIEW

**Comment by AriaMoradi** [comment]
Also I noticed `@Deprecated` annotations on `Source` should I change the documentation and encourage implementing these methods?

**Comment by arkon** [comment]
No, not yet.

**Comment by AriaMoradi** [comment]
@arkon
Are you sure your edits are correct about `SManga.status`?

Its a Int that reflects one of those values from the companion object...

**Comment by arkon** [comment]
Are you confused by the quoted "enum"? Perhaps it's confusing to non-native speakers.

**Pull request merged**
