### PR TITLE
Added HentaiMimi

### LINKED ISSUE #6683: [Source Request] <hentaimimi>
---
## Source website
- Name: hentaimimi
- Link: https://hentaimimi.com/
- Language(s): English (havent check all of em but i think its fully english)

### PR DESCRIPTION
**Pull request by jopejoe1**
Doesn't have an icon as I could not find one.
Closes #6683

### CODE REVIEW

**Comment by joseph619** [comment]
@as280093 Need icons

**Comment by kiyoko123** [comment]
we need this to be added first and think about icons later kekw
cc @CarlosEsco

**Comment by CarlosEsco** [comment]
> we need this to be added first and think about icons later kekw
> cc @CarlosEsco 

Or we can just wait

**Comment by kiyoko123** [comment]
> Or we can just wait

Just pull it already 👀

**Comment by CarlosEsco** [comment]
> > Or we can just wait
> 
> Just pull it already 👀 

Or I can close it and not merge..

**Comment by annabenefiel90** [comment]
Is it possible to put search field on Filter menu? instead of scrolling and checking one by one. 
Pretty sure it's more efficient.

**Pull request merged**
