### PR TITLE
MangaHub: clear api key cookie

### LINKED ISSUE #16410: MangaHub: API rate limit excessed
### Source information

MangaHub 1.4.30

### Source language

English

### Steps to reproduce

After reading 3-4 manga chapters it shows"API rate limit excessed"

### Expected behavior

All manga chapters should have been able to read without any problem.

### Actual behavior

It shows API rate limit excessed
Screenshot_2023-05-11-20-59-18-808_eu kanade tachiyomi

### Tachiyomi version

0.14.6

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Slowlife01**
Fixes #16410

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

**Comment by Davidbolt121199** [comment]
#16410

**Comment by Davidbolt121199** [comment]
The issue remains the same

**Comment by Davidbolt121199** [comment]
The issue remains the same.
Screenshot_2023-05-14-09-24-34-548_eu kanade tachiyomi

**Comment by Slowlife01** [comment]
> The issue remains the same.
> Screenshot_2023-05-14-09-24-34-548_eu kanade tachiyomi
> 

Can't reproduce this, I tested it for awhile

**Comment by Davidbolt121199** [comment]
> > The issue remains the same.
> > Screenshot_2023-05-14-09-24-34-548_eu kanade tachiyomi
> 
> Can't reproduce this, I tested it for awhile. Try clearing cookies first

Even after clearing the cookies it continues to show 
Screenshot_2023-05-17-00-16-48-185_eu kanade tachiyomi

**Pull request merged**
